#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告発に至る経緯"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-10-31 06:56:37 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  白山市

#contents

* 2018年01月

** テレビ

*** いずれもテレビで知った、元警察官の白山市にある人気蕎麦店と、旧白峰村の八坂神社
    :LOGBOOK:
    CLOCK: [2018-10-31 水 07:02]
    :END:

　時刻は7時14分です。7時2分頃にテレビをつけ、しばらく集中していました。今日は2時過ぎに目が覚めました。しばらく起きていて、そのあと二度目をしようとしましたが、どうにも寝付けずパソコンの電源を入れ直したのは5時16分ぐらいだったように思います。

　全行で「今日は」とまでパソコンで打ち込んだタイミングで、テレビで気になるニュースが出てきました。ここ最近の関心事のワードの１つになりますが、「花園ラグビー場」で、その隣接した公園の水道で汚染された工業用水が・・・というもので、市の対応が問題視されていました。

　先週は、北九州市で砂防ダムにイノシシ2頭が転落したというニュースがあり、それも市の対応が問題視され、ふるさと納税に悪影響が出るような話にもなっていました。鳥獣保護法というような法律の問題が絡んでいたようですが、不思議と、あれだけ報道があったのに弁護士のコメントは見なかったです。

　砂防ダムというのも、今年の集中豪雨でテレビの解説を見て役割を理解しました。また、ダムの放流の件で被害が出たと住民が訴えるような報道も見かけましたが、あれも愛媛県の松山市の辺りであったように思います。この愛媛県や松山市というのも、ここ最近の関心事のワードの１つになります。

　今年はダムについての関心も強くなったのですが、きっかけがこれも白山市にあったように思います。この項目のタイトル名と新たな書面の構成については、昨日の午前中に考えが固まっていたのですが、昨日もテレビで気になることがいろいろあったので、作成に取り掛かることがありませんでした。

　書面の作成作業が停滞しがちな状況で動き出す潮目となったのは、日曜日の夜のテレビ番組でした。東京都の奥多摩の山奥にある蕎麦屋が取り上げられていたのですが、その番組の終わり頃、あるいは見終えた直後に思い出したのが、白山市の元警察官の蕎麦屋のことでした。


