#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "テスト中"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-09-24 06:31:30 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  落合洋司弁護士（東京弁護士会）

[:contents]

* 現在

** テスト中

*** 落合洋司弁護士（東京弁護士会）

▶ ツイート％yjochi（落合洋司 Yoji Ochiai 🇯🇵）％2018/09/23 17:10％ https://twitter.com/yjochi/status/1043774666299469829
<blockquote class="twitter-tweet" lang="ja"><p>石破氏は、閣外にいることで、国内外から、次の首相有力という目でますます見られ、存在感が増すだろう。こういう時は、重要閣僚で処遇するとか、封じ込めて虎を野に放たないようにすべきところだが、それができないレームダック内閣だわな。</p>&mdash; yjochi（落合洋司 Yoji Ochiai 🇯🇵}）<a href="https://twitter.com/yjochi/status/1043774666299469829">2018/09/23 17:10</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
石破氏は、閣外にいることで、国内外から、次の首相有力という目でますます見られ、存在感が増すだろう。こういう時は、重要閣僚で処遇するとか、封じ込めて虎を野に放たないようにすべきところだが、それができないレームダック内閣だわな。  
▶


▶

* 本日は

** 曇り空

*** MovableType

▶ ツイート％motoken_tw（モトケン）％2018/09/23 12:24％ https://twitter.com/motoken_tw/status/1043702735130902528
<blockquote class="twitter-tweet" lang="ja"><p>@ashibenotomaya 暴力団というのは、堅気の人を脅したりすかしたりして稼いでいるんですけど。それでも言うことを聞かないと殺したりしてますよ。無防備な堅気の人は暴力団のいい鴨です。</p>&mdash; motoken_tw（モトケン}）<a href="https://twitter.com/motoken_tw/status/1043702735130902528">2018/09/23 12:24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
@ashibenotomaya 暴力団というのは、堅気の人を脅したりすかしたりして稼いでいるんですけど。それでも言うことを聞かないと殺したりしてますよ。無防備な堅気の人は暴力団のいい鴨です。  
▶

* もうすぐ７時

** 曇り空のまま

*** MovableType

▶ ツイート％motoken_tw（モトケン）％2018/09/23 12:24％ https://twitter.com/motoken_tw/status/1043702735130902528
<blockquote class="twitter-tweet" lang="ja"><p>@ashibenotomaya 暴力団というのは、堅気の人を脅したりすかしたりして稼いでいるんですけど。それでも言うことを聞かないと殺したりしてますよ。無防備な堅気の人は暴力団のいい鴨です。</p>&mdash; motoken_tw（モトケン}）<a href="https://twitter.com/motoken_tw/status/1043702735130902528">2018/09/23 12:24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
@ashibenotomaya 暴力団というのは、堅気の人を脅したりすかしたりして稼いでいるんですけど。それでも言うことを聞かないと殺したりしてますよ。無防備な堅気の人は暴力団のいい鴨です。  
▶


　2018-09-20のツイート分析 https://t.co/aGaQ01rrX3 \n ツイート数 59590 (±0), フォロワー数 558 (-1) \n フォロー数 534 (±0), お気に入り数 42 (±0)

　閉園保育所を醤油蔵に　能登町の数馬酒造、来春から仕込み - 石川県のニュース | 北國新聞社 https://t.co/nw19ZILmyT

* 本日

** 曇り

*** MovableType　７時の音楽は終わっている９時になった。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:27／2018-09-18 17:55 URL： https://twitter.com/kk_hirono/status/1041981956785721344 https://twitter.com/s_hirono/status/1041973906326708224
&twitter(1041981956785721344){theme:light}
> 2018-09-18-175318_ノースライム（@noooooooorth）：文春砲デビューの実態を大和先生に聞く！⑥を公開しました。今回は弁護士が主体的にメディアをコント.jpg https://t.co/TnYYqY6LFY
◁◁◁

　2018-09-20のツイート分析 https://t.co/aGaQ01rrX3 \n ツイート数 59590 (±0), フォロワー数 558 (-1) \n フォロー数 534 (±0), お気に入り数 42 (±0)

　閉園保育所を醤油蔵に　能登町の数馬酒造、来春から仕込み - 石川県のニュース | 北國新聞社 https://t.co/nw19ZILmyT



<blockquote>
○京都弁護士会
・京都弁護士会遺言センター運営委員会副委員長（平成２２年度〜平成２６年度）
・同高齢者障害者センター運営委員会副委員長（平成２３年度～）

○その他
・長岡京市高齢者虐待防止ネットワーク委員会（平成２２年度～２５年度）
・ＣＳＲ普及協会近畿支部会員
・京都の異業種交流会 ＢＮＩ ３Ｗｉｎチャプター会員 http://bni-3win.com/
・公式ツイッターアカウント　@akishigemakoto
</blockquote>

　あああ

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 16:38 URL： https://twitter.com/kk_hirono/status/1041981811637678081 https://twitter.com/s_hirono/status/1041954483201236992
&twitter(1041981811637678081){theme:light}
> 2018-09-18-163654_佐藤正子（@SATOMasako）：報告しといた。.jpg https://t.co/dlnlRPwI1n
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981846639104001 https://twitter.com/s_hirono/status/1041973748667015170
&twitter(1041981846639104001){theme:light}
> 2018-09-18-164248_過食弁護士（@juntaba1）：なにこれ？わざわざ殺された秋田の何の関係もない先生の話を引っ張って来るってことは、お前恨み買って死ぬぞっ.jpg https://t.co/kCBAHqmQzS
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981870131400704 https://twitter.com/s_hirono/status/1041973780841619457
&twitter(1041981870131400704){theme:light}
> 2018-09-18-175028_ノースライム（@noooooooorth）：別に電撃的に報告してくれても構わんのやで。.jpg https://t.co/r4nhk78JKk
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981889429372928 https://twitter.com/s_hirono/status/1041973812382785536
&twitter(1041981889429372928){theme:light}
> 2018-09-18-175059_ノースライム（@noooooooorth）：他の業界のことはよくわからないが、ウチの業界には若者（特に修習生）に奢りたがっている人がやたら.jpg https://t.co/rnMowqxncX
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:27／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981908941275137 https://twitter.com/s_hirono/status/1041973843961602049
&twitter(1041981908941275137){theme:light}
> 2018-09-18-175141_ノースライム（@noooooooorth）：メインはルーアン鴨。まずソースと付け合せの野菜たちが美味しい。肉はものすごくしっかりとした肉質.jpg https://t.co/lnPYcIvgIs
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:27／2018-09-18 17:55 URL： https://twitter.com/kk_hirono/status/1041981933318631424 https://twitter.com/s_hirono/status/1041973875091824646
&twitter(1041981933318631424){theme:light}
> 2018-09-18-175230_ノースライムのリツイート（弁護士亀石倫子　@MichikoKameishi）：テレビで政権に批判的なコメントしたら、ものすごく叩かれて、事.jpg https://t.co/6OiEtTEnAb
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:27／2018-09-18 17:55 URL： https://twitter.com/kk_hirono/status/1041981956785721344 https://twitter.com/s_hirono/status/1041973906326708224
&twitter(1041981956785721344){theme:light}
> 2018-09-18-175318_ノースライム（@noooooooorth）：文春砲デビューの実態を大和先生に聞く！⑥を公開しました。今回は弁護士が主体的にメディアをコント.jpg https://t.co/TnYYqY6LFY
◁◁◁

　2018-09-20のツイート分析 https://t.co/aGaQ01rrX3 \n ツイート数 59590 (±0), フォロワー数 558 (-1) \n フォロー数 534 (±0), お気に入り数 42 (±0)

　閉園保育所を醤油蔵に　能登町の数馬酒造、来春から仕込み - 石川県のニュース | 北國新聞社 https://t.co/nw19ZILmyT

