#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料・情報"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-10-15 12:59:02 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  参考資料・情報 労災認定

#contents

* 労災認定

** 男性遺族フジと係争中　パワハラ自殺労災認定

*** 至る経緯
    :LOGBOOK:
    CLOCK: [2018-10-15 月 13:04]--[2018-10-15 月 14:37] =>  1:33
    :END:

[link:] » 新居浜 自殺 - Google 検索 https://t.co/9uPG8SCrg0

[link:] » 男性遺族フジと係争中　パワハラ自殺労災認定 | 愛媛新聞ONLINE https://t.co/TPvbDC631c

```
２０１０年７月、フジ（愛媛県松山市）が運営する新居浜市内のスポーツクラブに勤務していた男性（２７）が自殺したのは、上司のパワーハラスメントが原因として、遺族が同社と上司に計約１億２２５９万円の損害賠償を求めている訴訟に絡み、新居浜労働基準監督署が男性の自殺を労災認定していたことが４日、分かった。 
　遺族の代理人弁護士によると、認定は６月２０日付で、労基署が、上司からの暴言などで男性が精神疾患を患い自殺した、と一連の因果関係を認定したとみている。 
　約１年前に、遺族が労災申請し、労基署が関係者の事情聴取などをしていた。 
　遺族は３月、松山地裁に提訴し係争中。遺族の代理人は「パワハラによる自殺が労災認定されるケースは少ない。訴訟の今後を大きく左右する結果だ」と評価。フジは「まず冥福を祈りたい。認定の情報が入っておらず、発言は差し控える。社の考えは裁判の中で伝えたい」とコメントした。 

［source：］男性遺族フジと係争中　パワハラ自殺労災認定 | 愛媛新聞ONLINE http://www.ehime-np.co.jp/news/local/20130705/news20130705903.html
```

　テレビでバイキングを見ていました。愛媛のご当地アイドルの自殺問題です。先週の木曜日からの報道という話も今日、テレビで見かけましたが、当初は「新居浜」という地名をちょこちょこと見かけていたような気がして気になっていました。

▶ ツイート％viking_fujitv（【フジテレビ公式】バイキング）％2018/10/15 10:25％ https://twitter.com/viking_fujitv/status/1051645289705037824
&twitter(1051645289705037824){theme:light}
> 10月15日(月)の #バイキング は…
> パワハラか金銭問題か…ご当地アイドルが自殺した理由は？追いつめられた事情▽デヴィ夫人パーティにお騒がせタレント続々！カイヤ離婚騒動を松居一代＆山根明が語る
> 11時55分から放送です♪
> #バイキングくん  
▶

　上記のバイキングの番組サイドのツイートをみると、ご当地アイドルの自殺の件が先にありますが、番組では「▽デヴィ夫人パーティにお騒がせタレント続々！カイヤ離婚騒動を松居一代＆山根明が語る」が先になっていました。

[link:] 2018-10-11_113702＿テレビの画面・「農業アイドル」自殺　パワハラで提訴へ　事務所が「1億円払え」.jpg  http://hirono2014sk.blogspot.com/2018/10/2018101511092018-10-090006382018-10.html#20181011113702

　調べたところ、テレビで最初に見たのが11日の午前11時半過ぎだったようです。今日は15日なので4日前になりますが、もう1,2日前だったような気もします。個人的に愛媛県や松山市についてあらためて色々と考える機会にもなりました。

　やはりかなり時間が経過したような感覚があるのですが、当初は「新居浜」という地名を見かけていたように思います。この愛媛県新居浜市についても、他のところで書いておきたいことがあります。


