#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "職務質問の指導者、元警察官の宇野博幸氏に対する弁護士らの反応"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-10-01 11:54:07 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  元警察官、宇野博幸氏 うの字 くまえもん 富田林警察署の被疑者逃走事件 浜松市の看護師女性連れ去り殺害事件 黙秘 不起訴

#contents

* 富田林警察署の被疑者逃走事件

** 8月12日の逃走事件発生当時

*** 佐藤大和弁護士のTwitterでの反応
    :LOGBOOK:
    CLOCK: [2018-10-02 火 11:53]--[2018-10-02 火 13:45] =>  1:52
    :END:

2018年10月01日18時46分の登録： ＃レイ法律事務所代表弁護士佐藤大和　@yamato_lawyer＃のツイート／2018-08-14_1652〜2018-09-30_2308／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月01日18時46分 http://hirono2014sk.blogspot.com/2018/10/yamatolawyer2018-08-1416522018-09.html

2018年10月02日11時44分の登録： TWEET：”2018-08-13 00:17〜2018-08-14 22:43”／レイ法律事務所代表弁護士佐藤大和（@yamato_lawyer）の検索（2018年10月02日11時44分の記録23件） http://hirono2014sk.blogspot.com/2018/10/tweet2018-08-13-00172018-08-14.html

 昨日の夕方になるかと思いますが、佐藤大和弁護士のTwitterアカウントはTwilogに登録されていませんでした。意外なことにテキストリストにも未登録だったみたいなのですが、追加し、更新処理もしているかと思います。次がその記録のテキストファイルになります。

```
[10013]  % wc -l yamato_lawyer_201705201919-201809302308.txt 
3188 yamato_lawyer_201705201919-201809302308.txt
```

　改行を入れず、改行のコードを別の文字に置換しているので、3188という行数がそのままツイートの数になります。ファイル名には取得した範囲で最も古いツイートの投稿日時と最新のツイートの投稿日時を記録しています。プログラム的な自動処理です。

　ツイートのURLは次のように収集し、作業ファイルに保存した収集したツイートのURLを使い、データベースに登録しています。このデータベースに登楼したデータが、まとめ記事の作成に反映されます。

```
% egrep '2018-08-1[3-4]' yamato_lawyer_201705201919-201809302308.txt |sed -E 's/.*URL： ([^ ]+) ?.*/\1/'
```

　2018年10月01日18時46分の登録のまとめ記事で、時間的な範囲の射程からもれたものを補足しました。富田林警察署の被疑者逃走事件は、8月12日夜の発生となっていますが、テレビ等で報道が始まったのは翌13日になってからなので、8月13日以降のツイートを対象としました。

　テキストデータは、ファイルに次のように保存されています。

```
▶TW yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-09-30 23:08 URL： https://twitter.com/yamato_lawyer/status/1046401343705894912 TWEET： さて、本当にお見合い希望者がくるかな（苦笑）。万が一、たくさん希望者がきたら、「弁護士お見合い企画」ですね。田村先生、よろしくお願いいします。 https://t.co/S1RM8ghHNq  
▶RT yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）｜kunitakasai（河西邦剛） 日時：2018-09-30 22:54／2018-09-30 21:27 URL： https://twitter.com/yamato_lawyer/status/1046397941596839936 https://twitter.com/kunitakasai/status/1046375936638124033 TWEET： 【企業案件】 \n 山本健太弁護士と私が、とある商品の代理人弁護士となり商品の魅力で議論するという企業PRの仕事を頂きました🎵 \n  \n まさか自分が弁護士になり商品のPRをするとは思いませんでしたが💦もちろん全力で弁論しましたp(^^)q… https://t.co/cYn0CrrI1X 
```

　テキストデータのみだと改行が少ないということもあると思いますが、数が増えるとずいぶんとみづらくなり、見落としが出る可能性が高いと思います。見づらいだけではなく作業を効率化させるためTwitterカードを利用したまとめ記事としてブログに投稿しています。記録としてもまとめています。

　あとはWebページの目視やページ内検索ということになりますが、富田林警察署の逃走事件に関連した佐藤大和弁護士のツイート、リツイートを参考資料として次に掲載します。

▷ リツイート→yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）＞okuboka（大窪和久）｜2018/08/16 09:59／2018/08/15 12:40｜https://twitter.com/yamato_lawyer/status/1029895405826322434 ／ https://twitter.com/okuboka/status/1029573566474289152
&twitter(1029895405826322434%3E){theme:light}
> RT @okuboka: 盆だろうが正月だろうが弁護人が接見に行くのは普通のことなのに… https://t.co/qO60HzhYus  

　次は上記のツイートに引用されたツイートです。

▶ ツイート％O59K2dPQH59QEJx（ピピピーッ）％2018/08/15 11:15％ https://twitter.com/O59K2dPQH59QEJx/status/1029552007609110528
&twitter(1029552007609110528){theme:light}
> 今テレビに出ている自称犯罪ジャーナリストの小川泰平氏によると「お盆の夜に弁護士が接見をするのは不自然」だそうです。  
▶

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/08/20 00:22％ https://twitter.com/yamato_lawyer/status/1031199704120406016
&twitter(1031199704120406016){theme:light}
> 今回の逃走事件で「富田林署逃走事件、大迷惑だったテレビクルーの大追跡」（週刊ポスト）という記事があるが、テレビだけではなく、週刊誌も新聞社も同様である。自分がメディア対応をした弁護士だからわかるが、テレビ、週刊誌、新聞社には、取材のルールが必要。法律違反をしてはいけない。  
▶

　次のツイートは、佐藤大和弁護士が上記のツイートとして自己返信したツイートのようです。Twitterカードにはそのように表示されています。

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/08/20 00:15％ https://twitter.com/yamato_lawyer/status/1031197901383380992
&twitter(1031197901383380992){theme:light}
> 何か事件等があったときの「マスコミ（テレビ、週刊誌、新聞社など）間の取材のルール」をしっかりと決めるべき。取材のためだったら、平気で法律違反をしても良い、人権を侵害しても良い、人の感情を踏みにじっても良いと思っているマスコミが少なからずいることは大問題。  
▶

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/08/20 00:26％ https://twitter.com/yamato_lawyer/status/1031200696752693248
&twitter(1031200696752693248){theme:light}
> 一部の週刊誌やテレビは、取材のためだったら、建物の中まで勝手に入ってくる場合もある。また新聞社は、直接関係のない方々にまで取材をして、迷惑をかける場合がある。国民に真実を伝えたい気持ちがあるかもしれないが、法律や人権を尊重したうえでの取材をするべき。  
▶

　次はリツイートです。

▷ リツイート→yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）＞qZMza4SPDEHJBOG（花京院司）｜2018/08/20 00:40／2018/08/19 10:03｜https://twitter.com/yamato_lawyer/status/1031204289820028929 ／ https://twitter.com/qZMza4SPDEHJBOG/status/1030983577469513728
&twitter(1031204289820028929%3E){theme:light}
> RT @qZMza4SPDEHJBOG: 富田林署の件、
> 
> ・アクリル板を３０年くらい点検していなち
> ・ブザーの電池を警察で抜いていた
> ・前室に留置担当がいない
> ・憲法上保障された弁護人との秘密交通権を侵害しているとしか思えない捜査関係者とやらのリークが報道されている
> 
> のは、…  

　TwitterAPIで取得したデータは「のは、」で途切れていますが、実際のツイートは「のは、どこに通報すれば良いんですかね」となっています。「RT @qZMza4SPDEHJBOG: 」という部分は元のツイートにないので、その分、元の文字列が削られているのかもしれません。

　次も佐藤大和弁護士のリツイートになります。深澤諭史弁護士のタイムラインで見かけることの割と多い、実名の弁護士アカウントのようです。

▷ リツイート→yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）＞ryouheitakaki（高木良平）｜2018/08/20 16:51／2018/08/20 16:49｜https://twitter.com/yamato_lawyer/status/1031448696498487296 ／ https://twitter.com/ryouheitakaki/status/1031448002496319488
&twitter(1031448696498487296%3E){theme:light}
> RT @ryouheitakaki: 弁護人が被疑者被告人を逃がそうとしていたと誤解されている方々がいるようなので、正直なことをお話しますね。弁護人は、被疑者被告人を適法に釈放させたいとは思っていますが、逃げられるといろいろ面倒なので、逃げて欲しくはないですよ。逃亡の手伝いなん…  

　次は、富田林警察署の被疑者逃走事件とは特に関連性がないですが、佐藤大和弁護士が深澤諭史弁護士のツイートをリツイートしたものです。同業者として違和感を感じていればリツイートはないとも思うのですが、深澤諭史弁護士としては比較的穏当なツイートかもしれません。

▷ リツイート→yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）＞fukazawas（深澤諭史）｜2018/08/26 10:22／2018/08/26 10:04｜https://twitter.com/yamato_lawyer/status/1033525052279414784 ／ https://twitter.com/fukazawas/status/1033520572938907648
&twitter(1033525052279414784%3E){theme:light}
> RT @fukazawas: ◯いつものプロバイダ
> （＊＾ω＾）名誉毀損？プライバシー侵害？表現の自由，通信の秘密が大事だお。お前らの人生より広告料の方が大事だお。
> ◯今回のプロバイダ
> （；＾ω＾）著作権侵害！？大変だお！お友達の大企業様々が被害者だお！すぐに通信内容を監視して…  

　上記のリツイートも、文字列の途切れた部分は「すぐに通信内容を監視してブロッキングするお！」となっているので、補足をしておきます。

　次も、富田林警察署の被疑者逃走事件とは直接無関係ですが、ネットのニュース記事以外で情報を見ることがなく、ネットの反応というのもごくわずかだったということで気になる案件でした。千葉県警の現職の警察官を刑事弁護し、控訴審で逆転無罪となったようです。公然わいせつ容疑。

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/08/30 19:21％ https://twitter.com/yamato_lawyer/status/1035110133783650305
&twitter(1035110133783650305%3E){theme:light}
> 控訴審を担当した弁護人の一人として、無罪になり本当に良かった。最後まで諦めなかった本人の力です。今後は国賠も検討していますが、本人と一緒にえん罪を減らすための活動もしていきたい。千葉県警巡査に逆転無罪＝公然わいせつ、故意否定―東京… https://t.co/j8xQ0Edl0F  
▶

　ツイートに引用されたヤフーニュースの記事は削除されていますが、殆どの場合、タイトル部分を選択して右クリックのメニューから検索をすると、内容が同じと思われるニュース記事が見つかります。2箇所ほど引用してご紹介をしておきたいと思います。

```
電車内で陰部を露出したとして公然わいせつ罪に問われた千葉県警巡査に対し、東京高裁（合田悦三裁判長）が一審千葉地裁の有罪判決を破棄、逆転無罪を言い渡し、３０日までに確定したことが分かった。無罪が確定したのは、県警柏署地域課の

［source：］千葉県警巡査に逆転無罪＝公然わいせつ、故意否定－東京高裁：時事ドットコム https://www.jiji.com/jc/article?k=2018083000864&g=soc
```

```
控訴審を担当した佐藤大和弁護士は「現役警官に無罪判決が出され、復職を果たしたのは画期的」と指摘。永島巡査は、県警の取り調べで「認めないと逮捕する」などと、罪を認める上申書を書かされたといい、国家賠償訴訟を起こすことも検討しているという。（2018/08/30-16：52）

［source：］千葉県警巡査に逆転無罪＝公然わいせつ、故意否定－東京高裁：時事ドットコム https://www.jiji.com/jc/article?k=2018083000864&g=soc
```

　次のツイートも、えん罪に対する佐藤大和弁護士の考え、スタンスが色濃くあらわれているので、ご紹介をしておきたいと思います。

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/09/03 00:10％ https://twitter.com/yamato_lawyer/status/1036270254333222913
&twitter(1036270254333222913%3E){theme:light}
> 先日、えん罪事件を担当して無事に無罪となったが、一度メディアが「事件」として取り扱ってしまうと世論がメディアに誘導され「悪いことをした人間」という方向に動き出す。集団で叩き始める。いじめと同じ構造。真実が明らかになっていないにもかかわらず、人の人生を壊しにいく。異常な雰囲気。  
▶

　次に、メディアに対する厳しい注文のような佐藤大和弁護士のツイートを２つご紹介したいと思います。富田林警察署の被疑者逃走事件では、弁護士の行動の起因性も大きいと思うのですが、まるで無反省なばかりか矛先を警察批判にも転じている弁護士らに、違和感を拭えません。

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/09/03 22:39％ https://twitter.com/yamato_lawyer/status/1036609519848017920
&twitter(1036609519848017920){theme:light}
> いかにメディアに人権を守らせつつ、公平な報道をさせるかは、本当に難しい。メディアで世論の流れを作り、一度作り出した流れでメディアは動き始める。そして、どんどん話題を展開する。そして、メディア被害を生み出し、メディアが無意識の国民的な集団いじめを作り出す。  
▶

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/09/03 23:03％ https://twitter.com/yamato_lawyer/status/1036615777309224961
&twitter(1036615777309224961){theme:light}
> 本来、メディアは「国民の知る権利」のために真実を公平に報道しなければならないが、今の一部メディアは、「視聴率」「利益」のために真実を捻じ曲げ、国民が求めていないにもかかわらず、憶測や間違った情報、裏取りができていない情報、偏った内容、そして人権を侵害する内容等を放送し続ける。  
▶

　「いかにメディアに人権を守らせつつ、公平な報道をさせるかは、本当に難しい。」、これはもはや神々の領域を感じさせるものがあります。「弁護士による人権侵害」というのは見たこともないのですが、まったく無関心なのが弁護士鉄道の歴史、沿革なのだと思います。

　佐藤大和弁護士には、弁護士として追求する理想の世界観のようなものを感じます。それは深澤諭史弁護士にも感じてきたものでした。佐藤大和弁護士の場合は、テレビ等の露出も多く知名度が高いので、その影響は大きいとも思います。体操の塚原夫妻に専任されたと知り、その思いを強くしました。

　1年ほど前になりますか、YouTubeで銀河鉄道999の第1話の動画を見て、主人公が「機械の体を求めたびに出た」という物語のテーマ性があったことを思い出しました。それまで深く考えていなかったのも不思議なのですが、銀河鉄道999のことは、山口貴士弁護士のブログ記事に遡ります。

　次も、富田林警察署の被疑者逃走事件とは直接関係のない佐藤大和弁護士のリツイートになります。他の弁護士のタイムラインでもリツイートとして見ていました。弁護士業界の内幕のようですが、とても大きなことが書いてあります。

▷ リツイート→yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）＞nmr_ems（弁護士 塩見直子）｜2018/09/27 12:59／2018/09/26 19:21｜https://twitter.com/yamato_lawyer/status/1045161091204964353 ／ https://twitter.com/nmr_ems/status/1044894822727704576
&twitter(1045161091204964353%3E){theme:light}
> RT @nmr_ems: 最近離婚問題で来所された複数の依頼者から「弁護士と意思疎通ができないから案件の途中だけど弁護士を替えたい。」と言われ、よくよく聞いたらその弁護士とは一度も会ったこともなく、事務員が話を聞いて事件を受任したとのこと。そんなことしてるの某事務所だけだと思っ…  

　これも尻切れとなっていました。補足します。「事務員が話を聞いて事件を受任したとのこと。そんなことしてるの某事務所だけだと思ってたけど意外と多いのね。→続 」。続くとなっていることに気が付きましたが、続きらしいものは読んでいないように思います。

　まとめ記事として記録したものがあるのではないかと思います。

```
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
基準となる注目のツイートを含む最新110件のツイート
2017-11-08 17：17から110件：最新2018-09-28 00：03という範囲（323日6時間46分）の取得
基準となる注目ツイートの位置と内容タイムラインの該当箇所に移動

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＼弁護士 塩見直子　@nmr_ems＼最近離婚問題で来所された複数の依頼者から「弁護士と意思疎通ができないから案件の途中だけど弁護士を替えたい。」と言われ、よくよく聞いた http://hirono2014sk.blogspot.com/2018/09/nmrems.html
```

　7件目のツイートとなっていましたが、次がその直後のツイートで、ブログ記事では6件目となっているものです。

▶ ツイート％nmr_ems（弁護士 塩見直子）％2018/09/26 19:26％ https://twitter.com/nmr_ems/status/1044895993496399872
&twitter(1044895993496399872%3E){theme:light}
> →で、もっと怖いのが、その複数の依頼者が「弁護士さんて忙しいからそんなもの（直接は話を聞いてくれない）」と思い込んでいたこと。
> 直接話を聞かないで受任するなんて無責任か怠惰なだけかと・・・私の知っているまともな弁護士たちはどんなに忙しくてもきちんと依頼者対応してますよ！  
▶

　次のツイートもご紹介しておきます。間接的に富田林警察署の被疑者逃走事件と少し関連というか接点があります。それはテレビ出演での弁護士の量刑予想です。ここでは内容に踏み込まず、佐藤大和弁護士のツイートの紹介だけにとどめておきたいと思います。

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/09/29 00:31％ https://twitter.com/yamato_lawyer/status/1045697482187915266
&twitter(1045697482187915266%3E){theme:light}
> いくら芸能人でも6000万はないでしょう。自分の今までのメディア対応の経験上、法曹関係者と記載するとき、弁護士ではない（苦笑）。Yahooはほんと記事を掲載するときは一度内容を確認したほうがいい。被害者２人に示談金ＭＡＸ６０００万… https://t.co/pD44hkRWqg  
▶

　最後に掲載した佐藤大和弁護士のツイートは、該当のまとめ記事で7件目となっているものです。あらためて記事名とURLをご紹介しておきます。

［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃レイ法律事務所代表弁護士佐藤大和　@yamato_lawyer＃のツイート／2018-08-14_1652〜2018-09-30_2308／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月01日18時46分 http://hirono2014sk.blogspot.com/2018/10/yamatolawyer2018-08-1416522018-09.html

　佐藤大和弁護士といえば、テレビへの出演もありますが、書籍のようなものもけっこうな数、出しているようです。かなり多忙で睡眠不足というようなツイートも見かけていました。富田林警察署の被疑者逃走事件でも、どれだけの情報を見聞きしているのかと考えるところがあります。

** 山口県周南市での逮捕

*** 10月1日放送のバンキングに出演した佐藤大和弁護士のコメント

　バイキングの放送は平日の午前11時55分からとなっています。私の住む石川県鳳珠郡では「石川テレビ」の放送になります。その番組の始まりから、この富田林警察署の逃走犯の山口県周南市での逮捕を取り上げていたと思いますが、12時13分になって次に貴乃花親方の問題を取り上げるという告知。

　12時19分ですが、今度は番組に北村晴男弁護士が出てきました。バイキングの見出しは「”引退届””所属先変更願”は受理される？　きょう午後1時から臨時理事会開催」となっています。

　今日は、昨日の台風24号関連のニュースも多いのですが、情報番組のバイキングは、よほど大きな被害でも出ない限り、自然災害を取り上げることは少ないようにも思います。独自の視点で話題を取り上げ、深堀するという趣旨の番組です。

　これまで日大のアメフト部の危険タックル問題、和歌山県田辺市の資産家不審死事件をとりわけ徹底して取り上げてきました。佐藤大和弁護士は、和歌山の事件の関連での出演が多かったのですが、被疑者のような立場となった妻の代理人となったことで、ゴタゴタもあったらしく、暫く姿を見ませんでした。

　時刻は13時20分です。台所で昼食の洗い物を済ませていました。12時51分にバイキングは、次のニュースという告知で「故　平尾昌晃さん”約60億円遺産トラブル”三男・勇気氏の発言に次男・亜希矢氏生激白」をやっています。その中で12時57分に再び佐藤大和弁護士の姿を見ました。

　当初は、番組の初め頃に佐藤大和弁護士が出てきたので、後半は別の弁護士に交代なのかと思ったのですが、違っていました。先日もこのバイキングに田村隼人弁護士が出演していたので、忙しい佐藤大和弁護士に頼まれて代役で出たのかと想像などしていたのです。

▶ ツイート％tamura_hayato（田村勇人）％2018/09/30 21:00％ https://twitter.com/tamura_hayato/status/1046369251945144320
&twitter(1046369251945144320){theme:light}
> 弁護士よもや話動画です。
> 佐藤大和君とのお見合い希望者の釣書はフラクタル法律事務所まで！
> https://t.co/GKHXYmy84Z  
▶

▷ リツイート→noooooooorth（ノースライム）＞fractal_law（フラクタル法律事務所 fractal law office）｜2018/09/30 16:13／2018/09/25 18:46｜https://twitter.com/noooooooorth/status/1046296906052202496 ／ https://twitter.com/fractal_law/status/1044523551720521732
&twitter(1046296906052202496){theme:light}
> RT @fractal_law: #佐藤大和 弁護士，#北周士 弁護士，#田村勇人 弁護士が出演するYouTube動画の新作part9が公開されました♪
> 頭の回転速度とメディアの関係を考える。
> #フラクタル法律事務所 #弁護士 #四方山話
> 
> 文春砲デビューの実態を大和先生に聞く…  

▷ リツイート→noooooooorth（ノースライム）＞tamura_hayato（田村勇人）｜2018/09/30 16:13／2018/09/25 13:57｜https://twitter.com/noooooooorth/status/1046296865598107648 ／ https://twitter.com/tamura_hayato/status/1044450814029324288
&twitter(1046296865598107648){theme:light}
> RT @tamura_hayato: すいません！先ほどのは一個前のを重複してました！次はこれです！
> 佐藤大和弁護士の文春砲デビュー秘話ユーチューブ
> https://t.co/Pz7fA11yCV  

▶ ツイート％noooooooorth（ノースライム）％2018/09/30 12:22％ https://twitter.com/noooooooorth/status/1046238909317804033
&twitter(1046238909317804033){theme:light}
> 文春砲デビューの実態を大和先生に聞く！ラストを公開しました。長かった大和先生に対するインタビューもこれでラスト！ 大和先生による業界に優秀な人間を引き込むための秘策とは。お楽しみ下さい。
> https://t.co/6GkC6f4yFb  
▶

　ノースライムというTwitterアカウントは北周士弁護士のことです。文春砲デビューとありますが、その文春の記事を私は、宇出津図書館で読みました。宇出津図書館では週刊新潮と週刊文春が毎週号おいてあるのですが、図書館へは月に1,2回か、数カ月行かなかったことも多いです。

　週刊文春の佐藤大和弁護士の記事ですが、だいたいの内容はネットの情報として見かけていたのでとりわけ印象に残ることもなかったのですが、同時に取り上げられた記者の方が気になりました。その記事の内容より、その情報がテレビでもネットでは全く見かけるものではなかったからです。

　図書館から戻った後も、その記者の件に関しては情報を全く見かけていません。戻ってからネットで調べようとも考えていたのですが、家に帰った頃にはすっかり忘れていたように思います。佐藤大和弁護士の話題と混在したような記事であったのも印象的で、似たものは他に見たことがありません。

　文春の記者が意図的にそうしたとも考えられます。ちょっと調べてみたいと思います。

［link：］ 文春 紀州のドンファン 記者 - Google 検索 https://www.google.co.jp/search?biw=1774&bih=912&ei=3qWxW_qYBILmwQPAhInIBA&q=%E6%96%87%E6%98%A5+%E7%B4%80%E5%B7%9E%E3%81%AE%E3%83%89%E3%83%B3%E3%83%95%E3%82%A1%E3%83%B3+%E8%A8%98%E8%80%85&oq=%E6%96%87%E6%98%A5+%E7%B4%80%E5%B7%9E%E3%81%AE%E3%83%89%E3%83%B3%E3%83%95%E3%82%A1%E3%83%B3+&gs_l=psy-ab.1.0.35i39k1j0i30k1j0i8i30k1l2.15503.15970.0.25573.2.2.0.0.0.0.134.238.0j2.2.0....0...1c.1.64.psy-ab..0.1.134....0.U6XYqT5GQhg

▶ ツイート％fukazawas（深澤諭史）％2018/10/01 12:51％ https://twitter.com/fukazawas/status/1046608565157294080
&twitter(1046608565157294080){theme:light}
> https://t.co/aPGMW0WDnD
> 相談者のことだけを考えれば、「そのような事実がある可能性は、極めて低い。一方で、疾病により、そのような認識を抱くに至った可能性は、より高い。したがって、まずは法律家の助言より、医師の… https://t.co/MCO0a17SXo  
▶

　気になる深澤諭史弁護士のツイートを見つけました。その前に深澤諭史弁護士のリツイートとしての中村元弥弁護士のツイートも気になるものです。

▶ ツイート％1961kumachin（中村元弥）％2018/10/01 12:38％ https://twitter.com/1961kumachin/status/1046605254366654465
&twitter(1046605254366654465){theme:light}
> ねえよ https://t.co/hhDY5ZwBMF  
▶

▶ ツイート％uwaaaa（サイ太）％2018/10/01 11:39％ https://twitter.com/uwaaaa/status/1046590324150231041
&twitter(1046590324150231041){theme:light}
> 収益性がないことばかりやっている人間に対しては，「他にクッソ効率のいい収益源があるんだろうな」と思ってます。  
▶

```
事件が暗礁に乗り上げる中、ドン・ファンを巡る魑魅魍魎たちの人間模様が徐々に浮き彫りになってきている。『週刊文春』2018年6月28日号は、“ドン・ファン妻（22）を操る「イケメン」弁護士と「タカリ」記者”と題した記事を掲載。記事では、“世紀の出鱈目本”を世に送り出した黒幕が克明に描かれている。「FRIDAYの契約記者・吉田隆氏ですよ。吉田氏は（野崎氏が被害に遭った）6000万円の窃盗事件の取材を通じて野崎氏と知り合い、徐々に擦り寄っていくのです。

［source：］みんなが寝静まった頃に　目的は只の金儲け！ “紀州のドン・ファン”事件に群がる守銭奴たち http://tskeightkun.blog.fc2.com/blog-entry-5477.html
```

　ようやくそれらしい情報を見つけました。上記に引用をしましたが、「『週刊文春』2018年6月28日号は、“ドン・ファン妻（22）を操る「イケメン」弁護士と「タカリ」記者”と題した記事を掲載。」とあります。こんなタイトルだったのかと、少し驚いたのですが間違いはなさそうです。

　記事の内容が混在していたのか、それとも同時二本立ての記事で、そういう印象を与えるものだったのかと考えていたのですが、記事のタイトルそのものが２つで１つだったようです。

　同姓同名も多そうな吉田隆という人物ですが、「吉田隆　記者」と検索しても情報は多くはなく、関心が低い感じです。植村隆と名前が似ていますが、数日前に「週刊金曜日」という雑誌の編集長か何かになったという情報を見かけました。裁判で有名になっていた人物でもあります。

```
真実 私は「捏造記者」ではない 単行本（ソフトカバー） – 2016/2/27
植村 隆 (著)

［source：］真実 私は「捏造記者」ではない | 植村 隆 |本 | 通販 | Amazon https://www.amazon.co.jp/%E7%9C%9F%E5%AE%9F-%E7%A7%81%E3%81%AF%E3%80%8C%E6%8D%8F%E9%80%A0%E8%A8%98%E8%80%85%E3%80%8D%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84-%E6%A4%8D%E6%9D%91-%E9%9A%86/dp/4000610945
```

```
商品の説明
内容紹介
1991年に元慰安婦について書いた1本の記事が、23年後に元記者の人生を狂わせた。活字メディア・電話・ネットなどでの抗議・嫌がらせ・脅迫は家族・職場の大学にまで及び、元記者は闘うことを決意した。そしていまや司法、活字メディアへと抵抗のうねりは広がっている。元記者の名誉回復だけでなく、日本の民主主義の再生を求めて。

［source：］真実 私は「捏造記者」ではない | 植村 隆 |本 | 通販 | Amazon https://www.amazon.co.jp/%E7%9C%9F%E5%AE%9F-%E7%A7%81%E3%81%AF%E3%80%8C%E6%8D%8F%E9%80%A0%E8%A8%98%E8%80%85%E3%80%8D%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84-%E6%A4%8D%E6%9D%91-%E9%9A%86/dp/4000610945
```

```
総合週刊誌「週刊金曜日」発行人と同誌を発行する株式会社金曜日（東京）の社長に就任した元朝日新聞記者で、韓国カトリック大学客員教授の植村隆氏（６０）が２８日、東京都内で記者会見した。植村氏は「リベラルなジャーナリズムの灯火を消してはならないという思いから引き受けた。憲法を守る、『週刊金曜日』を守る、というのが私の新たなスローガン」などと抱負を述べた。韓国の大学教員は兼務するという。

　平成５年創刊の「週刊金曜日」は定期購読部数が当初の５万部から１万３０００部程度にまで落ち込んでいるといい、経営環境は厳しい。植村氏に社長就任を依頼した北村肇前社長は理由について「権力の監視・批判をする、タブーを排して事実のみを伝えるという原点に立ち返って反転攻勢するのにふさわしいリーダーだ」と説明した。

［source：］「週刊金曜日」新社長・植村隆氏「リベラルなジャーナリズムの灯火を消してはならない」（1/2ページ） - 産経ニュース https://www.sankei.com/life/news/180928/lif1809280034-n1.html
```

　「2018.9.28 16:53」が記事の配信時刻のようです。編集長ではなく新社長となっていました。週刊金曜日という雑誌のことはネットで話題になっていたことで存在だけは知っていましたが、平成5年創刊というのは驚きです。私が存在を知ったのは10年も経っていないかもしれません。

　植村隆氏の娘が脅迫を受けたというような裁判のことは、桶川ストーカー殺人事件と同じ頃に記事を読んでいたという印象が残っています。桶川ストーカー殺人事件については、事件の発生自体は、調べたところ私の服役中か拘置所にいたときのことでした。平成11年の事件です。

　桶川ストーカー殺人事件といえば、同じく記者というかジャーナリストという清水潔氏ですが、ストーカー事件に対する関心が強かっただけに、疑問もいろいろある関心の強い事件です。父娘関係という点でも考えさせられる事件です。

　佐藤大和弁護士も出来過ぎの善人というか、そのまんま漫画の主人公のようなイメージがあります。現実の問題として考えると、どうなのかと疑問に考えることも多々あったのですが、今日のバイキングの放送の量刑予想も、設問の捉え方から疑問のある回答でした。

[link:] » 佐藤大和 - Twitter検索 https://t.co/mewnoThBmR

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:09／2018-09-21 13:03 URL： https://twitter.com/kk_hirono/status/1046643214042583040 https://twitter.com/yamato_lawyer/status/1042987729556930561
&twitter(1046643214042583040){theme:light}
> 件の芸人さんの件、10数年前のことを持ち出し、記事にする。しかも見出しには悪意しかない。十分に名誉毀損にもなりうる記事。もちろん週刊誌にも問題があるが、そういった記事を掲載し拡散するYahooなどのニュースサイトにも大きな問題がある。むしろ週刊誌以上に影響がある分、悪質といえる。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜tamura_hayato（田村勇人） 日時：2018-10-01 15:10／2018-09-30 21:00 URL： https://twitter.com/kk_hirono/status/1046643390534713344 https://twitter.com/tamura_hayato/status/1046369251945144320
&twitter(1046643390534713344){theme:light}
> 弁護士よもや話動画です。 \n  佐藤大和君とのお見合い希望者の釣書はフラクタル法律事務所まで！ \n  https://t.co/GKHXYmy84Z
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜DAISEN84863970（DAISEN） 日時：2018-10-01 15:10／2018-10-01 12:45 URL： https://twitter.com/kk_hirono/status/1046643438035169280 https://twitter.com/DAISEN84863970/status/1046606998773493760
&twitter(1046643438035169280){theme:light}
> 何もなかったかのように佐藤大和弁護士を出演させるバイキングって暴走してんのか計算づくの炎上演出なのかしらないが坂上忍と番組制作サイドとレイ法律事務所の蜜月さだけは気持ち悪いくらい見え見えだ \n  北村弁護士もグッディ出るようになっておかしくなったな。 \n   \n  #坂上忍 \n  #バイキング
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜_tubuan_（つぶあん/恋花🚫⚠🎤  ✒📖） 日時：2018-10-01 15:10／2018-10-01 12:08 URL： https://twitter.com/kk_hirono/status/1046643483539267584 https://twitter.com/_tubuan_/status/1046597578660315136
&twitter(1046643483539267584){theme:light}
> バイキングに出てる刑の重さについて語ってる人の佐藤大和さん(？)の声がめっちゃかっこいい 私が好きな声😳
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:10／2018-09-29 16:35 URL： https://twitter.com/kk_hirono/status/1046643536135770112 https://twitter.com/yamato_lawyer/status/1045940181700730880
&twitter(1046643536135770112){theme:light}
> 所属弁護士の独立移籍の際、法律事務所がその弁護士に対して、事務所に縛りつけようとしたり、独立移籍後をけん制しようとするために、懲戒請求をちらつかせるケースをたまに聞くことがあるが、そんなことはあってはならないし、そんな事務所があるなら弁護士に対する業務妨害として問題視すべき。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜1041112（ムックリン） 日時：2018-10-01 15:11／2018-10-01 13:00 URL： https://twitter.com/kk_hirono/status/1046643627126976513 https://twitter.com/1041112/status/1046610759336132609
&twitter(1046643627126976513){theme:light}
> 塚原のパワハラどうした？しれっと出演してる塚原の担当弁護士佐藤大和 #バイキング
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜01248888rena（レナ 🐰） 日時：2018-10-01 15:11／2018-10-01 12:15 URL： https://twitter.com/kk_hirono/status/1046643656440963072 https://twitter.com/01248888rena/status/1046599363256958976
&twitter(1046643656440963072){theme:light}
> 佐藤大和弁護士かっこよすぎん？
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ymEso34K67U6dZp（みなこ） 日時：2018-10-01 15:11／2018-10-01 07:55 URL： https://twitter.com/kk_hirono/status/1046643726175490050 https://twitter.com/ymEso34K67U6dZp/status/1046534103741345793
&twitter(1046643726175490050){theme:light}
> @yamato_lawyer 佐藤弁護士、参加されるんですか？(*^▽^*) \n  佐藤弁護士目当てでいっぱい来ますよΣ（ﾟдﾟlll）
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜reiko_chatbot（レイ子-レイ法律事務所の看板娘よ） 日時：2018-10-01 15:11／2018-09-30 14:13 URL： https://twitter.com/kk_hirono/status/1046643791296249857 https://twitter.com/reiko_chatbot/status/1046266887997276162
&twitter(1046643791296249857){theme:light}
> 【出演情報】 \n  フジテレビ「バイキング」月曜レギュラー出演中！ \n  10月1日（月）も、 \n  レイ法律事務所代表弁護士・佐藤大和が、フジテレビ「バイキング」に出演いたします。 \n   \n  ※番組の内容と放送時間は変更になる可能性があります。 \n  また、番… https://t.co/6x5qP6WudF
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:12／2018-09-29 00:31 URL： https://twitter.com/kk_hirono/status/1046643907532967936 https://twitter.com/yamato_lawyer/status/1045697482187915266
&twitter(1046643907532967936){theme:light}
> いくら芸能人でも6000万はないでしょう。自分の今までのメディア対応の経験上、法曹関係者と記載するとき、弁護士ではない（苦笑）。Yahooはほんと記事を掲載するときは一度内容を確認したほうがいい。被害者２人に示談金ＭＡＸ６０００万… https://t.co/pD44hkRWqg
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:12／2018-09-28 08:40 URL： https://twitter.com/kk_hirono/status/1046644004404703232 https://twitter.com/yamato_lawyer/status/1045458275745980416
&twitter(1046644004404703232){theme:light}
> 本日はドラマ監修の現場。法廷シーンの撮影のため、俳優さんたちやスタッフさんたちに現場指導。かなり面白いドラマなので、放送が本当に楽しみ。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜DAISEN84863970（DAISEN） 日時：2018-10-01 15:13／2018-09-24 13:03 URL： https://twitter.com/kk_hirono/status/1046644274626842624 https://twitter.com/DAISEN84863970/status/1044074725951983616
&twitter(1046644274626842624){theme:light}
> 佐藤大和弁護士 \n  体操パワハラ問題がまだ解決もしていないバイキングは動画の謝罪もしていない中で \n  どの面下げてテレビ出てんのかと嫌悪感しかない \n  性悪MCと性悪弁護士のお昼の番組ってあり得ないわフジも近い将来 \n  新潮45みたいになるんだろ… https://t.co/WRW9ECbzBK
◁◁◁

　上記のTwitterの検索で、佐藤大和弁護士が体操の塚原氏の代理人をしているような情報を見かけましたが、これは全くの初耳です。二転三転しながら最終的に塚原氏側が辞任をさせられたというようなところで、テレビの報道は見ていないように思います。

　塚原という名前は、他に聞いたこともなく記憶に残っていたのですが、オリンピックの月面宙返りの人と最初に知ったときは驚きました。調べて確認はしていないですが、小学生の頃であったように思います。コマネチ選手より前だったと思いますが、テレビで何度も繰り返し見かけていました。

```
2018年09月10日 09時58分	アサ芸プラス


「体操協会パワハラ問題」で脚光を浴びる塚原夫妻の代理人弁護士の正体！

　いっこうに収束する気配がない体操協会のパワハラ問題。当事者である塚原夫妻の代理人弁護士に就いているのが「バイキング」（フジテレビ系）のコメンテーターとして出演している佐藤大和弁護士だ。9月3日の放送に出演した佐藤弁護士は、前週に生出演した宮川紗江選手のコメントと合わせながら、塚原夫妻の謝罪文を解説。これに対して、タレントで政治評論家の東国原英夫が持論を展開した。

［source：］体操協会パワハラ問題　塚原夫妻の代理人弁護士は『バイキング』出演の佐藤大和弁護士｜ニフティニュース https://news.nifty.com/article/sports/athletic/12104-111872/
```

　9月10日の時点で、このようなニュースが出ていたようですが、これは知りませんでした。佐藤大和弁護士のツイートでは、別の件で、バイキングに対する不満や不公正さを指摘していたように思います。人生経験も豊富そうな塚原夫妻が、佐藤大和弁護士を頼りに任せていたというのは意外でした。

[link:] » "バイキング" from:yamato_lawyer - Twitter検索 https://t.co/JIzVD46u5V

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:36／2018-09-24 14:41 URL： https://twitter.com/kk_hirono/status/1046650017157591041 https://twitter.com/yamato_lawyer/status/1044099477810761728
&twitter(1046650017157591041){theme:light}
> 本日のバイキング出演。弁護士バッチを忘れ、一旦事務所に戻ったが、今度はネクタイを忘れるという・・・（苦笑）。いまはドラマ監修の現場へ。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:36／2018-08-20 09:57 URL： https://twitter.com/kk_hirono/status/1046650110044585984 https://twitter.com/yamato_lawyer/status/1031344395923013633
&twitter(1046650110044585984){theme:light}
> 先週火曜日、すぐに私もTwitterで否定したが、改めて本日のバイキングで否定する予定。それにしてもこの記事を見る限り、しっかりと裏取りもせず、自分たちで誤情報を勝手に流しておいて、自分たちで否定するという・・・。本当にこちらに迷… https://t.co/XFB4t9ZPLl
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:36／2018-08-14 14:13 URL： https://twitter.com/kk_hirono/status/1046650151182290945 https://twitter.com/yamato_lawyer/status/1029234608401862657
&twitter(1046650151182290945){theme:light}
> 事実と異なることを放送するとは・・。それも放送前にバイキング側に伝えていたにもかかわらず、放送するのは本当にありえない。自分が出演している番組だからといって、この件をうやむやにするつもりはない。代理人としてしっかりとバイキング側にクレームをいれ、場合によっては相応の対応をする予定
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:37／2018-08-14 14:09 URL： https://twitter.com/kk_hirono/status/1046650176398450690 https://twitter.com/yamato_lawyer/status/1029233612950974464
&twitter(1046650176398450690){theme:light}
> 先ほど「バイキング」で「紀州のドン・ファン」と言われている件を放送し、家政婦さんのインタビューで「奥さんは（パスポートを）返してもらってない」とあったが、パスポートは警察に渡しておらず当初から本人の手元にある。バイキング側には放送前に伝えており、間違っているのに放送をしている。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:37／2018-08-10 21:45 URL： https://twitter.com/kk_hirono/status/1046650219465650176 https://twitter.com/yamato_lawyer/status/1027898776931815424
&twitter(1046650219465650176){theme:light}
> 「バイキング」の徳原先生と。何だか二人ともチャラいですね（苦笑）。コメンテーター弁護士同士の写真。 https://t.co/6rQRBmfh9e
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-01 15:37／2018-06-16 12:03 URL： https://twitter.com/kk_hirono/status/1046650300981899264 https://twitter.com/yamato_lawyer/status/1007820891479142400
&twitter(1046650300981899264){theme:light}
> 昨日、バイキングに出演した際の、出演者全員が「妻が怪しい」という前提での異常なコメントと雰囲気。もちろん過剰に妻側に立ってほしいということはないが、バランスを失っており、インタビューにない事実を断定的に話をしたり、またCM中に代理… https://t.co/scjYPfHNaM
◁◁◁

　Twitterの検索でも、今日のバイキングで富田林警察署の逃走犯の量刑のコメントに触れたものは見当たらず、それ自体は珍しくなかったのですが、逃走前の事件のことはよく知らないなどと前置きをしながら、佐藤大和弁護士は、加重逃走罪の法定刑を踏まえ、懲役5年以上とコメントしていました。

　逃走前に逮捕されていた事件には、強制性交罪が含まれており、これは凶悪犯の逃走として繰り返し報道され周知化されていたかと思います。以前の強姦罪でも上限は有期懲役で、平成4年の時点でも懲役20年となっていました。その後、刑法の改正で有期懲役刑の上限は更に引き上げられているはずです。

　強姦罪の加減もだいぶん前に2年から3年に引き上げられていたかと思いますが、量刑の相場自体がずいぶんと重くなったと聞いておりますし、常習的な複数の同種事件では懲役20年を超える判決もいくつかニュースとして見てきました。テレビではなくネットのニュースがほとんどかもしれません。

```
⑴　強制性交等罪（改正刑法１７７条）
①　構成要件及び法定刑
１３歳以上の者に対し、暴行又は脅迫を用いて性交、肛門性交又は口腔性交（以下「性交等」という。）をした者は、強制性交等の罪とし、５年以上の有期懲役に処する。１３歳未満の者に対し、性交等をした者も、同様とする。

［source：］強制性交等罪とは？強姦罪はどのように改正されたか？わかりやすく解説 | 弁護士法人泉総合法律事務所 https://izumi-keiji.jp/column/seihanzai/kyosei-kaisei
```

　刑法の177条という条文は変わっていないように思いますが、下限が懲役5年以上となっていることに驚きました。この法改正はテレビでも解説付きで報道されていましたが、強制性交罪の下限が5年になっていたとは今日まで気がつかなかったように思います。

　この性犯罪の厳罰化については、3,4日前になりますか、伊藤和子弁護士が関与していたと知り、エントリーとして取り上げていますが、まだ手付かずです。「2018-09-29-183626_性犯罪厳罰化法案と伊藤和子弁護士.org」というファイルとして作成しています。

　少し調べたところ、逃走で逮捕された被疑者は、窃盗や強制性交罪で起訴されていたようです。起訴されたのか確認していないですが、パトカーへの放火容疑の事件というのも報道にはありました。非現住建造物への放火でも量刑はかなり重いはずです。

　番組では逃走中の犯罪を含めた刑罰の量刑を問われていましたが、併合罪ということになれば、それだけでも量刑の上限が1.5倍になるはずなのに、それをうかがわせる佐藤大和弁護士の説明というのは感じられず、上限が懲役5年という加重逃走罪を基礎にしているような印象を受けました。

```
併合罪の法定刑の計算方法
併合罪の法定刑は刑の長期を罪が重い方の刑期×1.5とすると定められています。(刑法第47条)

例えば、刑の長期が懲役20年の罪と懲役15年の罪を１度に犯した場合、併合後の長期は【20×1.5=30年】です。ちなみに、併合罪により長期が伸びる場合は30年が上限であり、併合対象となる罪の法定刑が死刑・無期懲役は特に法定刑の修正はありません。

ちなみに、この場合の長期とは「長い期間」という辞書的な意味ではありません。『懲役〇〇年以上●●年以下』という場合の●●年の方を、長期といいます。

［source：］併合罪とは｜観念的競合・牽連犯との違いや量刑の計算方法などを解説｜刑事事件弁護士ナビ https://keiji-pro.com/columns/196/
```

　有期刑の上限について調べていたところ、驚きの情報を発見しました。2011年12月6日の記事となっていますが、判決が静岡地裁沼津支部で出たのは、前日の5日のようです。

```
そこで、裁判長は、２００９年３月以前の７件の罪について懲役２４年（求刑懲役３０年）を、以後の６件の罪について懲役２６年（求刑懲役３０年）をそれぞれ言い渡した結果、求刑６０年に対して懲役５０年となりました。

　現在の無期懲役刑は終身刑ではありませんので、一生刑務所に入っているということはなく、２０年前後刑務所にいると仮出獄が認められます。強盗致傷罪は５年以上無期懲役が法定刑ですが、検察が無期懲役を求刑しなかったことで、かえって無期懲役より長い懲役になったともいえるでしょう。

　判決で裁判長は「女性の人格を無視し凶暴極まりない。確定裁判の前後を通じて重大犯罪を繰り返した経過、事件の態様などから再犯の可能性は否定できず、徹底した矯正が望まれることを考慮すると、いずれの事件群も懲役２０年を下回るべきではない」と述べたということです。

［source：］日本の裁判所で性犯罪について求刑６０年に対して懲役５０年の判決下る http://blogos.com/article/26236/
```

　犯行の悪質さが重視されたようですが、日本で懲役50年という判決が出ていたとは、今日まで全く知りませんでした。諸外国では200年、300年というものを見かけてきましたが、日本では30年を超える懲役刑も見たことがなかったような気もします。

　間に確定判決をはさんでいたため、別の裁判として併合審理を受けたため、懲役24年と懲役26年という２つの判決が出て、合計で懲役50年となったということです。否認に対する検事の嫌がらせとして3刑持ちにされたという話は、その本人から福井刑務所で話を聞いたことがありました

　昨日か一昨日、弁護士のツイートとしては珍しく、上告審における未決通算を話題にしたものがありました。それも亀石倫子弁護士のGPS裁判、最高裁判決に関するものでした。弁護士の主張通り違法という判断が出たものの、有罪という結果も量刑も変わらなかったということです。

　弁護士の主張通り違法と認定されれば、法定通算となり、上告審での勾留期間は全て参入されるようなツイートもありました。検察の上告が棄却されたような場合は、そうなるという話は聞いていましたが、判決確定前の勾留は、仮釈放の対象とはならないはずなので被告人の不利益は小さくないと思います。

　実際に経験したことですが、同じ懲役4年の判決でも、上告審まで争い未決通算が少なかった場合と、すぐに判決を確定させて服役し、仮釈放をもらった場合では、実質的な拘束期間が半分ほどになるということがありました。前者は私自身で、後者は殺人罪でした。被害者の素行も悪く感謝されたそうです。

　佐藤大和弁護士の量刑予想は、懲役5年以上とずいぶん幅を持たせたものでしたが、意図的に軽く思わせたり、刑事弁護に過大な期待を世間にアピールしたようにも思えてなりません。優しい感じの語り口でもありましたが、世間の反感を被疑者に向けさせるのも現実的な効果と思えてならないです。

　もとよりこの富田林警察署の逃走事件は、接見の弁護士が取った行動も大きく寄与しているのですが、多くの弁護士らは、それをさらに警察の落ち度、失態の上積みとして世間にアピールした感があります。その辺りから距離をおいているようにも見えましたが、同じ弁護士という問題性は皆無に感じました。

　佐藤大和弁護士のツイートの投稿数は多くないので、8月12日頃のツイートであれば、比較的容易に遡れるかと思います。Twilogの登録があれば、もっと簡単に住むのですが、とりあえず、逃走事件発生直後の佐藤大和弁護士のツイートを捜してみたいと思います。



* 浜松市の看護師女性連れ去り殺害事件


