#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "テレビの政権批判のコメントで業務妨害され警察に通報した、という亀石倫子弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-09-18 09:11:49 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  亀石倫子弁護士 秋重実弁護士 通報 政権批判 テレビ出演

[:contents]

* 流れ

** ツイート

*** 秋重実弁護士（京都弁護士会）の「気味の悪い世の中になってきた」というツイートでの引用
    :LOGBOOK:
    CLOCK: [2018-09-18 火 09:26]--[2018-09-18 火 10:29] =>  1:03
    :END:

▶ ツイート％akishigemakoto（弁護士秋重実）％2018/09/17 21:34％ https://twitter.com/akishigemakoto/status/1041666793444524035  
<blockquote class="twitter-tweet" lang="ja"><p>気味の悪い世の中になってきた https://t.co/eUIvlT6Lk4</p>&mdash; akishigemakoto（弁護士秋重実}）<a href="https://twitter.com/akishigemakoto/status/1041666793444524035">2018/09/17 21:34</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
気味の悪い世の中になってきた https://t.co/eUIvlT6Lk4  
▶

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 09:28／2018-09-18 09:11 URL： https://twitter.com/kk_hirono/status/1041846280392073216 https://twitter.com/s_hirono/status/1041842056572760064</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041846280392073216){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041842056572760064<a href="https://twitter.com/s_hirono/status/1041842056572760064"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-084815_弁護士秋重実（@akishigemakoto）：気味の悪い世の中になってきた.jpg https://t.co/asYpBYM8Yu
▷▷▷

　秋重実弁護士のTwitterタイムラインは、Firefoxのブラウザでだいぶん前から開いたままにしていました。そのようにタブを開きすぎることが多く、時々整理で閉じているのですが、なにか思うところがあって秋重実弁護士のページのタブは開いたままにしていました。

*** ツイートと、そのツイートに対する反応

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2018-09-18 10:15／2018-09-17 21:29 URL： https://twitter.com/kk_hirono/status/1041858245445410816 https://twitter.com/MichikoKameishi/status/1041665493415780352</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858245445410816){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/MichikoKameishi/status/1041665493415780352<a href="https://twitter.com/MichikoKameishi/status/1041665493415780352"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> テレビで政権に批判的なコメントしたら、ものすごく叩かれて、事務所に業務を妨害するほどの電話かけてくる人もいて、警察に通報した。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2018-09-18 10:15／2018-09-17 21:36 URL： https://twitter.com/kk_hirono/status/1041858284284592129 https://twitter.com/MichikoKameishi/status/1041667240939016192</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858284284592129){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/MichikoKameishi/status/1041667240939016192<a href="https://twitter.com/MichikoKameishi/status/1041667240939016192"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> ほんとうに悲しい。 \n  誰が好き好んで名前晒して顔晒して自分の意見を言って、ここまで叩かれたいと思う？ \n  なにも言わなければこんな目に遭わない。 \n  誰もがそう思うだろう。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sidehand21（藤井洋平） 日時：2018-09-18 10:15／2018-09-17 22:50 URL： https://twitter.com/kk_hirono/status/1041858306808016896 https://twitter.com/sidehand21/status/1041685798175694850</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858306808016896){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/sidehand21/status/1041685798175694850<a href="https://twitter.com/sidehand21/status/1041685798175694850"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 番組見てました。 \n  亀石さんの発言に、アナウンサーが焦って話題を変えようとしていたのが印象的でした。 \n   \n  亀石さんの発言は確か日本の報道の自由度についての言及だったと記憶しております。 \n  （間違っていた… https://t.co/SqpcO7GmKp
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2018-09-18 10:15／2018-09-17 23:41 URL： https://twitter.com/kk_hirono/status/1041858329167839232 https://twitter.com/MichikoKameishi/status/1041698630300655617</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858329167839232){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/MichikoKameishi/status/1041698630300655617<a href="https://twitter.com/MichikoKameishi/status/1041698630300655617"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @sidehand21 あ、それではなくて、別の番組でプーチン発言への日本政府の対応についてしたコメントです💦
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sidehand21（藤井洋平） 日時：2018-09-18 10:16／2018-09-17 23:57 URL： https://twitter.com/kk_hirono/status/1041858347022966784 https://twitter.com/sidehand21/status/1041702603229261826</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858347022966784){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/sidehand21/status/1041702603229261826<a href="https://twitter.com/sidehand21/status/1041702603229261826"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi コメントありがとうございます！ \n  いずれにしても、最近はマスコミですら本来の社会的使命を無視して、政権批判をしないのに、ご自身の意見をしっかり発言されたのは立派だと思います！ツイートも含めとても共感しました！
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜libertan（六十路の手習い） 日時：2018-09-18 10:16／2018-09-17 23:28 URL： https://twitter.com/kk_hirono/status/1041858379025547264 https://twitter.com/libertan/status/1041695433565691905</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858379025547264){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/libertan/status/1041695433565691905<a href="https://twitter.com/libertan/status/1041695433565691905"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 先日、西宮まで亀石さん講演聞きに行ったものです。応援してます。頑張ってください。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2018-09-18 10:16／2018-09-17 23:44 URL： https://twitter.com/kk_hirono/status/1041858399225274369 https://twitter.com/MichikoKameishi/status/1041699422214615040</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858399225274369){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/MichikoKameishi/status/1041699422214615040<a href="https://twitter.com/MichikoKameishi/status/1041699422214615040"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @libertan 西宮の講演会、お越しいただきましてありがとうございました🙇‍♀️ \n  励まされます。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ohgachan（おおがっちゃん） 日時：2018-09-18 10:16／2018-09-18 08:18 URL： https://twitter.com/kk_hirono/status/1041858415339814917 https://twitter.com/ohgachan/status/1041828669109325824</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858415339814917){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/ohgachan/status/1041828669109325824<a href="https://twitter.com/ohgachan/status/1041828669109325824"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 暴力的な言動には毅然として対処することをお勧めします。大阪弁護士会には弁護士業務妨害対策委員会のようなものはあるのでしょうか。相手は確信犯でしょうから、一人で立ち向かうよりも、そうしたプロフェッショナル集団の力を借りた方が効果的かと。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2018-09-18 10:16／2018-09-18 08:20 URL： https://twitter.com/kk_hirono/status/1041858439041843200 https://twitter.com/MichikoKameishi/status/1041829247814316032</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858439041843200){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/MichikoKameishi/status/1041829247814316032<a href="https://twitter.com/MichikoKameishi/status/1041829247814316032"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @ohgachan ありがとうございます、そうします🙇‍♀️
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ohgachan（おおがっちゃん） 日時：2018-09-18 10:16／2018-09-18 08:24 URL： https://twitter.com/kk_hirono/status/1041858456041316352 https://twitter.com/ohgachan/status/1041830297753419776</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858456041316352){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/ohgachan/status/1041830297753419776<a href="https://twitter.com/ohgachan/status/1041830297753419776"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 札幌弁護士会の弁護士業務妨害対策委員会は、民暴委員会と共通メンバーで、会員弁護士に対する業務妨害や様々な嫌がらせ、名誉毀損行為、ストーカー行為などにも機敏に対処してくれます。会員向けに業務妨害対策マニュアルも発行しています。以上ご参考まで。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takitaro2（滝本太郎） 日時：2018-09-18 10:16／2018-09-17 23:00 URL： https://twitter.com/kk_hirono/status/1041858478568955904 https://twitter.com/takitaro2/status/1041688289961365504</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858478568955904){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/takitaro2/status/1041688289961365504<a href="https://twitter.com/takitaro2/status/1041688289961365504"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 重点警備、携帯の所在確認了解し、各番号110番特例を \n  また下記を習い性に。 \n  ・ホーム先頭に立たない \n  ・下り階段では手すり \n  ・自宅・事務所は常に鍵 \n  ・出るときは、必ず周囲を見てから \n  ・写真の残るイン… https://t.co/qA30ksZCUV
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜14jcruyff（o.murase） 日時：2018-09-18 10:16／2018-09-17 23:28 URL： https://twitter.com/kk_hirono/status/1041858542624366592 https://twitter.com/14jcruyff/status/1041695427156881409</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858542624366592){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/14jcruyff/status/1041695427156881409<a href="https://twitter.com/14jcruyff/status/1041695427156881409"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @takitaro2 @MichikoKameishi テレビで、安倍批判したら、こんな警戒をしなければならないなんて、本当に異常。圧倒的優位にあるのに、敵対するものを、ひたすら居丈高に攻撃し悦に浸ってる、今の政権の姿勢が、そうさせてる気がします。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜grom_raider（中年係長📢反TPP❕反高プロ⚡⚡） 日時：2018-09-18 10:16／2018-09-17 22:20 URL： https://twitter.com/kk_hirono/status/1041858563772239873 https://twitter.com/grom_raider/status/1041678230845939713</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858563772239873){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/grom_raider/status/1041678230845939713<a href="https://twitter.com/grom_raider/status/1041678230845939713"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 番組を拝見しておりました。久しぶりにテレビで真っ当な政権批判を聞けて、清々しい気持ちでおりました。 \n   \n  何も出来ませんが、応援しております。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KSN1HybmjjiCMoQ（けん） 日時：2018-09-18 10:17／2018-09-17 23:40 URL： https://twitter.com/kk_hirono/status/1041858609984888833 https://twitter.com/KSN1HybmjjiCMoQ/status/1041698349022273537</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858609984888833){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/KSN1HybmjjiCMoQ/status/1041698349022273537<a href="https://twitter.com/KSN1HybmjjiCMoQ/status/1041698349022273537"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi サンモニとかでしょ？ \n  相手憎しで言ってるわけじゃなく、 \n  事実を歪曲して言ってるわけじゃなく、 \n  ただ、事実を淡々と話すだけで、バッシング。 \n  これこそ、今の日本の現状を物語ってますよね。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜metakotokittan（めた山（人と違うことしてたい病）） 日時：2018-09-18 10:17／2018-09-17 22:22 URL： https://twitter.com/kk_hirono/status/1041858653739864064 https://twitter.com/metakotokittan/status/1041678779045695488</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858653739864064){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/metakotokittan/status/1041678779045695488<a href="https://twitter.com/metakotokittan/status/1041678779045695488"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 現政権を指示してる人達の中に、業務妨害などの違法行為を肯定するような人々が沢山いるってことですね。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜14jcruyff（o.murase） 日時：2018-09-18 10:17／2018-09-17 21:49 URL： https://twitter.com/kk_hirono/status/1041858674816208896 https://twitter.com/14jcruyff/status/1041670564279017472</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858674816208896){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/14jcruyff/status/1041670564279017472<a href="https://twitter.com/14jcruyff/status/1041670564279017472"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @sousuke_c なんだか、本当に嫌な風潮ですね。負けないでください。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jadetigers（四十郎） 日時：2018-09-18 10:17／2018-09-17 21:33 URL： https://twitter.com/kk_hirono/status/1041858700242124802 https://twitter.com/jadetigers/status/1041666329588060160</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858700242124802){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/jadetigers/status/1041666329588060160<a href="https://twitter.com/jadetigers/status/1041666329588060160"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 全く無力ですが応援しています
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜CMyaro（春夏秋冬） 日時：2018-09-18 10:17／2018-09-17 22:09 URL： https://twitter.com/kk_hirono/status/1041858722622889984 https://twitter.com/CMyaro/status/1041675581966831616</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858722622889984){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/CMyaro/status/1041675581966831616<a href="https://twitter.com/CMyaro/status/1041675581966831616"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi これはもう暴力の域です。許せるものではない。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜9wb9xr（中河 謙二） 日時：2018-09-18 10:17／2018-09-17 22:01 URL： https://twitter.com/kk_hirono/status/1041858742503976960 https://twitter.com/9wb9xr/status/1041673581619552260</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858742503976960){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/9wb9xr/status/1041673581619552260<a href="https://twitter.com/9wb9xr/status/1041673581619552260"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 負けないで‼ \n   \n  応援している方々も､沢山いますから｡
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜cwineyou（モスリン） 日時：2018-09-18 10:17／2018-09-17 23:15 URL： https://twitter.com/kk_hirono/status/1041858762720477185 https://twitter.com/cwineyou/status/1041692162562220032</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858762720477185){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/cwineyou/status/1041692162562220032<a href="https://twitter.com/cwineyou/status/1041692162562220032"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 本当に恐ろしい世の中になりましたね。 \n  圧力で押さえつけられて、まっとうなことが言えない世の中で生きたくはありません。 \n  どうか負けないでください😢💦
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yukimuratechno（テクノカット（木村裕樹）） 日時：2018-09-18 10:17／2018-09-17 21:39 URL： https://twitter.com/kk_hirono/status/1041858812028669952 https://twitter.com/yukimuratechno/status/1041668010405060608</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858812028669952){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/yukimuratechno/status/1041668010405060608<a href="https://twitter.com/yukimuratechno/status/1041668010405060608"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 偽計業務妨害みたいなやつになるかもしれませんね。電話かけ続けた方は、手段をわきまえなかったことを反省するため、拘置所で一休みになりますね。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜gegegenobacabon（バカボン） 日時：2018-09-18 10:18／2018-09-17 23:00 URL： https://twitter.com/kk_hirono/status/1041858846942089217 https://twitter.com/gegegenobacabon/status/1041688251843502082</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858846942089217){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/gegegenobacabon/status/1041688251843502082<a href="https://twitter.com/gegegenobacabon/status/1041688251843502082"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 常識が通用しないのですから通報は当然です。今日の報道ステーションは素晴らしかったですよ。正しいことを言うのは良識あれば当然のことです。それをテレビで見たのは久しぶりのことでホッとしました。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fKf7E5yFYV1jYU0（まさくん😃☺森加計、赤坂自民亭） 日時：2018-09-18 10:18／2018-09-17 23:29 URL： https://twitter.com/kk_hirono/status/1041858882484633600 https://twitter.com/fKf7E5yFYV1jYU0/status/1041695553933852672</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858882484633600){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/fKf7E5yFYV1jYU0/status/1041695553933852672<a href="https://twitter.com/fKf7E5yFYV1jYU0/status/1041695553933852672"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @mcenroeisgod 私も応援します。久々のまっとうな政権批判良かったです。報道自由度ランキングは確かに旧民主党政権よりかなり下がっています。官邸がテレビに対して圧力と恫喝をして黙らせようと… https://t.co/AjLU3SXWma
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okiraku31moji（sato rie31moji） 日時：2018-09-18 10:18／2018-09-17 22:14 URL： https://twitter.com/kk_hirono/status/1041858923999809537 https://twitter.com/okiraku31moji/status/1041676741700272128</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041858923999809537){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/okiraku31moji/status/1041676741700272128<a href="https://twitter.com/okiraku31moji/status/1041676741700272128"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi それが悪いことなのだということを分かっていないのでしょう。子どもならともかく、きっと皆年齢では大人のでしょうから、悪いことにはきちんと責任を取らねばならないと気づいてもらいましょうね。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nashihima（THE UNFORGIVEN） 日時：2018-09-18 10:19／2018-09-17 23:03 URL： https://twitter.com/kk_hirono/status/1041859128505786374 https://twitter.com/nashihima/status/1041689161697116160</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859128505786374){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/nashihima/status/1041689161697116160<a href="https://twitter.com/nashihima/status/1041689161697116160"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 応援してます！ツイッターの連中は気軽にブロックまたはミュートしてはいかがでしょうか。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜paruchang777（ぱるちゃん） 日時：2018-09-18 10:19／2018-09-18 02:29 URL： https://twitter.com/kk_hirono/status/1041859177751007233 https://twitter.com/paruchang777/status/1041740964253990912</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859177751007233){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/paruchang777/status/1041740964253990912<a href="https://twitter.com/paruchang777/status/1041740964253990912"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @yamamototaro0 出るか出らんかは本人の自由。 \n  自分の意見が全て正しいと思ってるからこーゆー事言えるんぢゃね？ \n  正しいと思う人もおるし反対意見あるの当たり前。 \n  まぁ、事務所にまで電話するやり過ぎの人の気持ちはわからんけど。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜allnight（AllNight） 日時：2018-09-18 10:19／2018-09-18 00:28 URL： https://twitter.com/kk_hirono/status/1041859211196424192 https://twitter.com/allnight/status/1041710495131004930</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859211196424192){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/allnight/status/1041710495131004930<a href="https://twitter.com/allnight/status/1041710495131004930"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi あのコメントはとても分かりやすく共感しました。 \n  叩かれたり業務妨害されたり大変だとは思いますが、くじけずに頑張ってください！ \n  くじけるような人じゃないですよねｗｗ \n  応援しています！！
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Vll61Tx（SW学徒・福祉ギルド） 日時：2018-09-18 10:19／2018-09-17 21:54 URL： https://twitter.com/kk_hirono/status/1041859281610567680 https://twitter.com/Vll61Tx/status/1041671669176131584</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859281610567680){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/Vll61Tx/status/1041671669176131584<a href="https://twitter.com/Vll61Tx/status/1041671669176131584"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi あのホテル不倫ヒゲ弁護士なら、抗議する価値ありますが、亀石さんに関しては、営業妨害・人権侵害ですよ。 \n  もし亀石さんと意見を異にしても
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bfcd35d874514c7（ま～くん。） 日時：2018-09-18 10:19／2018-09-18 03:24 URL： https://twitter.com/kk_hirono/status/1041859327068319745 https://twitter.com/bfcd35d874514c7/status/1041754794044485637</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859327068319745){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/bfcd35d874514c7/status/1041754794044485637<a href="https://twitter.com/bfcd35d874514c7/status/1041754794044485637"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 私、学生時代、東京新聞を取ってました(笑) \n   \n  正義は勝つ、とはよぉ言いませんが \n  私は亀石さんの主張が好きです。 \n  そして現官房長官、好きではありません。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜NxItachan（「野党結集」政権奪取❗️） 日時：2018-09-18 10:20／2018-09-18 06:36 URL： https://twitter.com/kk_hirono/status/1041859368302469120 https://twitter.com/NxItachan/status/1041803201559724032</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859368302469120){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/NxItachan/status/1041803201559724032<a href="https://twitter.com/NxItachan/status/1041803201559724032"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @aizawaaki 亀井倫子さん、負けるな❗️少なくとも、ここに一人、いや多くの心ある人が応援しています。とてつもなく危うい空気が蔓延していますね。どうして私達日本人はこうも軽薄なんでしょうね。… https://t.co/lkEzsUTdNo
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜twibuzzbot（ツイバズ） 日時：2018-09-18 10:20／2018-09-18 04:50 URL： https://twitter.com/kk_hirono/status/1041859406575497217 https://twitter.com/twibuzzbot/status/1041776320508649474</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859406575497217){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/twibuzzbot/status/1041776320508649474<a href="https://twitter.com/twibuzzbot/status/1041776320508649474"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 弁護士 亀石倫子(@MichikoKameishi)さん \n   \n  現在RTの勢い日本で \n  🏅第5位🏅です \n  1131.6RT/時速 (4時台) \n   \n  テレビで政権に批判的なコメントしたら、ものすごく叩かれて、事務所に業務を妨害するほどの電話 \n  .… https://t.co/lNdrXssyCx
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sonoda_hisashi（園田寿） 日時：2018-09-18 10:20／2018-09-18 01:09 URL： https://twitter.com/kk_hirono/status/1041859516470448129 https://twitter.com/sonoda_hisashi/status/1041720706138947584</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859516470448129){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/sonoda_hisashi/status/1041720706138947584<a href="https://twitter.com/sonoda_hisashi/status/1041720706138947584"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 私も同じような経験がありますが、くれぐれもお気をつけ下さい。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Hiromiasou（麻生博美） 日時：2018-09-18 10:20／2018-09-17 23:11 URL： https://twitter.com/kk_hirono/status/1041859583302434816 https://twitter.com/Hiromiasou/status/1041691033933770752</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859583302434816){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/Hiromiasou/status/1041691033933770752<a href="https://twitter.com/Hiromiasou/status/1041691033933770752"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @yamamototaro0 こんばんは。ほんとにひどいですね。安倍政権を批判することはまっとうなことですよね。正しい事を言って何故叩かれるのかと。これ程までに酷い事をしている政府を批判しない方がどうかしてると思う。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jo_ta_haha（さんむうん） 日時：2018-09-18 10:21／2018-09-17 22:56 URL： https://twitter.com/kk_hirono/status/1041859625337769984 https://twitter.com/jo_ta_haha/status/1041687400680837120</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859625337769984){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/jo_ta_haha/status/1041687400680837120<a href="https://twitter.com/jo_ta_haha/status/1041687400680837120"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 応援しています \n  言論の自由が抑圧されるようでは民主主義は終わる \n  そんなことにならないように、社会が守らなくてはなりません
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜AR4bvoZqxuzrwZF（山崎） 日時：2018-09-18 10:21／2018-09-17 22:48 URL： https://twitter.com/kk_hirono/status/1041859692866068480 https://twitter.com/AR4bvoZqxuzrwZF/status/1041685310776651778</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859692866068480){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/AR4bvoZqxuzrwZF/status/1041685310776651778<a href="https://twitter.com/AR4bvoZqxuzrwZF/status/1041685310776651778"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @qp0305 ぜひ負けないでください。おかしな人間は必ずいます。 \n  なにせ現首相も議員時代の時に、選挙妨害でヤクザ雇っていたぐらいですので。相手もあなたの発言を恐れているということです。山本太郎や森ゆう子のようになってください。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜gotoopp（しんさく） 日時：2018-09-18 10:21／2018-09-17 23:01 URL： https://twitter.com/kk_hirono/status/1041859732573544449 https://twitter.com/gotoopp/status/1041688680438456320</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859732573544449){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/gotoopp/status/1041688680438456320<a href="https://twitter.com/gotoopp/status/1041688680438456320"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 放送観てました。私たちの声を代弁してくれてありがとうございました。本当に酷いですね。亀石さんのように勇気を持って発言できる方を尊敬します。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜pa_chan_mama（ぱぁちゃんママ） 日時：2018-09-18 10:21／2018-09-17 22:51 URL： https://twitter.com/kk_hirono/status/1041859757298962432 https://twitter.com/pa_chan_mama/status/1041686042141585409</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859757298962432){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/pa_chan_mama/status/1041686042141585409<a href="https://twitter.com/pa_chan_mama/status/1041686042141585409"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 応援しています。 \n  日本の法曹界、民主主義の為に頑張って下さい。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜2015_0919_0218（kmokmos） 日時：2018-09-18 10:21／2018-09-18 09:02 URL： https://twitter.com/kk_hirono/status/1041859797753057280 https://twitter.com/2015_0919_0218/status/1041839749613281280</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859797753057280){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/2015_0919_0218/status/1041839749613281280<a href="https://twitter.com/2015_0919_0218/status/1041839749613281280"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 嫌がらせに負けないで頑張ってくださいね！ \n  亀石さん、みんな応援してますよ！みんなが味方です！ \n  亀石さんがメディアで色んな発言してくれてることで、どれだけ国民が救われてるか！これからもこんなことに負… https://t.co/9IQ4vnsSxC
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜shozocb750（しょうちゃん） 日時：2018-09-18 10:21／2018-09-17 23:13 URL： https://twitter.com/kk_hirono/status/1041859823405416449 https://twitter.com/shozocb750/status/1041691566060892161</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859823405416449){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/shozocb750/status/1041691566060892161<a href="https://twitter.com/shozocb750/status/1041691566060892161"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi やっぱ世の中がおかしくなってますよね！？ \n  安倍支持者こそが憲法違反してるんですよ！
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mado_news（松井玲奈＠沖縄県知事選挙） 日時：2018-09-18 10:22／2018-09-18 01:16 URL： https://twitter.com/kk_hirono/status/1041859859073777665 https://twitter.com/mado_news/status/1041722667525562369</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859859073777665){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/mado_news/status/1041722667525562369<a href="https://twitter.com/mado_news/status/1041722667525562369"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 今の現職の総理大臣が『暴力団に選挙妨害を依頼した人』がですから、政権に批判的なコメントに反応して事務所に電話かけてくる人も、政権の手先かもしれません。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜osamum2012（Swim57 立憲パートナーズ、脱原発、遺伝子組換えでない） 日時：2018-09-18 10:22／2018-09-18 00:08 URL： https://twitter.com/kk_hirono/status/1041859898793910273 https://twitter.com/osamum2012/status/1041705434665480192</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859898793910273){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/osamum2012/status/1041705434665480192<a href="https://twitter.com/osamum2012/status/1041705434665480192"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi 番組を見ていました \n  国民として国の行く末を案じての発言でした \n  それに嫌がらせとは本当にとは下劣です \n   \n  タトゥー裁判、頑張ってください！ \n  今週、娘が傍聴に行きます
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Szk330Hiro（hirotch） 日時：2018-09-18 10:22／2018-09-17 23:20 URL： https://twitter.com/kk_hirono/status/1041859941370191872 https://twitter.com/Szk330Hiro/status/1041693270269550592</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859941370191872){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/Szk330Hiro/status/1041693270269550592<a href="https://twitter.com/Szk330Hiro/status/1041693270269550592"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @yamamototaro0 人違いだったらごめんなさい。サンデーモーニングでお話しされていた弁護士さんですよね。 \n  応援している人もたくさんいます。頑張って下さい！
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜minami_aoyama（南青山（「沈黙はファシズムの承認」）） 日時：2018-09-18 10:22／2018-09-18 00:06 URL： https://twitter.com/kk_hirono/status/1041859998404313088 https://twitter.com/minami_aoyama/status/1041704972214165504</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041859998404313088){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/minami_aoyama/status/1041704972214165504<a href="https://twitter.com/minami_aoyama/status/1041704972214165504"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @Hideo_Ogura そういうことを、おカネをもらって専門にやっているグループがあるんでしょうね。政権側は税金を使い放題だからどうとでもなるのでしょう。
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yuumari65（yuumari） 日時：2018-09-18 10:23／2018-09-18 09:58 URL： https://twitter.com/kk_hirono/status/1041860270937669632 https://twitter.com/yuumari65/status/1041854060742172672</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041860270937669632){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/yuumari65/status/1041854060742172672<a href="https://twitter.com/yuumari65/status/1041854060742172672"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @jkHWFmhgUCLhsjT サンデーモーニングは最後の砦とも思えるまっとうな番組。スポーツタイムがちょっと長いけど。コメンテーターもごくまっとうな人が多い。亀石さんも、安田なつきさんもいつも… https://t.co/mDfcp85jvd
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜LOAaCeAPJ8gqmb0（ゆう） 日時：2018-09-18 10:24／2018-09-18 08:25 URL： https://twitter.com/kk_hirono/status/1041860410188550144 https://twitter.com/LOAaCeAPJ8gqmb0/status/1041830413889437696</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041860410188550144){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/LOAaCeAPJ8gqmb0/status/1041830413889437696<a href="https://twitter.com/LOAaCeAPJ8gqmb0/status/1041830413889437696"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi う～ん🤔 \n  ここまでなら共感😄 \n  この後の💬は蛇足😅 \n   \n  私は己を晒して発言できないチキンなので🐓 \n  自分を晒して考えを公にする方に敬意があります \n   \n  名前を晒して意見を言うなら厳しい意見を飲み込む強いハー… https://t.co/zniIXirSw4
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KomaEpic（koma） 日時：2018-09-18 10:24／2018-09-17 23:24 URL： https://twitter.com/kk_hirono/status/1041860515855618049 https://twitter.com/KomaEpic/status/1041694439968841728</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041860515855618049){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/KomaEpic/status/1041694439968841728<a href="https://twitter.com/KomaEpic/status/1041694439968841728"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> @MichikoKameishi @sidehand21 安部政権の言論弾圧凄いですね。嫌がらせをしてくるということは確信をついた批判ができている証拠でもあります。亀石先生を応援しているので言論弾圧に負けずに戦ってほしいです。
▷▷▷

* 同業弁護士らの反応

** こたんせ

*** 「恨み買う商売ですからね。秋田県の弁護士はなんで殺害されたの？」というツイートの発見
    :LOGBOOK:
    CLOCK: [2018-09-18 火 16:50]--[2018-09-18 火 17:38] =>  0:48
    :END:

▶ ツイート％kotadon（こたぴょん）％2018/09/18 12:35％ https://twitter.com/kotadon/status/1041893446007447552  
<blockquote class="twitter-tweet" lang="ja"><p>極めて危険な内容なので報告しておきました。 https://t.co/sFl4Tfw0iq</p>&mdash; kotadon（こたぴょん}）<a href="https://twitter.com/kotadon/status/1041893446007447552">2018/09/18 12:35</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
極めて危険な内容なので報告しておきました。 https://t.co/sFl4Tfw0iq  
▶

　ぱっとみて気になる内容のツイートでしたが、それが亀石倫子弁護士のツイートにつながるものとは思いもよりませんでした。

　こたんせ、のTwitterタイムラインはFirefoxのタブでページを開いたままにしていたように思いますが、タブをクリックした時点でページの再読込があったのか、いつの間にかプロフィールの内容が変更になっていました。

<blockquote>
こたぴょん
@kotadon
27歳ゆるふわOLに憧れる，かつて天使のような笑顔だと親戚から言われていた30代の何かの専門家。 文字だけでの飯テロをやることもあります。思い出したように #こたレシピ というハッシュタグでレシピを書き出したりします。

どこかにあるユートピア
2010年2月に登録
<span style="color: #01DFA5; font-size: 12px;">［source：］ こたぴょん(@kotadon)さん | Twitterからの返信付きツイート <a href="https://twitter.com/kotadon/with_replies">https://twitter.com/kotadon/with_replies</a></span>
</blockquote>

　今日は午前中からだったと思いますが、Emacs-LispでBloggerへの投稿処理のコードを編集していたのですが、思いの外、手間取り、本文の内容が置き換わるなどの経験のない大きなエラーが出ていました。関数を変えることで対処が出来ましたが、原因を探すだけでも時間がかかりました。

　次が、変更した処理で投稿したBloggerの記事になります。タイトル名を「ファイル名（拡張子除く）：レベル１の見出し／レベル２の見出し／レベル３の見出し」としました。「パンくずリスト」のような表記としています。

- 2018年09月16日10時54分の登録： *** 2018年9月15日のTwitterタイムライン http://hirono2017kk.blogspot.com/2018/09/2018915twitter.html
- 2018年09月16日17時07分の登録： *** 2018年9月14日のTwitterタイムライン http://hirono2017kk.blogspot.com/2018/09/2018914twitter.html
- 2018年09月16日19時10分の登録： *** 落合洋司弁護士のブログの引用からの経緯で見つけたアクセスランキング1位のニュース記事 http://hirono2017kk.blogspot.com/2018/09/1.html
- 2018年09月17日21時44分の登録： *** 深澤諭史弁護士のタイムライン、リツイートとしての発見 http://hirono2017kk.blogspot.com/2018/09/blog-post_12.html
- 2018年09月18日06時53分の登録： *** 深澤諭史弁護士のタイムライン、リツイートとしての発見 http://hirono2017kk.blogspot.com/2018/09/blog-post_39.html
- 2018年09月18日10時29分の登録： *** 秋重実弁護士（京都弁護士会）の「気味の悪い世の中になってきた」というツイートでの引用 http://hirono2017kk.blogspot.com/2018/09/blog-post_3.html
- 2018年09月18日16時45分の登録： テレビの政権批判のコメントで業務妨害され警察に通報した、という亀石倫子弁護士のツイート：流れ／ツイート／ツイートと、そのツイートに対する反応 http://hirono2017kk.blogspot.com/2018/09/blog-post_5.html
- 2018年09月18日16時48分の登録： テレビの政権批判のコメントで業務妨害され警察に通報した、という亀石倫子弁護士のツイート：流れ／ツイート／秋重実弁護士（京都弁護士会）の「気味の悪い世の中になってきた」というツイートでの引用 http://hirono2017kk.blogspot.com/2018/09/blog-post_31.html

　ファイル名や見出しの付け方は、まだまだ改善の必要がありますが、使い込むことで慣れていきたいと考えています。こういうのもだいぶん前から考えにあったのですが、面倒もあってなかなか実行に移すことができず、ようやく取り掛かると、予想外に手間取りました。

　昨日から昨夜になると思いますが、Bloggerの記事の方でも、seesaaWiki用のコードを変換する処理を加え、通常のhtmlとして埋め込みツイートと引用のhtmlタグを反映させるようにしました。seesaaWikiの記法をhtmlのコードに変換するというフィルター処理です。

　seesaaWikiの記法をメインに使うようになったのは、今月に入ってからだと思います。それ以前は、GitHubで扱いやすいMarkdownの記法を使っていました。編集のエディタのEmacsでは、seesaaWikiの記法に似ているorg-modeをメジャーモードにしました。

　Bloggerの記事のタイトル名の書式変換は、亀石倫子弁護士のエントリーの作成を中断して作業を進めていました。そして、ようやく出来たというタイミングで、こたんせのツイートから再び亀石倫子弁護士のツイートに巡り合ったのは、不思議な発見のタイミングでした。



** スクリーンショットとしての記録作成措置

*** こたんせ、北周士弁護士、過食弁護士、佐藤正子弁護士

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 16:37 URL： https://twitter.com/kk_hirono/status/1041981687838560256 https://twitter.com/s_hirono/status/1041954325931552768</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981687838560256){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041954325931552768<a href="https://twitter.com/s_hirono/status/1041954325931552768"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-161807_　こたぴょん@kotadon27歳ゆるふわOLに憧れる，かつて天使のような笑顔だと親戚から言われていた30代の何かの専門家。　文字だけでの飯.jpg https://t.co/McP191AyJX
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 16:37 URL： https://twitter.com/kk_hirono/status/1041981709502181376 https://twitter.com/s_hirono/status/1041954357464330240</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981709502181376){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041954357464330240<a href="https://twitter.com/s_hirono/status/1041954357464330240"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-162605_こたぴょん（@kotadon）：「無償の愛」＝「多額の現金」ですね！.jpg https://t.co/2I1dFHV7GN
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 16:37 URL： https://twitter.com/kk_hirono/status/1041981730544996352 https://twitter.com/s_hirono/status/1041954388565053440</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981730544996352){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041954388565053440<a href="https://twitter.com/s_hirono/status/1041954388565053440"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-162709_こたぴょん（@kotadon）：あれ？きたんせに報告したっけ？いや，そもそも結婚したっけ？.jpg https://t.co/YvgWSGe4OA
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 16:37 URL： https://twitter.com/kk_hirono/status/1041981753030660096 https://twitter.com/s_hirono/status/1041954420416602112</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981753030660096){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041954420416602112<a href="https://twitter.com/s_hirono/status/1041954420416602112"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-163519_こたぴょんのリツイート（弁護士亀石倫子　@MichikoKameishi）：ありがとうございます😭以前ブロックしたら、「表現の自由を奪うな.jpg https://t.co/d1D8EFMn1x
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 16:37 URL： https://twitter.com/kk_hirono/status/1041981781782626304 https://twitter.com/s_hirono/status/1041954451756437504</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981781782626304){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041954451756437504<a href="https://twitter.com/s_hirono/status/1041954451756437504"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-163603_こたぴょん（@kotadon）：極めて危険な内容なので報告しておきました。.jpg https://t.co/WDgeo0sS8m
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 16:38 URL： https://twitter.com/kk_hirono/status/1041981811637678081 https://twitter.com/s_hirono/status/1041954483201236992</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981811637678081){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041954483201236992<a href="https://twitter.com/s_hirono/status/1041954483201236992"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-163654_佐藤正子（@SATOMasako）：報告しといた。.jpg https://t.co/dlnlRPwI1n
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981846639104001 https://twitter.com/s_hirono/status/1041973748667015170</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981846639104001){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041973748667015170<a href="https://twitter.com/s_hirono/status/1041973748667015170"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-164248_過食弁護士（@juntaba1）：なにこれ？わざわざ殺された秋田の何の関係もない先生の話を引っ張って来るってことは、お前恨み買って死ぬぞっ.jpg https://t.co/kCBAHqmQzS
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981870131400704 https://twitter.com/s_hirono/status/1041973780841619457</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981870131400704){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041973780841619457<a href="https://twitter.com/s_hirono/status/1041973780841619457"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-175028_ノースライム（@noooooooorth）：別に電撃的に報告してくれても構わんのやで。.jpg https://t.co/r4nhk78JKk
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:26／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981889429372928 https://twitter.com/s_hirono/status/1041973812382785536</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981889429372928){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041973812382785536<a href="https://twitter.com/s_hirono/status/1041973812382785536"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-175059_ノースライム（@noooooooorth）：他の業界のことはよくわからないが、ウチの業界には若者（特に修習生）に奢りたがっている人がやたら.jpg https://t.co/rnMowqxncX
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:27／2018-09-18 17:54 URL： https://twitter.com/kk_hirono/status/1041981908941275137 https://twitter.com/s_hirono/status/1041973843961602049</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981908941275137){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041973843961602049<a href="https://twitter.com/s_hirono/status/1041973843961602049"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-175141_ノースライム（@noooooooorth）：メインはルーアン鴨。まずソースと付け合せの野菜たちが美味しい。肉はものすごくしっかりとした肉質.jpg https://t.co/lnPYcIvgIs
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:27／2018-09-18 17:55 URL： https://twitter.com/kk_hirono/status/1041981933318631424 https://twitter.com/s_hirono/status/1041973875091824646</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981933318631424){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041973875091824646<a href="https://twitter.com/s_hirono/status/1041973875091824646"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-175230_ノースライムのリツイート（弁護士亀石倫子　@MichikoKameishi）：テレビで政権に批判的なコメントしたら、ものすごく叩かれて、事.jpg https://t.co/6OiEtTEnAb
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-18 18:27／2018-09-18 17:55 URL： https://twitter.com/kk_hirono/status/1041981956785721344 https://twitter.com/s_hirono/status/1041973906326708224</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041981956785721344){theme:light}　</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041973906326708224<a href="https://twitter.com/s_hirono/status/1041973906326708224"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-18-175318_ノースライム（@noooooooorth）：文春砲デビューの実態を大和先生に聞く！⑥を公開しました。今回は弁護士が主体的にメディアをコント.jpg https://t.co/TnYYqY6LFY
▷▷▷

▶ ツイート％yjochi（落合洋司 Yoji Ochiai 🇯🇵）％2018/09/23 23:08％ https://twitter.com/yjochi/status/1043864572153581568
[https://twitter.com/yjochi/status/1043864572153581568:embed]
あべちゃんに固執して新たな流れが作れないままの自民党。来年の参議院選、その先の衆議院選まで、支持を引き延ばせるかだな。自分は、草葉の陰から見守っている。笑  
▶

▶ ツイート％yjochi（落合洋司 Yoji Ochiai 🇯🇵）％2018/09/23 17:10％ https://twitter.com/yjochi/status/1043774666299469829
[https://twitter.com/yjochi/status/1043774666299469829:embed]
石破氏は、閣外にいることで、国内外から、次の首相有力という目でますます見られ、存在感が増すだろう。こういう時は、重要閣僚で処遇するとか、封じ込めて虎を野に放たないようにすべきところだが、それができないレームダック内閣だわな。  
▶





