#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料・情報"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-10-18 10:04:01 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  岡口基一裁判官の分限裁判

#contents

* 岡口基一裁判官の分限裁判

** 戒告処分の決定

*** テレビの報道、今のところ録画した「日テレNEWS２４」のみの確認
    :LOGBOOK:
    CLOCK: [2018-10-18 木 10:12]--[2018-10-18 木 11:54] =>  1:42
    :END:

　今のところ録画していた「日テレNEWS２４」のみでの確認ですが、これは前回の分限裁判後の記者会見の時と同じかと思います。今回ほど他の番組をチェックすることはなかったと思いますが、Twitterの検索でもその他というのは関西テレビだかの１局だけだったようです。

　今回の放送は前回より短く簡潔でした。記者会見の写真か映像も出ていましたが、同席した弁護士というのも左右に一人で、岡口基一裁判官を含め３人だけという会館でした。Twitterで見かけた情報によると、裁判所の中で午後８時か９時に会見が開かれたようです。異例ともありました。

　次がテレビの画面撮影になります。非常上告-最高検察庁御中_ツイッター（@s_hirono）の画像つきツイートです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 10:40／2018-10-18 10:37 URL： https://twitter.com/kk_hirono/status/1052736137083609088 https://twitter.com/s_hirono/status/1052735488686096384
&twitter(1052736137083609088){theme:light}
> 2018-10-18_072714＿テレビの画面・日テレNEWS２４・ツイッターに不適切投稿　岡口裁判官を最高裁が戒告処分　岡口基一裁判官.jpg https://t.co/wPm63cmuw2
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 10:40／2018-10-18 10:37 URL： https://twitter.com/kk_hirono/status/1052736156633161728 https://twitter.com/s_hirono/status/1052735453516857344
&twitter(1052736156633161728){theme:light}
> 2018-10-18_072703＿テレビの画面・日テレNEWS２４・ツイッターに不適切投稿　岡口裁判官を最高裁が戒告処分　岡口基一裁判官.jpg https://t.co/nRnHHJO2Z5
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 10:40／2018-10-18 10:37 URL： https://twitter.com/kk_hirono/status/1052736179907387393 https://twitter.com/s_hirono/status/1052735422076411904
&twitter(1052736179907387393){theme:light}
> 2018-10-18_072654＿テレビの画面・日テレNEWS２４・ツイッターに不適切投稿　岡口裁判官を最高裁が戒告処分　岡口基一裁判官.jpg https://t.co/dVSzhmYQc8
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 10:40／2018-10-18 10:37 URL： https://twitter.com/kk_hirono/status/1052736203651407872 https://twitter.com/s_hirono/status/1052735390044450817
&twitter(1052736203651407872){theme:light}
> 2018-10-18_072642＿テレビの画面・日テレNEWS２４・ツイッターに不適切投稿　岡口裁判官を最高裁が戒告処分　岡口基一裁判官.jpg https://t.co/ev143BbIdC
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 10:40／2018-10-18 10:37 URL： https://twitter.com/kk_hirono/status/1052736222919974912 https://twitter.com/s_hirono/status/1052735358562009088
&twitter(1052736222919974912){theme:light}
> 2018-10-18_072621＿テレビの画面・日テレNEWS２４・ツイッターに不適切投稿　岡口裁判官を最高裁が戒告処分　岡口基一裁判官.jpg https://t.co/l7L2BMqlIE
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 10:40／2018-10-18 10:37 URL： https://twitter.com/kk_hirono/status/1052736242549309445 https://twitter.com/s_hirono/status/1052735326718844928
&twitter(1052736242549309445){theme:light}
> 2018-10-18_072600＿テレビの画面・日テレNEWS２４・ツイッターに不適切投稿　岡口裁判官を最高裁が戒告処分　岡口基一裁判官.jpg https://t.co/dHiVBnifhb
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 10:40／2018-10-18 10:37 URL： https://twitter.com/kk_hirono/status/1052736265903206401 https://twitter.com/s_hirono/status/1052735294653386752
&twitter(1052736265903206401){theme:light}
> 2018-10-18_072543＿テレビの画面・日テレNEWS２４・ツイッターに不適切投稿　岡口裁判官を最高裁が戒告処分　岡口基一裁判官.jpg https://t.co/LG0P2nSc8V
◁◁◁
----

　他の方法でも調べてみます。

[link:] » 岡口　裁判官　テレビ - Twitter検索 https://t.co/zPfukGl6T1

----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yuria2122（株式情報市場） 日時：2018-10-18 10:54／2018-10-18 09:08 URL： https://twitter.com/kk_hirono/status/1052739765450158081 https://twitter.com/yuria2122/status/1052712869773463552
&twitter(1052739765450158081){theme:light}
> 岡口裁判官に戒告　不適切なＳＮＳ 最高裁：ニュースモーニングサテライト：テレビ東京 https://t.co/3d7Pwsg9ka
◁◁◁
----
[link:] » 岡口裁判官に戒告　不適切なＳＮＳ 最高裁：ニュースモーニングサテライト：テレビ東京 https://t.co/NvIVTC5H1v

----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜risa_mama117（rima） 日時：2018-10-18 10:55／2018-09-10 23:10 URL： https://twitter.com/kk_hirono/status/1052740041124937728 https://twitter.com/risa_mama117/status/1039154145058410497
&twitter(1052740041124937728){theme:light}
> 関テレ:裁判官がSNS発信で懲戒？最高裁大法廷が判断へ…岡口基一判事「裁判を受ける国民の皆さんにとって悲劇」https://t.co/LMazJmUypo「裁判官を懲戒すべきかどうかが審理される「分限裁判」。 \n  その当事者となってい… https://t.co/T6zuPR8xGC
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜166mochizuki（望月宣武Hiromu MOCHIZUKI） 日時：2018-10-18 10:56／2018-06-13 16:08 URL： https://twitter.com/kk_hirono/status/1052740167864221697 https://twitter.com/166mochizuki/status/1006795451096535040
&twitter(1052740167864221697){theme:light}
> @okaguchik 下記ニュースを「下着のまま」と空目して貴職（岡口判事）のことと勘違いしてしまったことを心よりお詫び申し上げます。 \n   \n  ▼裁判官を懲戒請求　民事訴訟で「下書き」のまま判決言い渡す　岐阜地裁（CBCテレビ） - g… https://t.co/2yjr17ZbNH
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mstk_Horiguchi（天高くほりぐち肥ゆる秋） 日時：2018-10-18 10:56／2017-12-26 23:46 URL： https://twitter.com/kk_hirono/status/1052740182938607616 https://twitter.com/mstk_Horiguchi/status/945667141570670592
&twitter(1052740182938607616){theme:light}
> お　すごい　岡口裁判官　全国ニュース（日本テレビ系よみうりテレビ系　NEWS　ZERO）でツイートが取り上げられている。さすがですねぇ
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜egeLA5SLQPV55jo（不勉強⚒️💯🦄） 日時：2018-10-18 10:56／2016-10-01 11:22 URL： https://twitter.com/kk_hirono/status/1052740283807363073 https://twitter.com/egeLA5SLQPV55jo/status/782042947680243712
&twitter(1052740283807363073){theme:light}
> 岡口裁判官がまたテレビで取り上げられてる https://t.co/pmmXFSwg3y
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜BarlKarth（高島章（弁護士）） 日時：2018-10-18 10:57／2016-09-21 13:57 URL： https://twitter.com/kk_hirono/status/1052740343081271297 https://twitter.com/BarlKarth/status/778458117050728448
&twitter(1052740343081271297){theme:light}
> 当日の弁護団長（高島章）の服装ですが、秋でもありますので、普通のスーツにネクタイで出廷予定です。岡口さんはどうするかは聞いていません。 \n  岡口裁判官と当職がテレビに映る機会はめったにないでしょうから、当日のテレビニュースは、チェックしないといけません。
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KPtan2（NKPMとイッパイアッテナ） 日時：2018-10-18 10:57／2016-06-28 09:54 URL： https://twitter.com/kk_hirono/status/1052740479429668864 https://twitter.com/KPtan2/status/747594101424427008
&twitter(1052740479429668864){theme:light}
> 岡口裁判官の件、TVで報道されたのね。組織なのでいろいろあると思うけど、岡口さんのツイートをみて、親近感を抱いた人は多いんじゃないかな？しかも、かなり偉い人なんだよね。
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜pacitokun（井藤公量） 日時：2018-10-18 10:57／2016-06-28 09:11 URL： https://twitter.com/kk_hirono/status/1052740494394966016 https://twitter.com/pacitokun/status/747583098406076416
&twitter(1052740494394966016){theme:light}
> 岡口裁判官、テレビにも登場していたのか。 \n  https://t.co/VIWOufiEjj
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jyona_can（ジョナ） 日時：2018-10-18 10:57／2016-06-28 07:40 URL： https://twitter.com/kk_hirono/status/1052740541337632768 https://twitter.com/jyona_can/status/747560331862433792
&twitter(1052740541337632768){theme:light}
> めざましテレビで岡口基一裁判官の顔写真付き報道…
◁◁◁
----

　数年前になると思いますが、最初に白ブリーフや半裸写真などで岡口基一裁判官が厳重注意処分を受けたとき、とくダネなどのテレビの情報番組で取り上げられたことは、事後にネットの情報で知りましたが、私がテレビで見ることは一度もなかったと思います。複数の番組で取り上げられていたようでした。

　昨夜の夜７時からのNHKのNEWS７でも、短かったですが、少しだけ岡口基一裁判官の戒告処分をニュースとして取り上げていたように思います。他に情報を見ていないので、記憶に自信がないのですが、それもテレビの画面を撮影していたように思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 11:50／2018-10-18 11:48 URL： https://twitter.com/kk_hirono/status/1052753670029242368 https://twitter.com/s_hirono/status/1052753359671717888
&twitter(1052753670029242368){theme:light}
> 2018-10-17_192557＿テレビの画面・NEWS７・ツイッター裁判官戒告処分　”裁判官の品位おとしめた”　岡口基一裁判官.jpg https://t.co/UicLcVbDRq
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 11:50／2018-10-18 11:48 URL： https://twitter.com/kk_hirono/status/1052753687238520832 https://twitter.com/s_hirono/status/1052753327962742784
&twitter(1052753687238520832){theme:light}
> 2018-10-17_192545＿テレビの画面・NEWS７・ツイッター裁判官戒告処分　”裁判官の品位おとしめた”　岡口基一裁判官.jpg https://t.co/IWuqyvebbd
◁◁◁
----
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 11:50／2018-10-18 11:48 URL： https://twitter.com/kk_hirono/status/1052753706830061568 https://twitter.com/s_hirono/status/1052753295746318337
&twitter(1052753706830061568){theme:light}
> 2018-10-17_192536＿テレビの画面・NEWS７・ツイッター裁判官戒告処分　”裁判官の品位おとしめた”　岡口基一裁判官.jpg https://t.co/EANBd5Jbox
◁◁◁
----

　昨夜のNEWS９のニュースは見出しも大きくインパクトというか強調性のあるものだと思いました。映像か写真に伊藤和子弁護士が写り込んでいますが、これは前回の記者会見のときのものだと思われます。小倉秀夫弁護士も出ていた歴史的な映像の記録でした。

* 横浜地検　犯人隠避教唆容疑で弁護士ら逮捕

** バイキング（10月18日放送）

*** 予定の「▽弁護士がウソ供述させた疑い…同じ弁護士達の本心は？」、沢田研二の騒動で中止なのか？
    :LOGBOOK:
    CLOCK: [2018-10-18 木 12:20]--[2018-10-18 木 15:26] =>  3:06
    :END:

▶ ツイート％viking_fujitv（【フジテレビ公式】バイキング）％2018/10/18 03:03％ https://twitter.com/viking_fujitv/status/1052621024045363200
&twitter(1052621024045363200){theme:light}
> 10月18日(木)の #バイキング は…
> “ミスター慶應"出場イケメン大学生が性的暴行の疑いで逮捕！▽弁護士がウソ供述させた疑い…同じ弁護士達の本心は？▽高級住宅街“南青山”に児童相談所建設計画…住民説明会が紛糾！
> 11時55分から放送です♪
> #バイキングくん  
▶

　昨日になると思いますが、たぶん朝にTwitterでリストを作成しました。リストの機能自体、ここ数年間ほとんど使っていなかったのですが、事前にニュース・情報番組の放送内容をチェックしておきたいと考え作成したものです。

［link：］ @hirono_hideki/tvさんはTwitterを利用しています https://twitter.com/hirono_hideki/lists/tv

　時刻は14時31分になっています。昼食にスパゲッティを作り、洗い物をしているだけでもけっこう時間が掛かりました。スパゲティを作っている途中、テレビのバイキングで弁護士の犯人隠避教唆で逮捕という話題が予定通り始まりました。

　CM前に次の話題を紹介するというのもバイキングでよくあることですが、台所からかけつけスマホでテレビ画面の撮影ができてのは、そのCM後というタイミングでした。次が今日のバイキングの放送でのテレビ画面の写真撮影になります。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 14:38／2018-10-18 14:27 URL： https://twitter.com/kk_hirono/status/1052796130596085760 https://twitter.com/s_hirono/status/1052793154624086017
&twitter(1052796130596085760){theme:light}
> 2018-10-18_115515＿テレビの画面・バイキング・番組冒頭　今日のニュース　2項目.jpg https://t.co/8Bd6vIrize
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 14:38／2018-10-18 14:27 URL： https://twitter.com/kk_hirono/status/1052796146844721153 https://twitter.com/s_hirono/status/1052793186165252096
&twitter(1052796146844721153){theme:light}
> 2018-10-18_115537＿テレビの画面・バイキング・騒動　沢田研二（７０）コンサート　直前に中止　なぜ？ファン混乱　契約上の問題が発生.jpg https://t.co/RKBNSCnBDj
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 14:39／2018-10-18 14:27 URL： https://twitter.com/kk_hirono/status/1052796168999063552 https://twitter.com/s_hirono/status/1052793217412788224
&twitter(1052796168999063552){theme:light}
> 2018-10-18_122434＿テレビの画面・バイキング・争　港区・ブランド街　100億円の児童相談所　建設へ.jpg https://t.co/3xw9sD3iQS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 14:39／2018-10-18 14:27 URL： https://twitter.com/kk_hirono/status/1052796191526678528 https://twitter.com/s_hirono/status/1052793249671204864
&twitter(1052796191526678528){theme:light}
> 2018-10-18_124833＿テレビの画面・バイキング・テレビ番組出演の弁護士（３２）逮捕　無免許死亡事故で嘘の供述させたか？　江口大和弁護士.jpg https://t.co/dccA2cKB4w
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-18 14:39／2018-10-18 14:27 URL： https://twitter.com/kk_hirono/status/1052796212162658304 https://twitter.com/s_hirono/status/1052793282403549190
&twitter(1052796212162658304){theme:light}
> 2018-10-18_130652＿テレビの画面・バイキング・”ミスター慶応”出場者逮捕　19歳の女性に性的暴行容疑.jpg https://t.co/lFAvxEixTa
◁◁◁
<hr />

　5つ目の「2018-10-18_130652＿テレビの画面・バイキング・”ミスター慶応”出場者逮捕　19歳の女性に性的暴行容疑」は、ほぼ前の弁護士逮捕の話題が終わり切り替わったというタイミングでの撮影でした。だいたい12時48分から13時06分が弁護士逮捕の話題の時間でした。

　初めに中止なのかと思ったのは、バイキングの番組開始に決まって出てくる画面下のテロップに今日のニュースというのがあり、いつもは項目が3つだったのが、今日は２つだけで、その直後に今日に舞い込んだと思われる沢田研二のコンサート中止が、いきなり始まったからです。

　バイキングでは曜日ごとに違いもあるのかと思いますが、番組で今日のニュースの挨拶の後、細かい話題やニュースを多い時で５つほど取り上げ、そのあとで今日のニュースに移るパターンがよくあるように思います。けっこう変則的で流れがつかみにくくもあるのですが、そういうものだと思っていました。

　バイキングの今日のニュースについては、過去にいくつか記録したものがあると思います。社会的な影響の大きな番組と考え、弁護士の出演は業務の提携性が強いではと感じるところもあるので、注目とともに記憶違いなどないように正確な記録を心掛けています。

```
[10002]  % pp -l|grep 今日のニュース
2018-06-18_115530＿テレビの画面・バイキング・今日のニュース.jpg http://hirono2014sk.blogspot.com/2018/06/2018061913182018-06-180822562018-06.html#20180618115530
2018-06-19_115537＿テレビの画面・バイキング・今日のニュース.jpg http://hirono2014sk.blogspot.com/2018/06/2018062011352018-06-182108592018-06.html#20180619115537
2018-06-22_115513＿テレビの画面・バイキング・今日のニュース　独自　注目　予想.jpg http://hirono2014sk.blogspot.com/2018/06/2018062309152018-06-220812482018-06.html#20180622115513
2018-06-25_115512＿テレビの画面・バイキング・今日のニュース　疑惑　練炭自殺偽装　日大　危険タックル問題.jpg http://hirono2014sk.blogspot.com/2018/06/2018062611142018-06-250842012018-06.html#20180625115512
2018-06-28_115524＿テレビの画面・バイキング・今日のニュース　直撃　日大アメフト　謝罪　ゴルフ片山プロ　運命　サッカーW杯　決戦.jpg http://hirono2014sk.blogspot.com/2018/06/2018062817132018-06-261217012018-06.html#20180628115524
2018-07-03_115532＿テレビの画面・バイキング・今日のニュース　サッカーW杯惜敗　日大アメフト問題　隠ぺい工作の”黒幕”の正体は？.jpg http://hirono2014sk.blogspot.com/2018/07/2018070507552018-07-030532032018-07.html#20180703115532
2018-07-04_115515＿テレビの画面・バイキング・今日のニュース　”口封じ”X氏の影に迫る！　桂歌丸さん死去　梅宮アンナYouTube再活動.jpg http://hirono2014sk.blogspot.com/2018/07/2018070507552018-07-030532032018-07.html#20180704115515
2018-07-05_115521＿テレビの画面・バイキング・今日のニュース　いたずら１１９番暴言ネット配信男　「井上前コーチは被害者　辺見マリ”５億円借金”騒動.jpg http://hirono2014sk.blogspot.com/2018/07/2018070613212018-07-050749422018-07.html#20180705115521
2018-07-09_115526＿テレビの画面・バイキング・今日のニュース　新展開　日大田中理事長が危険タックル問題に言及　逮捕　文科省前局長が息子を「裏口入学」.jpg http://hirono2014sk.blogspot.com/2018/07/2018071116582018-07-081030472018-07.html#20180709115526
2018-07-12_115537＿テレビの画面・バイキング・今日のニュース　アニメ「おじゃる丸」　現役部員への独自取材　ルビー・モレノ.jpg http://hirono2014sk.blogspot.com/2018/07/2018071313282018-07-110801322018-07.html#20180712115537
2018-07-13_115522＿テレビの画面・バイキング・今日のニュース　豪雨迫る中　安倍首相ら懇親会　失職の熊本前市議服飾　平成を彩ったアスリート引退会見.jpg http://hirono2014sk.blogspot.com/2018/07/2018071411142018-07-131130392018-07.html#20180713115522
2018-07-16_115606＿テレビの画面・バイキング・今日のニュース　日大アメフト部チーム改善報告書　東京医科大学裏口入学リスト　熊本市魏失職取り消し.jpg http://hirono2014sk.blogspot.com/2018/07/2018072110492018-07-151105532018-07.html#20180716115606
2018-07-17_115511＿テレビの画面・バイキング・今日のニュース　日大ついに回答期限　医師装う婚活サギ師　財閥会長へのセクハラ強要.jpg http://hirono2014sk.blogspot.com/2018/07/2018072110492018-07-151105532018-07.html#20180717115511
2018-07-19_115534＿テレビの画面・バイキング・今日のニュース　肺がん３度見落とし女性死亡　日大アメフト新監督人事　石原裕次郎の遺品保管場所.jpg http://hirono2014sk.blogspot.com/2018/07/2018072110492018-07-151105532018-07.html#20180719115534
2018-07-20_115515＿テレビの画面・バイキング・今日のニュース　「妻を実家に埋めた」夫と母親　日大アメフト部新監督選考委員　赤坂自民亭SNS投稿写真に批判.jpg http://hirono2014sk.blogspot.com/2018/07/2018072110492018-07-151105532018-07.html#20180720115515
2018-07-24_115523＿テレビの画面・バイキング・今日のニュース　関東学連に猛抗議　元総長が語る日大の実情と今後　”コンクリ詰め遺体”.jpg http://hirono2014sk.blogspot.com/2018/07/2018073013362018-07-230746252018-07.html#20180724115523
2018-07-24_115533＿テレビの画面・バイキング・今日のニュース　関東学連に猛抗議　元総長が語る日大の実情と今後　”コンクリ詰め遺体”.jpg http://hirono2014sk.blogspot.com/2018/07/2018073013362018-07-230746252018-07.html#20180724115533
2018-07-25_115527＿テレビの画面・バイキング・今日のニュース　関東学連が改善報告書を　阿波おどり「総おどり」中止　ストーカー男元恋人宅放火.jpg http://hirono2014sk.blogspot.com/2018/07/2018073013362018-07-230746252018-07.html#20180725115527
2018-07-26_115520＿テレビの画面・バイキング・今日のニュース　鈴鹿市死体遺棄事件　日大アメフト異議申し立て？　剛力彩芽インスタ再開.jpg http://hirono2014sk.blogspot.com/2018/07/2018073013362018-07-230746252018-07.html#20180726115520
2018-08-03_115511＿テレビの画面・バイキング・今日のニュース　山根会長が９０分の猛反論　文科省汚職　日大・田中理事長HPで謝罪へ.jpg http://hirono2014sk.blogspot.com/2018/08/2018080714542018-08-010923462018-08.html#20180803115511
2018-08-07_115517＿テレビの画面・バイキング・今日のニュース　山根帝国｜「宿舎で全員の前で恫喝」｜保護者「子供まで不正知ってる」.jpg http://hirono2014sk.blogspot.com/2018/08/2018081213552018-08-071155172018-08.html#20180807115517
2018-08-28_115514＿テレビの画面・バイキング・今日のニュース.jpg http://hirono2014sk.blogspot.com/2018/08/2018083115142018-08-262143542018-08.html#20180828115514
```

　なお、沢田研二のコンサート中止のことは、朝の8時の番組の始まりでも目にしていました。今日は岡口基一裁判官の戒告処分のニュースを探すため、8時からは何度もあちこちにチャンネルを変更していましたが、それらしいものを見ることはありませんでした。

　念の為もあり、とくダネは録画しているはずです。録画は同じ時間に１つしかできないのですが、とくダネを選択したのは、過去に岡口基一裁判官がツイートで、とくダネの司会者の小倉智昭さんに変態扱いされたような不満を書いているのを見かけたような記憶があるからです。

　時刻は15時02分です。テレビのミヤネ屋で司会者が、二千円札を見かけたことがないと言っていますが、3年ほどともいい。まわりの出演者にも聞きまわっていました。私は二千円札を一度も見たことがなく、それもずいぶん前から気になってはいました。

　ミヤネ屋では全国ニュース前の前半に続き、後半に入っても紀州のドンファンの不審死を取り上げています。テレビで取り上げているのを見たのもずいぶん久しぶりですが、「独占　紀州ドン・ファン”真犯人正体”　最も知るライター取材全記録」というタイトルでやっています。

　たぶんというか間違いなく、週刊文春で佐藤大和弁護士と一緒に取り上げられていた記者だと思います。名前も出ていましたが、本人は出演していないようです。はじめ余り見かけない人が出て説明をしていたので、その記者なのかと思ったのですが、違っていました。

　今回の記者の告白では、不審死をした本人が覚せい剤をやっていると電話で打ち明け、男性機能の回復のために効果があるとそそのかされて、やったのではないかという関係者の推測も交えて紹介しています。

　紀州のドン・ファン不審死事件といえば、佐藤大和弁護士が被疑者に近い扱いになっていた再婚相手の若い女性の代理人となって、出演の多かったバイキングでもごたごたがあったようですが、最近は佐藤大和弁護士もまた出演するようになっていて、それより先にミヤネ屋が取り上げたのも気になります。

　そういえば土日の辺りに佐藤大和弁護士がバイキングの月曜日のレギュラー出演だと初めてしったのですが、月曜日には出ていませんでした。同じく代理人をするという愛媛ご当地アイドル自殺訴訟が大きな話題という扱いになっていたので、出演を控えたのかもしれません。

　前にも紀州のドン・ファン不審死事件の妻の代理人となりながら番組に出演し、事件についての話をしていたため、視聴者の批判や苦情があったというような情報は見かけていました。

