#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "成仏理論について再び考えさせられた深澤諭史弁護士のTwitterタイムライン"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-09-17 14:25:01 +0900

tags:  深澤諭史弁護士 Twitterタイムライン 成仏理論

#contents

* 成仏理論

** 深澤諭史弁護士

*** 2018年9月15日のTwitterタイムライン

▶ ツイート％fukazawas（深澤諭史）％2018/09/15 11:18％ [[https://twitter.com/fukazawas/status/1040786978449481728>>https://twitter.com/fukazawas/status/1040786978449481728]]  
&twitter(1040786978449481728){theme:light}  
> 修習生の就職状況がおそらく今以上に悪かった頃，会社がわざわざ修習生向けに求人を出して「法律家としてのスキルは求めていない（お前らが一生懸命勉強してきたことに金は払わないし，無駄だったんだよ（笑）くやしいのう，くやしいのう，メシウマ！）」っていうのが流行ったよね。~~
> （・∀・）ＲＴ~~  
▶

▶ ツイート％fukazawas（深澤諭史）％2018/09/15 11:24％ [[https://twitter.com/fukazawas/status/1040788455884615680>>https://twitter.com/fukazawas/status/1040788455884615680]]  
&twitter(1040788455884615680){theme:light}  
> （；・∀・）これが答えだと同意。~~
> （＊＾ω＾）就職難の世代がその後，スムーズに独立できている例が多いのは，就職さえしてしまえば，そこそこの待遇になるので，独立に必要なお金も経験も得られるからだお。~~
> （；・∀・）逆に，ブラック事務所… https://t.co/prGUOZvLc7~~  
▶

▷ リツイート→fukazawas（深澤諭史）＞Route66_LP3（ルート６６（元ルパン３世））｜2018/09/15 11:24／2018/09/15 11:20｜[[https://twitter.com/fukazawas/status/1040788470019514368>>https://twitter.com/fukazawas/status/1040788470019514368]]  ／[[https://twitter.com/Route66_LP3/status/1040787410324402176>>https://twitter.com/Route66_LP3/status/1040787410324402176]]  
&twitter(1040788470019514368){theme:light}  
> RT @Route66_LP3: 最悪期はそもそも就職先がない、という状況でしたが、新人弁護士の待遇が底を打ち、「こんな待遇で雇えるんだ」と採用側が理解した結果、就職難が解消したという状況です。 https://t.co/R3LZynCsvA~~  
▷

▶ ツイート％fukazawas（深澤諭史）％2018/09/15 11:30％ [[https://twitter.com/fukazawas/status/1040789850813718528>>https://twitter.com/fukazawas/status/1040789850813718528]]  
&twitter(1040789850813718528){theme:light}  
> たぶん，これは，この社会の「窮地に陥っている人間を使うときは，最大限足元を見るのは当然のこと」＋「自分たちの『外』で積んだ経験や技術は徹底的に無視したい」という性質が悪魔合体した結果だと思う。 https://t.co/cTaX3anKiB~~  
▶

▶ ツイート％fukazawas（深澤諭史）％2018/09/15 11:30％ [[https://twitter.com/fukazawas/status/1040789850813718528>>https://twitter.com/fukazawas/status/1040789850813718528]]  
&twitter(1040789850813718528){theme:light}  
> たぶん，これは，この社会の「窮地に陥っている人間を使うときは，最大限足元を見るのは当然のこと」＋「自分たちの『外』で積んだ経験や技術は徹底的に無視したい」という性質が悪魔合体した結果だと思う。 https://t.co/cTaX3anKiB~~  
▶

▷ リツイート→fukazawas（深澤諭史）＞rippy08（りっぴぃ）｜2018/09/15 11:33／2018/09/15 11:32｜[[https://twitter.com/fukazawas/status/1040790795496742912>>https://twitter.com/fukazawas/status/1040790795496742912]]  ／[[https://twitter.com/rippy08/status/1040790423893995520>>https://twitter.com/rippy08/status/1040790423893995520]]  
&twitter(1040790795496742912){theme:light}  
> RT @rippy08: 修習生や弁護士求人だけではなく、それこそロスジェネ世代は就活中にその種の圧迫面接やパワハラ（大学で学んだことなんて会社に入ったら役立たないよ、とか、○○大出てそれか、みたいな）を受けまくっていたのでは、、、~~
> そして下手したら現在進行形で、、、 http…~~  
▷

▶ ツイート％fukazawas（深澤諭史）％2018/09/15 12:17％ [[https://twitter.com/fukazawas/status/1040801635511951360>>https://twitter.com/fukazawas/status/1040801635511951360]]  
&twitter(1040801635511951360){theme:light}  
> 事業の適法性に関する法律相談における，「その事業の違法性の可能性・程度の高さ」と「法律相談料を案内したら連絡がなくなる可能性」は，非常に綺麗な相関関係がありますね。~~
> （・∀・）~~  
▶

▷ リツイート→fukazawas（深澤諭史）＞anbasalaw（アンバサダ）｜2018/09/15 12:29／2018/09/15 12:26｜[[https://twitter.com/fukazawas/status/1040804817394753541>>https://twitter.com/fukazawas/status/1040804817394753541]]  ／[[https://twitter.com/anbasalaw/status/1040804128887205888>>https://twitter.com/anbasalaw/status/1040804128887205888]]  
&twitter(1040804817394753541){theme:light}  
> RT @anbasalaw: 300万円なんて○年目の弁護士から見てハナクソ、という方がいる一方で、新人弁護士の年収は300万円とのお話も聞きます。となると、上記のハナクソで婚約指輪(3ヶ月相当)を4個買えちゃうんだね。おかしいね。どこがおかしいんだろうね。仮に訴訟なら、このよ…~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞warabimon（わらびもち）｜2018/09/15 12:30／2018/09/15 12:27｜[[https://twitter.com/fukazawas/status/1040804916074172417>>https://twitter.com/fukazawas/status/1040804916074172417]]  ／[[https://twitter.com/warabimon/status/1040804145345646593>>https://twitter.com/warabimon/status/1040804145345646593]]  
&twitter(1040804916074172417){theme:light}  
> RT @warabimon: 日弁◯の偉い人が飲み会の席で~~
> ~~
> 「合格者が1500人になれば都市圏の就活事情が厳しくなり、地方に流れゼロワン地域が減る予定だった。現実は単に都市圏の若手が買い叩かれるだけで、ゼロワン地域もあまり減らなかった。失敗した。」~~
> ~~
> と言ってて、大爆笑した。~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞jikapan（自家製パンチェッタ）｜2018/09/15 13:17／2018/09/15 12:45｜[[https://twitter.com/fukazawas/status/1040816926631456770>>https://twitter.com/fukazawas/status/1040816926631456770]]  ／[[https://twitter.com/jikapan/status/1040808839874932736>>https://twitter.com/jikapan/status/1040808839874932736]]  
&twitter(1040816926631456770){theme:light}  
> RT @jikapan: ウチに、「お金はいりませんから１年だけ無料で籍を置いて働かせてもらえませんか」と電話が来たのがたしか６４か６５期の修習生。~~
> たぶん、どん底はその辺。~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞anbasalaw（アンバサダ）｜2018/09/15 16:24／2018/09/15 16:10｜[[https://twitter.com/fukazawas/status/1040863891876569088>>https://twitter.com/fukazawas/status/1040863891876569088]]  ／[[https://twitter.com/anbasalaw/status/1040860405701140480>>https://twitter.com/anbasalaw/status/1040860405701140480]]  
&twitter(1040863891876569088){theme:light}  
> RT @anbasalaw: 貸与制について、ふつふつと怒りを覚えるようになったのは、64期まで続いていた給費制の内容が、とても高額・好条件だったと知ったからですね。無知を曝すようでアレですが、月20万程度を12回もらっているだけだと思っていました。思い込みです。~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞harrier0516osk（向原総合法律事務所　弁護士向原）｜2018/09/15 17:47／2018/09/15 17:46｜[[https://twitter.com/fukazawas/status/1040884826608300032>>https://twitter.com/fukazawas/status/1040884826608300032]]  ／[[https://twitter.com/harrier0516osk/status/1040884646609743873>>https://twitter.com/harrier0516osk/status/1040884646609743873]]  
&twitter(1040884826608300032){theme:light}  
> RT @harrier0516osk: 古来より、借金漬け→低賃金でも働かざるを得ないスパイラルに誘導する　という手法はあったわけで、法曹養成制度改革の狙いはそれかもなと邪推しています。~~
> なったあとにこの構造を見抜いた人は成仏せずに済むが、そもそも志願者が見抜いちゃったので法曹…~~  
▷



*** 2018年9月14日のTwitterタイムライン

弁護士らの不遇、不満の象徴としての成仏理論と地蔵菩薩の衆生済度：成仏理論／深澤諭史弁護士／2018年9月15日のTwitterタイムライン http://hirono2018.memo.wiki/d/%ca%db%b8%ee%bb%ce%a4%e9%a4%ce%c9%d4%b6%f8%a1%a2%c9%d4%cb%fe%a4%ce%be%dd%c4%a7%a4%c8%a4%b7%a4%c6%a4%ce%c0%ae%ca%a9%cd%fd%cf%c0%a4%c8%c3%cf%c2%a2%ca%ee%bb%a7%a4%ce%bd%b0%c0%b8%ba%d1%c5%d9#content_1_1_1

▶ ツイート％fukazawas（深澤諭史）％2018/09/14 09:45％ [[https://twitter.com/fukazawas/status/1040401102611537921>>https://twitter.com/fukazawas/status/1040401102611537921]]  
&twitter(1040401102611537921%3E){theme:light}  
> 民訴法学者の方が言っていた。~~
> ~~
> 『餓死しない＋感謝＝成仏』と。~~
> ~~
> 餓死しない程度の生活でも感謝されれば，喜んで成仏できるという意味らしい。~~
> ~~
> 本当の法律家は，豊かな生活のために目指す職業ではない。成仏できればいいではないか。~~
> ~~
> 果… https://t.co/9pGtoHde2f~~  
▶

▷ リツイート→fukazawas（深澤諭史）＞LiarLawyer800（嘘つき弁護士。）｜2018/09/14 10:03／2018/09/14 10:03｜[[https://twitter.com/fukazawas/status/1040405718665388032>>https://twitter.com/fukazawas/status/1040405718665388032]]  ／[[https://twitter.com/LiarLawyer800/status/1040405635949461504>>https://twitter.com/LiarLawyer800/status/1040405635949461504]]  
&twitter(1040405718665388032%3E){theme:light}  
> RT @LiarLawyer800: 少なくとも俺は違う。そこそこ豊かで文化的な生活がしたい。~~
> むしろ、生活基盤が安定してないと、プロボノも出来んよ？って話 https://t.co/1NCz2mItpe~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞O59K2dPQH59QEJx（ピピピーッ）｜2018/09/14 10:10／2018/09/14 10:10｜[[https://twitter.com/fukazawas/status/1040407510736265216>>https://twitter.com/fukazawas/status/1040407510736265216]]  ／[[https://twitter.com/O59K2dPQH59QEJx/status/1040407464452153345>>https://twitter.com/O59K2dPQH59QEJx/status/1040407464452153345]]  
&twitter(1040407510736265216%3E){theme:light}  
> RT @O59K2dPQH59QEJx: 貧しい法律家ほど信用できないものはない。 https://t.co/R6KqnzAkHD~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞sokudokubengosi（ワーキングプア弁護士）｜2018/09/14 13:07／2018/09/14 12:36｜[[https://twitter.com/fukazawas/status/1040452012003848192>>https://twitter.com/fukazawas/status/1040452012003848192]]  ／[[https://twitter.com/sokudokubengosi/status/1040444248624001024>>https://twitter.com/sokudokubengosi/status/1040444248624001024]]  
&twitter(1040452012003848192%3E){theme:light}  
> RT @sokudokubengosi: @fukazawas 私は乞食になろうが依頼者から嫌味を言われようが、国選と法テラスをやり続けて成仏する所存でございます。大変残念なのは件の学者様が成仏される前に弁護士資格を返上してしまったことです。未だ成仏するまではだいぶ長い道のりか…~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞yasumasa218（新谷泰真）｜2018/09/14 13:11／2018/09/14 11:21｜[[https://twitter.com/fukazawas/status/1040452990153285633>>https://twitter.com/fukazawas/status/1040452990153285633]]  ／[[https://twitter.com/yasumasa218/status/1040425224812945408>>https://twitter.com/yasumasa218/status/1040425224812945408]]  
&twitter(1040452990153285633%3E){theme:light}  
> RT @yasumasa218: イチケイのカラスを買ったので、櫻井先生にご飯を奢ってもらおう。~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞take___five（中村剛（take-five））｜2018/09/14 13:12／2018/09/13 15:27｜[[https://twitter.com/fukazawas/status/1040453135343398919>>https://twitter.com/fukazawas/status/1040453135343398919]]  ／[[https://twitter.com/take___five/status/1040124768366686213>>https://twitter.com/take___five/status/1040124768366686213]]  
&twitter(1040453135343398919%3E){theme:light}  
> RT @take___five: 処分保留釈放後の弁護活動について、何らかの手当ては必要だと思うんだけど、それで怖いのは、「処分保留釈放後も国選弁護人の選任の効力は続くよう法改正がなされたが、報酬は特に支払われない」という事態なんだよね…。~~  
▷

▶ ツイート％fukazawas（深澤諭史）％2018/09/14 13:20％ [[https://twitter.com/fukazawas/status/1040455320135360512>>https://twitter.com/fukazawas/status/1040455320135360512]]  
&twitter(1040455320135360512%3E){theme:light}  
> 契約書を起案しているときの脳と，プログラミングしているときに使う脳の部分が，概ね共通していることに気が付きました。~~
> （・∀・）~~  
▶

▷ リツイート→fukazawas（深澤諭史）＞Hideo_Ogura（小倉秀夫）｜2018/09/14 14:24／2018/09/14 14:21｜[[https://twitter.com/fukazawas/status/1040471443501277184>>https://twitter.com/fukazawas/status/1040471443501277184]]  ／[[https://twitter.com/Hideo_Ogura/status/1040470579948609537>>https://twitter.com/Hideo_Ogura/status/1040470579948609537]]  
&twitter(1040471443501277184%3E){theme:light}  
> RT @Hideo_Ogura: 法学部生がソフトハウスから採用されやすいのは、そういうことも理由の一つにありますね。RT @fukazawas: 契約書を起案しているときの脳と，プログラミングしているときに使う脳の部分が，概ね共通していることに気が付きました。 （・∀・）~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞juntaba1（過食弁護士）｜2018/09/14 15:53／2018/09/14 15:49｜[[https://twitter.com/fukazawas/status/1040493706984402944>>https://twitter.com/fukazawas/status/1040493706984402944]]  ／[[https://twitter.com/juntaba1/status/1040492808514097152>>https://twitter.com/juntaba1/status/1040492808514097152]]  
&twitter(1040493706984402944%3E){theme:light}  
> RT @juntaba1: 手元資金を自分の弁護士にも少なく見せかける依頼人がいる。支払いを減らすためであろうが、誤った資力前提の交渉では、ギリギリ和解できた案件が不本意に決裂したりする。~~
> と思っていたら倫理研修の課題で「代理人は資力あるのに知っててないふりしたらダメ」（意訳）…~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞ryskv（りゃすこふ）｜2018/09/14 19:47／2018/09/14 19:44｜[[https://twitter.com/fukazawas/status/1040552615140970496>>https://twitter.com/fukazawas/status/1040552615140970496]]  ／[[https://twitter.com/ryskv/status/1040551935063937024>>https://twitter.com/ryskv/status/1040551935063937024]]  
&twitter(1040552615140970496%3E){theme:light}  
> RT @ryskv: 刑事事件の報酬、あまりにも安いよな。これほど労力を割いているのに。~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞Bibendum65（仙猫カリン）｜2018/09/14 19:47／2018/09/14 19:44｜[[https://twitter.com/fukazawas/status/1040552660292648960>>https://twitter.com/fukazawas/status/1040552660292648960]]  ／[[https://twitter.com/Bibendum65/status/1040551746991415296>>https://twitter.com/Bibendum65/status/1040551746991415296]]  
&twitter(1040552660292648960%3E){theme:light}  
> RT @Bibendum65: 政財界の“お偉いさん”がいう「法曹のニーズ」って、~~
> 　リーガルチェックで細かいこと言わない~~
> 　むしろ、黒を白にするくらいの気概がほしい~~
> 　でも、いざとなれば弁護士業務は外注するんで、必ずしも法曹資格は不要~~
> 　給与はせいぜい大学院卒と同じ~~
> みたいな…~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞Bibendum65（仙猫カリン）｜2018/09/14 19:48／2018/09/14 19:47｜[[https://twitter.com/fukazawas/status/1040552958721552385>>https://twitter.com/fukazawas/status/1040552958721552385]]  ／[[https://twitter.com/Bibendum65/status/1040552492797288449>>https://twitter.com/Bibendum65/status/1040552492797288449]]  
&twitter(1040552958721552385%3E){theme:light}  
> RT @Bibendum65: 法的に複雑な問題が絡み合って、種々の要因から依頼者の対応も難しくて、経済的には全くペイしない案件を率先して受けてくれる弁護士のニーズはあるだろうけど、それは経済的な「需要」とは呼ばないだろう普通。。。~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞luckymangan（リーチ一発ツモ裏１）｜2018/09/14 19:56／2018/09/14 19:51｜[[https://twitter.com/fukazawas/status/1040554946653937664>>https://twitter.com/fukazawas/status/1040554946653937664]]  ／[[https://twitter.com/luckymangan/status/1040553729747902464>>https://twitter.com/luckymangan/status/1040553729747902464]]  
&twitter(1040554946653937664%3E){theme:light}  
> RT @luckymangan: 「〇依頼もしない人の無料相談を受けたり、調べものをしたこと~~
> 開業後あるある。そもそも時間の無駄。~~
> 世の中には、「ただで情報を知りたい人」＝「情報に価値はないと思ってる人」が結構多いことを認識した点では、勉強になった。」 https://t.co…~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞himaben1st（暇弁＠もうだめぽ）｜2018/09/14 20:04／2018/09/14 20:03｜[[https://twitter.com/fukazawas/status/1040556790029512704>>https://twitter.com/fukazawas/status/1040556790029512704]]  ／[[https://twitter.com/himaben1st/status/1040556578036805632>>https://twitter.com/himaben1st/status/1040556578036805632]]  
&twitter(1040556790029512704%3E){theme:light}  
> RT @himaben1st: 国家権力そのものである行政が憲法改正を口にすること自体がタブーなんだが、そんなこともわからんのかこのド阿呆は。 https://t.co/yy3uY8F8S1~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞lawkus（ystk）｜2018/09/14 20:27／2018/09/14 20:21｜[[https://twitter.com/fukazawas/status/1040562681898393600>>https://twitter.com/fukazawas/status/1040562681898393600]]  ／[[https://twitter.com/lawkus/status/1040561265645502464>>https://twitter.com/lawkus/status/1040561265645502464]]  
&twitter(1040562681898393600%3E){theme:light}  
> RT @lawkus: 「お願い 弁護人接見終了後、看守が来るまでお待ち願います」という以前はなかった掲示が接見室にあった。このようなものに従う義務はもちろんないが、逃走事件があって大変なのはわかるし、別に今急いでもいないし、お願いということなら聞いてあげようと思い協力した。~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞yotajirosan（起案ソープ）｜2018/09/14 20:28／2018/09/13 13:48｜[[https://twitter.com/fukazawas/status/1040562827658878976>>https://twitter.com/fukazawas/status/1040562827658878976]]  ／[[https://twitter.com/yotajirosan/status/1040099923079786496>>https://twitter.com/yotajirosan/status/1040099923079786496]]  
&twitter(1040562827658878976%3E){theme:light}  
> RT @yotajirosan: 人ごとのように報道しているが，逮捕段階で犯人扱いの報道をし，有罪との心証を市民に植え付けているマスコミは自らを振り返ることはないのだろうか。もやる。 https://t.co/lIGNsBUbrb~~  
▷

▷ リツイート→fukazawas（深澤諭史）＞lawkus（ystk）｜2018/09/14 20:48／2018/09/14 12:04｜[[https://twitter.com/fukazawas/status/1040567925692747777>>https://twitter.com/fukazawas/status/1040567925692747777]]  ／[[https://twitter.com/lawkus/status/1040436093672255488>>https://twitter.com/lawkus/status/1040436093672255488]]  
&twitter(1040567925692747777%3E){theme:light}  
> RT @lawkus: 相手方から恨まれた結果だとしたら有能さの証かもしれませんね。 https://t.co/d56ozDj2g2~~  
▷

▶ ツイート％nkaoguo（Kay）％2018/09/14 12:03％ [[https://twitter.com/nkaoguo/status/1040435792030523393>>https://twitter.com/nkaoguo/status/1040435792030523393]]  
&twitter(1040435792030523393){theme:light}  
> 昔の後輩が同期たちと経営している事務所をGoogleさんで検索したらサジェストに「悪徳」って出てきた…。~~  
▶

▷ リツイート→fukazawas（深澤諭史）＞momoo_t（弁護士 マンション管理士 桃尾俊明）｜2018/09/14 20:53／2018/09/14 20:53｜[[https://twitter.com/fukazawas/status/1040569310496747520>>https://twitter.com/fukazawas/status/1040569310496747520]]  ／[[https://twitter.com/momoo_t/status/1040569138987450368>>https://twitter.com/momoo_t/status/1040569138987450368]]  
&twitter(1040569310496747520%3E){theme:light}  
> RT @momoo_t: 「桃尾は悪徳弁護士」というビラをマンションにばら撒かれてからが本番です。 https://t.co/cZkaRlflRa~~  
▷


