#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "弁護士記録資料"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-10-12 10:14:56 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  愛媛のご当地アイドル自殺 佐藤大和弁護士 向原栄大朗弁護士

#contents

* 愛媛のご当地アイドル自殺

** 

* モトケンこと矢部善朗弁護士（京都弁護士会）

** リツイート
*** 捜査段階で毎日来てくれる地元弁護士を頼んだ方が、有効だし、安上がりだ。（奥村徹弁護士）
     :LOGBOOK:
     CLOCK: [2018-10-12 金 11:42]--[2018-10-12 金 14:43] =>  3:01
     :END:

 ▷ リツイート→motoken_tw（モトケン）＞okumuraosaka（強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)）｜2018/10/12 10:28／2018/10/12 10:13｜https://twitter.com/motoken_tw/status/1050558739571331072 ／ https://twitter.com/okumuraosaka/status/1050555078329790464
 &twitter(1050558739571331072){theme:light}
 > RT @okumuraosaka: どんな同機か知らないが虚偽自白して有罪になって、それを控訴審で挽回するのは難しい。捜査段階で毎日来てくれる地元弁護士を頼んだ方が、有効だし、安上がりだ。奥村も遠方からの相談では、まず地元の刑事やってる弁護士を捜すように回答してて、結果も良好  

 ▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2018/10/12 11:47％ https://twitter.com/s_hirono/status/1050578666579578880
 &twitter(1050578666579578880){theme:light}
 > 2018-10-12-112939_モトケンのリツイート（強制わいせつ／準強姦／買春／児童ポルノ／児童福祉法／青少年条例弁護人弁護士奥村徹（大阪弁護士会）　@okumurao.jpg https://t.co/c29co1w0rV  
 ▶

 　ちょっとだけ書いておきたいと思います。一昨日の１０日になりますが、図書館に立ち寄り、新聞各紙を見ていました。元横綱輪島関の死去について記事を見ていたのですが、その時、地元の能登高校で事件があったことを知りました。次の事件になります。

 ［link：］ 県立高校職員を逮捕＝女性宅に侵入、わいせつ容疑－石川県警：時事ドットコム https://www.jiji.com/jc/article?k=2018100900944&g=soc

 　上記の記事は「2018/10/09-18:54」という配信時刻になっています。容量不足で石川県内ニュースの番組録画が出来ていなかったようです。あるいは見ないまま削除した可能性も少しはあるのですが、容量不足のことは昨夜の「リーガルV」が始まった21時04分頃に気が付きました。

 　通常、録画機器は録画が始まるとデジタル表示でカウントが始まるのですが、００：００などとなったまま点滅していたので、またやってしまったと聞きました。ちょうど台所の方に行っていたので、番組の最初は視聴も録画も出来なかったことになります。

 ```
 容疑者は「触っていないし、現場にも行っていない」と容疑を否認しているという。
 　逮捕容疑は８月２４日午前１時ごろ、石川県内の民家に侵入し、１０代の女性の体を触るなどした疑い。
 　同署によると、同日午前２時半ごろ、女性の関係者から通報があった。聞き込みや遺留物などから

 ［source：］県立高校職員を逮捕＝女性宅に侵入、わいせつ容疑－石川県警：時事ドットコム https://www.jiji.com/jc/article?k=2018100900944&g=soc
 ```

 　実名の部分は避けて引用しました。「県立能登高校主事」となっていますが、別の新聞記事では教師ではないような説明が書いてありました。昔、用務員と呼ばれた役職なのかとも考えたのですが、年配というイメージが強く、26歳ということなので、違うような気はしています。

 　本人が否認をしているので、とりわけ刑事弁護的にはえん罪の可能性もありそうですが、ほとんど問題にはされていない感じです。テレビで報道は一切見ておりませんが、昨日の午前中は、尻を触ったとか些細とも思われる性犯罪事件で、実名から全国放送されていたので、どういう基準なのかと考えました。

 　昨年だったと思いますが、3月に同じ能登高校の女子高生殺害事件があり、被疑者が能登高校南のバス停から連れ去り、その50分ほどあとに車に飛び込んで自殺をし、そこから事件が発覚したという経緯でしたが、それが逃げたり、遺体を山の中に隠したりしていれば、どうなったのかと想像します。

 　連れ去りからの殺害場所となったのは能登町の宇加塚で、戸数も少ない山間で、近くには宇加塚峠があったり、遺体を遺棄する場所はいくらでもあったことになりますが、自殺した被疑者は、携帯電話や財布まで現場の家に遺したまま飛び出し、20,30分後に死亡したようです。

 　奥能登という地域も過去にはえん罪とは無縁ではなく、「蛸島事件」というのがあります。私はその事件のことを全く知らなかったのですが、被告発人大網健二から差し入れされた別冊ジュリストに記載があって、初めて知ったように思います。

 　そういえばその3冊の別冊ジュリストも、まだ家のどこにあるのか見つけていません。

 　昨年だったように思いますが、祭礼委員をしていた年配者の人に、蛸島で昔、子どもの殺人事件があったという話が出て、その行方不明となった場所が、高倉彦神社だと初めて知ったように思いました。

 　この珠洲市蛸島の高倉彦神社については、前にGoogleで検索をしたことがあったのですが、同名の神社というのは日本で他になさそうでした。

 ```
 蛸島事件（たこじまじけん）とは、1965年（昭和40年）に石川県珠洲市蛸島町で発生した殺人事件である。犯人の逮捕されていない未解決事件であり、また冤罪事件ともなった。


 目次
 1	概要
 2	事件の問題点
 3	脚注
 4	参考文献
 概要［編集］
 1965年7月5日、能登半島の小さな港町である蛸島地区で、当時10歳の少年が行方不明となり、翌日他殺体で発見された。警察は初動捜査において容疑者を絞り込めなかったため、地区住民約2500人のうち小学校高学年以上の1785人のアリバイを調べた［1］。

 8月11日、地区の青年が別件逮捕され、実際には殺人容疑で徹底的に取調べが行われたが、アリバイがあったため8月22日に釈放された。続いて8月30日に当時16歳の少年を住居侵入と窃盗の容疑で逮捕した［1］。

 しかしながら、少年の逮捕容疑は半年前のものであり、しかも留守にしていた無施錠の親類の家（現在でも農村部には見られる風習で、玄関に鍵をかけず親しい者同士で自由に出入りするのが普通であった）に入ったというもので、窃盗もでっち上げで警察が親類に無理矢理被害届を出させたもの［2］であって、本来ならば、「このような軽微な事案の取り調べだけならば、被告人の逮捕に踏み切ったかどうかも疑問」と裁判所に言わせしめるような別件逮捕であった［2］。

 この取り調べの過程で、少年は前述の殺人について犯行を自白したが、この自白以外に証拠はなく、少年は起訴されたものの、金沢地方裁判所七尾支部は1969年6月3日に無罪判決を言い渡した。判決文には、この事件の被告人に対する警察・検察側の別件逮捕・勾留を、刑事訴訟法203条以下と日本国憲法33条ならびに34条に違反すると批判している ［2］。検察側が控訴を断念したため、同少年の無罪が確定した。

 ［source：］蛸島事件 - Wikipedia https://ja.wikipedia.org/wiki/%E8%9B%B8%E5%B3%B6%E4%BA%8B%E4%BB%B6
 ```

 　上記に事件の概要という部分を引用しました。前にも読んでいた内容だと思いますが、今回意外に思ったのは、「金沢地方裁判所七尾支部は1969年6月3日に無罪判決を言い渡した。」という部分です。昭和44年だと、私は5歳ということになりますので、ニュースは目にしていたのかもしれません。

 　2,3日前から構想が出来ているのですが、この続きは「告訴の事実」として、記録をしたいと思います。金沢市場輸送と珠洲市蛸島の関わりです。

 ```
 平成３０年度の金沢弁護士会会長の小堀秀行です。金沢弁護士会には石川県内の１７４名の弁護士が全員登録しています（３０年４月１日現在）。北から輪島支部管内２名，七尾支部管内６名，金沢本庁管内１５４名，小松支部管内１２名です。

 ［source：］会長からのご挨拶｜金沢弁護士会 http://www.kanazawa-bengo.com/about/greeting/index.html
 ```

 　私の平成11年の事件の控訴審の国選弁護人ともなった小堀秀行弁護士が、今年度から金沢弁護士会の会長となっていたことは、テレビの画面を撮影した写真で初めて気が付きました。静止画として見ることで、書面への署名に気がついたのです。映像だけだと気が付きませんでした。

 　輪島支部管内というのがよくわからないのですが、たぶん穴水町も含まれるのだと思います。穴水町も以前は宇出津と同じ鳳至郡でしたが、現在も同じ鳳珠郡となるようです。

 ```
 鳳珠郡（ほうすぐん）は、石川県の郡。

 人口24,624人、面積456.48km²、人口密度53.9人/km²。（2018年4月1日、推計人口）

 以下の2町を含む。

 穴水町（あなみずまち）
 能登町（のとちょう）

 ［source：］鳳珠郡 - Wikipedia https://ja.wikipedia.org/wiki/%E9%B3%B3%E7%8F%A0%E9%83%A1
 ```

 　わかりやすく穴水町と能登町の2町が鳳珠郡だと書いてありますが、こういうのを見たのも初めてのような気がしました。以前は余り意識していなかったので気がついていなかったのかもしれません。穴水町は輪島警察署の管内になると聞いたように思うので、裁判所も同じかと思います。

 　穴水町に法律事務所が出来たのは、3,4年ほど前に情報を見ていました。都会から移住した夫婦の弁護士だったように思います。テレビの番組でも見たことがあって、自宅で男の子2人だったように思いますが4人家族で過ごす様子が出ていました。

 　弁護士は逆恨みをされやすいという話も聞いていたので、その番組を見たときは少し意外に感じました。

 　まだ1年は経っていないように思いますが、テレビで似たような場面を見たことがあり、初めは職業も全くわからなかったのですが、全盲の夫婦でした。夫婦ともにだったのかはわすれましたが、夫の職業は弁護士でした。横浜だったとも思います。

 ［link：］ 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「全盲」の検索結果 - Twilog https://twilog.org/hirono_hideki/search?word=%E5%85%A8%E7%9B%B2&ao=a

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 09:02％ https://twitter.com/hirono_hideki/status/997628516450488320
 &twitter(997628516450488320){theme:light}
 > 日本で三人目の全盲の弁護士になった、という。  
 ▶

 ［link：］ 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年05月19日 - Twilog https://twilog.org/hirono_hideki/date-180519

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 23:57％ https://twitter.com/hirono_hideki/status/997853831110119424
 &twitter(997853831110119424){theme:light}
 > 基本的に菩薩と言ったら「穏やかか表情」を浮かべる方も多いはず。しかし、いくら説いても聞かない輩は聞かないし、煩悩が絶えない輩は絶えません。そうなると、馬頭観音の出番となります。元明王との説もある馬頭観音、憤怒相を持っているのも無理… https://t.co/AF1zl6udj5  
 ▶

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 23:56％ https://twitter.com/hirono_hideki/status/997853402385141761
 &twitter(997853402385141761){theme:light}
 > 「千手観音」。本名は千手千貫観世音菩薩といい、その名の通り伝承では掌に目玉があるそうです。像では持物（じぶつ）があるため確認しづらいのがほとんどですが。顔もたくさんありますが、これは「どこにいようと、誰だろうと見つけ出して救う」と… https://t.co/t5yLRvTi7d  
 ▶

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 23:54％ https://twitter.com/hirono_hideki/status/997853086352793600
 &twitter(997853086352793600){theme:light}
 > 初心者でもわかる！ 観音様の見分け方｜仏像｜趣味時間 https://t.co/3snB0HySGV  
 ▶

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 23:46％ https://twitter.com/hirono_hideki/status/997850941679222784
 &twitter(997850941679222784){theme:light}
 > 【前編】修行をしながら衆生を救う、菩薩にまつわるエトセトラ｜仏像｜趣味時間 https://t.co/M287ZTaGYZ  
 ▶

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 23:43％ https://twitter.com/hirono_hideki/status/997850337036812289
 &twitter(997850337036812289){theme:light}
 > 衆生(しゅじょう)とは - コトバンク https://t.co/Bop5qWJyfA
 > なぜか衆上と勘違いしていた。上申という意味合いを強く意識していたのかもしれない。神様の目線でふざけたやつ。  
 ▶

 　千手観音の掌に目玉がある、というのは全く初めて知ったように思いました。引用をツイートしているので読んでいたはずですが不思議です。馬頭観音については、テレビで羽咋市のお寺を見たことがきっかけで、Googleで検索したような憶えがあります。

 　「衆生」とありますが、これは「衆生済度」のことではと思われます。ポケモンGOがきっかけで、旧柳田村の上町中又に「汗かき地蔵」の案内板を読んだのがきっかけでした。

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 21:26％ https://twitter.com/hirono_hideki/status/997815765666381825
 &twitter(997815765666381825){theme:light}
 > 深澤諭史弁護士。日本最強クラスの狂人系デタラメ弁護士。
 > &gt; 人権派弁護士，特に日本中から非難されている人の弁護をするとものすごいお金になるって，主張する人もいますしね。 \n \n それで稼げる国があるなら，弁護士は大勢その国に移… https://t.co/fE3eZ4BXhx  
 ▶

 　上記のツイートも自分の記憶から抜け落ちていました。

 ［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”（日本｜ニッポン｜にっぽん）．＊（スゴイ｜すごい｜スゴい）”／深澤諭史（@fukazawas）の検索（2014-06-12〜2018-05-06／2018年05月19日21時12分の記録45件） http://hirono2014sk.blogspot.com/2018/05/regexpfukazawas2014-06-122018-05.html

 　上記のまとめ記事は記憶にあったものです。

 ```
 ▶（01／45） TW fukazawas（深澤諭史） 日時：2014-06-12 19：22 URL： <https：//twitter.com/fukazawas/status/476897286870421504>
 {% tweet 476897286870421504 %}
 > 人権派弁護士，特に日本中から非難されている人の弁護をするとものすごいお金になるって，主張する人もいますしね。 \n \n それで稼げる国があるなら，弁護士は大勢その国に移住することでしょう…。 \n (･∀･；)

 ［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”（日本｜ニッポン｜にっぽん）．＊（スゴイ｜すごい｜スゴい）”／深澤諭史（@fukazawas）の検索（2014-06-12〜2018-05-06／2018年05月19日21時12分の記録45件） http://hirono2014sk.blogspot.com/2018/05/regexpfukazawas2014-06-122018-05.html
 ```

 ▶ ツイート％fukazawas（深澤諭史）％2014/06/12 10:22％ https://twitter.com/fukazawas/status/476897286870421504
 &twitter(476897286870421504){theme:light}
 > 人権派弁護士，特に日本中から非難されている人の弁護をするとものすごいお金になるって，主張する人もいますしね。
 > 
 > それで稼げる国があるなら，弁護士は大勢その国に移住することでしょう…。
 > (･∀･；)  
 ▶

 　蛸島からこういう深澤諭史弁護士のツイートが発掘されるとは思いませんでした。Twilogではよくある発見ではあります。

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 16:18％ https://twitter.com/hirono_hideki/status/997738230819704833
 &twitter(997738230819704833){theme:light}
 > 出没！アド街ック天国「八王子」
 > 
 > 2018年5月19日（土）  16時00分～16時54分  の放送内容 https://t.co/UqvLjv80vl  
 ▶

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/19 16:04％ https://twitter.com/hirono_hideki/status/997734813334302721
 &twitter(997734813334302721){theme:light}
 > 警察が情報提供求めた男児 無事｜NHK 新潟県のニュース https://t.co/LEF7wEVIsb  
 ▶

 　2018年5月19日に、盲目の弁護士夫婦の番組のことは出てきませんでした。少しは名前に記憶が残っていると思うので、名前から調べた方が早いかと思います。

 ［link：］ 全盲　弁護士　夫婦 - Google 検索 https://www.google.co.jp/search?source=hp&ei=KybAW9PHAdTahwOtqI2QDg&q=%E5%85%A8%E7%9B%B2%E3%80%80%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%80%80%E5%A4%AB%E5%A9%A6&oq=%E5%85%A8%E7%9B%B2%E3%80%80%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%80%80%E5%A4%AB%E5%A9%A6&gs_l=psy-ab.3..33i21k1.1747.8164.0.8940.26.25.0.0.0.0.195.2363.20j5.25.0....0...1c.1j4.64.psy-ab..1.24.2280.0..0i4k1j0i131k1j0i4i37k1j0i30k1j33i160k1.0.oSUgU7rv-Zs

 ▶ ツイート％fukazawas（深澤諭史）％2018/10/12 13:41％ https://twitter.com/fukazawas/status/1050607307082485760
 &twitter(1050607307082485760){theme:light}
 > 送信取り消しされないようにスクリーンショットとっておいて，警察に相談を・・。
 > もし，警察対応が難しければ，最寄りの弁護士へ・・。
 > （・∀・） https://t.co/amtiOWDxFX  
 ▶

 　URLが長すぎてAPIから投稿出来なかったので、ブラウザから投稿したのですが、その時、上記の深澤諭史弁護士のツイートが目に入りました。

 　時刻は13時53分です。テレビでバイキングを最初から終わりまでつけていましたが、結局、「愛媛のご当地アイドル自殺、訴訟提起」の件は、何事もなかったように触れずに終わったようです。

 　バイキングでは番組の始まりに3件ほど大見出しが出るのですが、元横綱輪島関死去が各局のニュースとなっていた当日も見出しに含まれておらず、日大の関係者ということで避けたのかとも考えたのですが、後半に話題のニュースランキングというコーナーで1位として、その時は取り上げていました。

 ［link：］ 夫婦ともに全盲の共働き家族「子育ては楽しい！」 | 大胡田一家の「見えないからこそ、見えること」 | 日経DUAL https://dual.nikkei.co.jp/article/076/69/

 ［link：］ 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「大胡田」の検索結果 - Twilog https://twilog.org/hirono_hideki/search?word=%E5%A4%A7%E8%83%A1%E7%94%B0&ao=a

 　Twilogの検索結果は、さきほどの2018年5月19日だけで、その日のツイートが12件でした。そのツイートもすべてがリツイートのようです。番組のことは記録していなかったようです。午後か夕方の時間帯に見た番組だったようには思っていましたが、確認はできそうにありません。

 ［link：］ 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「穴水 弁護士」の検索結果 - Twilog https://twilog.org/hirono_hideki/search?word=%E7%A9%B4%E6%B0%B4%E3%80%80%E5%BC%81%E8%AD%B7%E5%A3%AB&ao=a

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2015/08/12 15:46％ https://twitter.com/hirono_hideki/status/631356007055294464
 &twitter(631356007055294464){theme:light}
 > 穴水に弁護士がいるというのは今日初めて知った。輪島だけと聞いていたので。　 http://t.co/dv8zQVETXS  
 ▶

 ▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/01/29 20:22％ https://twitter.com/hirono_hideki/status/957937071082975233
 &twitter(957937071082975233){theme:light}
 > 金沢弁護士会の動きを、住民も歓迎する。集団予防接種でＢ型肝炎ウイルスに感染した能登町の男性（７０）は昨夏、国からの給付金を得るには訴訟手続きが必要と知り、相談のため車で約四十分かけて穴水まで出向いた。地域では司法サービスが疎遠とい… https://t.co/1t8ZkCM6CW  
 ▶
* 深澤諭史弁護士
** ツイート
*** そういや，今年度は，東京三弁護士会と東京司法書士会との協議会の副議長を仰せつかっておりますので，
    :LOGBOOK:
    CLOCK: [2018-10-16 火 12:16]--[2018-10-16 火 12:52] =>  0:36
    :END:

▶ ツイート％fukazawas（深澤諭史）％2018/10/16 11:54％ https://twitter.com/fukazawas/status/1052030042484527104
&twitter(1052030042484527104){theme:light}
> そういや，今年度は，東京三弁護士会と東京司法書士会との協議会の副議長を仰せつかっておりますので，メンバーの方がいらっしゃったらよろしくです。
> （・∀・）  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 12:18／2018-10-16 12:17 URL： https://twitter.com/kk_hirono/status/1052036084647878656 https://twitter.com/s_hirono/status/1052035854124773377
&twitter(1052036084647878656){theme:light}
> 2018-10-16-120813_深澤諭史（@fukazawas）：そういや，今年度は，東京三弁護士会と東京司法書士会との協議会の副議長を仰せつかっておりますので，メンバー.jpg https://t.co/yBw4LM91sP
◁◁◁

　時刻は12時19分ですが、深澤諭史弁護士のツイートの投稿は11時54分となっています。タイムラインの更新時に見かけたように思いますが、これはけっこう驚きました。東京三弁護士会というのは、東京の３つの弁護士会のことを意味するのかと思われます。

[link:] » 東京にはなぜ３つ弁護士会があるのですか ｜ 庶民の弁護士　伊東良徳 https://t.co/y2DTbknsrY

[link:] » 日本弁護士連合会：東京三弁護士会多摩支部 https://t.co/1pTQ73wfQL

[link:] » 東京弁護士会 - Wikipedia https://t.co/1YhgCsNQx9 \n 東京都には、単位弁護士会として、東京弁護士会のほか、第一東京弁護士会・第二東京弁護士会が存在し、所属する法律事務所が東京都内にある弁護士は、この3会のいずれか一つに所属する必要がある。

```
概要［編集］
東京都には、単位弁護士会として、東京弁護士会のほか、第一東京弁護士会・第二東京弁護士会が存在し、所属する法律事務所が東京都内にある弁護士は、この3会のいずれか一つに所属する必要がある。

東京都のみ地方裁判所管轄区と無関係に複数の弁護士会があるのは、会のあり方をめぐる考えの違いにより分裂したためとされている［2］［3］。3つの弁護士会は別々の場所にあったが、1995年の弁護士会館完成により同じ建物内に事務局がある。東弁は4階から7階、8・9・10階が二弁、11・12・13階が一弁で、日弁連は15階から17階にある。

所属する弁護士の会費、弁護士会経由で受任した所属弁護士の負担金、照会請求手数料などを主な収入源としている。

会長の補助機関として50を超える委員会が存在し、所属する弁護士がそれぞれの委員会で会務の一環として対象分野に関する活動を行っている。

［source：］東京弁護士会 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E5%BC%81%E8%AD%B7%E5%A3%AB%E4%BC%9A
```

　改めて確認のため調べたのですが、第一東京三弁護士会というのは、ほとんど見かけていないような気がしました。たとえば、小倉秀夫弁護士は東京弁護士会、深澤諭史弁護士は第二東京弁護士会の所属という情報はたびたび見かけてきました。

　今日だと思いますが、それも深澤諭史弁護士のタイムラインがきっかけで、住所が横浜で第二東京弁護士会という弁護士のことを見かけていました。

```
無免許で死亡事故を起こした男にうその供述をするよう指示し、車を貸した所有者をかくまったとして、横浜地検は１５日、犯人隠避教唆の疑いで、第二東京弁護士会に所属する弁護士の男（３２）＝横浜市神奈川区＝を逮捕した。認否は明らかにしていない。

　地検は同日、同容疑で車の所有者の男（２６）と、犯人隠避の疑いで事故を起こした男（２２）も逮捕した。

［source：］うその供述をするよう指示、弁護士を逮捕　横浜地検（カナロコ by 神奈川新聞） - Yahoo!ニュース https://headlines.yahoo.co.jp/hl?a=20181016-00030196-kana-l14
```

　これも確認のため調べたところ、犯人隠避教唆となっていました。教唆犯というのも珍しのではないかと思ったのですが、他の報道では気づかずにいました。

　深澤諭史弁護士については、弁護士として人として疑問に感じるところの大きな存在感があるのですが、それを私は弁護士業界や司法制度に波及する実態の根本的な問題性として捉え、記録とともにご紹介をしております。

　タイムラインで見る深澤諭史弁護士のツイートの多くは、リツイートの数も少なく、それだけ影響力も少なく、あるいは閲覧者も少ないのかと考えてきましたが、会務など弁護士会での活動というのも多く見かけ、また、著書もいくつか出しているという活動性が顕著です。

　社会の鑑という言葉がありますが、そのような深澤諭史弁護士の活動をひっくるめて、司法的救済及び石川県警察に再捜査を求める立場上、弁護士会、弁護士業界の現実、実態の反映として到底看過しうるものではないと考えています。
*** （・∀・）なおクオリティフィルター機能で，通知されず，読まれていない事に気が付いてるかは不明。
    :LOGBOOK:
    CLOCK: [2018-10-16 火 17:08]--[2018-10-16 火 17:36] =>  0:28
    CLOCK: [2018-10-16 火 12:55]--[2018-10-16 火 14:48] =>  1:53
    :END:

▶ ツイート％fukazawas（深澤諭史）％2018/10/16 11:21％ https://twitter.com/fukazawas/status/1052021640777723904
&twitter(1052021640777723904){theme:light}
> たまに，変なリプライを見かけて，その人のタイムラインを見に行くと，ほとんど攻撃的なリプライだけで埋め尽くされ，自分単独のツイートがない人がほとんどなんだけれど，あれ何が楽しいんだろう。
> （・∀・）なおクオリティフィルター機能で，通知されず，読まれていない事に気が付いてるかは不明。  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 12:57／2018-10-16 11:58 URL： https://twitter.com/kk_hirono/status/1052045748789899265 https://twitter.com/s_hirono/status/1052031027802038272
&twitter(1052045748789899265){theme:light}
> 2018-10-16-115438_深澤諭史（@fukazawas）：たまに，変なリプライを見かけて，その人のタイムラインを見に行くと，ほとんど攻撃的なリプライだけで埋め尽く.jpg https://t.co/G7jnpbbkHz
◁◁◁

　時刻は、13時34分です。昼食もまだでどうしょうかと思案中なのですが、テレビでバイキングをみています。今日も愛媛ご当地アイドル自殺関連の特集で、そのあとの今は「尾畠さんVS出版社・・・”初の著書”は違反！？」という見出しでやっています。

　さきほどまで余り見かけていない別の弁護士だったのですが、清原博弁護士が出て解説をしています。「パブリシティ権の侵害」という説明です。テロップには「損害賠償の額も跳ね上がる」などと出ていましたが、タイプしているタイミングで消えてしまいました。

　その前に見ていた深澤諭史弁護士のタイムラインでは、さきほどのツイートがさっそくのご本人のリツイートとして流れていました。ツイートの表示はリツイートが2件、いいねが4件のようです。2時間前のツイートととして表示されています。

　スクリーンショットの方も記録しています。不思議に思える現象なのですが、数日前は実名などの同業者の弁護士からもリツイートされたツイートが散見されたので、疎遠にされているというわけでもなさそうです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 13:44／2018-10-16 13:34 URL： https://twitter.com/kk_hirono/status/1052057795464314880 https://twitter.com/s_hirono/status/1052055076364120064
&twitter(1052057795464314880){theme:light}
> 2018-10-16-132801_深澤諭史（@fukazawas）：いじめの第三者調査委員会について-弁護士深澤諭史のブログ.jpg https://t.co/EtRoSIjLcN
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 13:45／2018-10-16 13:34 URL： https://twitter.com/kk_hirono/status/1052057810232520705 https://twitter.com/s_hirono/status/1052055107620065281
&twitter(1052057810232520705){theme:light}
> 2018-10-16-133122_深澤諭史（@fukazawas）：たまに，変なリプライを見かけて，その人のタイムラインを見に行くと，ほとんど攻撃的なリプライだけで埋め尽く.jpg https://t.co/Hl2E1QnefV
◁◁◁

　次は、スクリーンショットに映り込ませたツイートにもなりますが、そのツイートを見ている時に、２つ下のものとしてスクリーンショットの対象としたツイートを見かけました。

　深澤諭史弁護士のことで書いておきたかったことの1つに、日弁連でのシンポジウムで講演を行ったという事実があって、複数のブースで講演があったそうですが、見かけた情報によると、同じブースではもう一名の弁護士の講演があって、それが弁護士ドットコムの創業者だったということです。

　弁護士ドットコムの創業者弁護士と肩を並べたというかたちにもなるかと思いましたが、その後も弁護士ドットコムで深澤諭史弁護士の記事が優先的に表示される現象を目にしたことがありました。私の目から見るとそれがとても不思議な現象だったわけですが、それが現実であり実態であることは明白です。

```
TBSでは10月15日（月）から『1番だけが知っている』がスタートする（毎週月曜よる10時～11時07分 ※初回と10月22日の放送はよる9時からの2時間スペシャル）。
世の中のあらゆる業界に存在する“その道のNo.1”から、「1番だけが知っている」というとっておきの物語や驚愕の人物を聞き出し、その類まれなエピソードを紹介するこの番組。過去5回の特番では、「ビートたけしが唯一勝てないと思った芸人」や「北村晴男弁護士が魂震えたリアル“99.9”裁判」などを紹介し、その内容が放送終了後にWEBニュースで取り上げられるなど大きな反響を呼んだ。
そしてこのたび、ついに10月からレギュラー化が決定！ MCは特番に引き続き坂上忍と森泉が務める。また、レギュラー化にあたり内容もパワーアップ！ 芸能界やスポーツ界だけでなく、医療業界や学校業界など、さまざまな分野のNo.1から、1番だからこそ知る貴重なエピソードを聞き出していく。
毎週月曜の夜、次々と登場する驚愕の“No.1エピソード”に、あなたの魂が震える…！

［source：］1番だけが知っている｜TBSテレビ https://www.tbs.co.jp/program/ichiban_20181015.html
```

　これも先ほど深澤諭史弁護士のタイムラインから知ったのですが、北陸中日新聞のテレビ欄をみたところMRO北陸放送でも昨夜放送があったようです。きっかけは野田隼人弁護士の日野町事件に関するツイートでした。リツイートとして見かけたものです。

　締めくくろうと考えていたのですが、クオリティフィルター機能について全く触れていなかったことに気が付きました。今日は15時前に用事で出掛ける予定だったのですが、少し前に予定が変わったので、そのまま家にいます。外では雨が降っている様子もありました。

　クオリティフィルター機能について調べたのですが、正式なTwitterの機能だったようです。ただ、調べて見たページでは、スマホだけの機能でiphoneとAndroidに対応と書いてありました。実際にiphoneの方では設定の画面の操作で確認をしてみました。

　ミュートとブロックが中心とも思いましたが、通知ではフォロー以外とかアイコン画像なしとか細かい設定が出来るようでした。ブロックの場合はブロックされていることがすぐにわかるのですが、ミュートというのは確認が出来ないものと考えています。調べてはいませんが。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-16 17:18／2018-10-16 14:56 URL： https://twitter.com/kk_hirono/status/1052111630014734336 https://twitter.com/hirono_hideki/status/1052075882796339200
&twitter(1052111630014734336){theme:light}
> 【Twitter】『クオリティーフィルター』機能の使い方 – 品質が低いと判断されたツイートは自動で通知オフに ≫ 使い方・方法まとめサイト - usedoor https://t.co/MkDJT1NuMr
◁◁◁

　クオリティというのは品質のことだと思います。高品質を意味するとも思いますが、あえて調べて確認はしていません。フィルターも絞り込みのことではないかという感覚です。あるいは抽出なのかもしれません。

　深澤諭史弁護士は自身に対して批判的なツイートをそのまま中傷と決めているようです。その一方で、都合のよい情報のみを探し回るとか、都合の悪い情報には見向きもしないなどと、一般的な依頼者となりうる人を揶揄するようなツイートを行ってきました。素人も同義かもしれません。
** まとめ記事
*** 弁護士クオリティについて参考とする、「都合」というキーワード

［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”都合”／深澤諭史（@fukazawas）の検索（2012-11-21〜2018-10-10／2018年10月16日20時36分の記録207件） http://hirono2014sk.blogspot.com/2018/10/regexpfukazawas2012-11-212018-10.html

　さきほど作成したものです。過去に作成したものもあると思うので、数が増えているかなど比較を見ておきたいと思います。そのあと、上記のまとめ記事から得意性の高いものを選択し、いくつかピックアップをしてご紹介をしておきたいと思います。

```
[9990]  % dp -l |grep 都合|grep fukazawas|sed 's/$/\n/'
2017年10月09日14時54分の登録： ％@fukazawas　深澤諭史％「同じ法律問題で同じ立場の人々」が「情報交換」しているのをたまに見ますが，「自分たちに都合のよい解釈という名の妄想を披露しあって，落とし穴に集団行進をしている」状態に http://hirono2014sk.blogspot.com/2017/10/fukazawas_22.html

2018年04月20日06時29分の登録： ＼深澤諭史　@fukazawas＼『議論が沸騰すると現れる「都合のいい法律情報」 』という言葉は，本当に，言い得て妙ですね。 法律用語を使うとき，その前に，少し考えてみて http://hirono2014sk.blogspot.com/2018/04/fukazawas_20.html

2018年04月20日22時59分の登録： ＼深澤諭史　@fukazawas＼『議論が沸騰すると現れる「都合のいい法律情報」 』という言葉は，本当に，言い得て妙ですね。 法律用語を使うとき，その前に，少し考えてみて http://hirono2014sk.blogspot.com/2018/04/fukazawas_36.html

2018年05月17日10時28分の登録： ＼深澤諭史　@fukazawas＼「とりあえず，都合のいい法律情報だけあつめて，放置しておけば，そのうち何とかなる」\nは，最悪の選択であるといえます。 http://hirono2014sk.blogspot.com/2018/05/fukazawas_17.html

2018年10月16日20時36分の登録： REGEXP：”都合”／深澤諭史（@fukazawas）の検索（2012-11-21〜2018-10-10／2018年10月16日20時36分の記録207件） http://hirono2014sk.blogspot.com/2018/10/regexpfukazawas2012-11-212018-10.html
```

　「都合」をキーワードに前にもまとめ記事を作成していると思っていたのですが、データベースの検索にはなかったようです。正規表現も使っていない漢字2文字の検索なので手違いがあるとも考えられないのですが、結果は結果です。私の思い違いの可能性があります。

▶（009／207） TW fukazawas（深澤諭史） 日時： 2013-09-19 10:25:00 +0900 URL： https://twitter.com/fukazawas/status/380502781158637568
{% tweet 380502781158637568 %}
> ネットで法律情報が調べられることには，メリットもありまして，基本について説明を簡略化できる場合もあります（注意は必要） \n それ以上のデメリットは「まことしやかな自分に都合の良いデマ」に固執する人が増えていまして…。 \n 今，そういったものにも警鐘を鳴らす一般の方向けの本を書いています。

　上記のツイート本文は、文字数オーバーで末尾の文字数をいくつか削りました。その部分は「そういったものにも警鐘を鳴らす一般の方向けの本を書いています。」となっています。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)への投稿です。

▶（010／207） TW fukazawas（深澤諭史） 日時： 2014-03-01 10:02:00 +0900 URL： https://twitter.com/fukazawas/status/439566236427374592
{% tweet 439566236427374592 %}
> 「かけがえのない人生を生きる人々の喜びや悲しみに対して深く共感しうる豊かな人間性の涵養、向上を図る」教育機関の先生が仰ることはおもしろいですね(･∀･) RT @worldjourney 自分らの都合で若者達の将来を社会実験に使うクズ

　上記の深澤諭史弁護士のツイートは、最近は小倉秀夫弁護士以外にほとんど見かけなくなっている、いわゆる非公式RTの引用部分に「都合」というキーワードが含まれていました。

▶（011／207） TW fukazawas（深澤諭史） 日時： 2014-03-05 15:12:00 +0900 URL： https://twitter.com/fukazawas/status/441093999332323328
{% tweet 441093999332323328 %}
> 刑事事件を取り扱っていると、しばしば、自分の都合よく空想を巡らせることが出来る人間の才能にしばしば感心する。

　被疑者を愚弄しているように見えるのですが、深澤諭史弁護士らしさのツイートです。余り見覚えのないツイートとも思ったのですが、投稿日時が2014年3月5日となっていて、あるいは私が深澤諭史弁護士のアカウントを知らない時期で、その後の検索からデータベースに登録したものかもしれません。

　私の記憶に残っているのは、私が深澤諭史弁護士のTwitterアカウントに注目した時点で、フォロワー数が1千を少し切れる900件台だったことです。それが暫く続いていましたが、その時点で、共著の紹介はされていたように思います。本も出しているのに少ないので、不思議に感じていました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 21:15／2018-10-16 21:13 URL： https://twitter.com/kk_hirono/status/1052171214842552320 https://twitter.com/s_hirono/status/1052170575454429184
&twitter(1052171214842552320){theme:light}
> 2014-06-19-102421_％　grep　’,”RT　@fukazawas：’　hirono_hideki140619。csv.jpg https://t.co/kHBY1YiLPF
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 21:15／2018-10-16 21:13 URL： https://twitter.com/kk_hirono/status/1052171229652602881 https://twitter.com/s_hirono/status/1052170543498051584
&twitter(1052171229652602881){theme:light}
> 2014-06-19-100059_@fukazawas　@Hideo_Ogura　ツイートを使わせていただきました。問題ありましたら対応しますのでご連絡くだ.jpg https://t.co/HeSYY6ygsi
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 21:15／2018-10-16 21:12 URL： https://twitter.com/kk_hirono/status/1052171247914643456 https://twitter.com/s_hirono/status/1052170512212713472
&twitter(1052171247914643456){theme:light}
> 2014-06-19-095927_@fukazawas　貧乏だと厄介者扱いで終わりにされそうですね。報酬に差異を出せば、見解も大逆転するのかもしれないです泥.jpg https://t.co/Yv3WE1zFkf
◁◁◁

　現在、私のパソコンにあるスクリーンショットの画像ファイルの中で、最も古い時期のものを探し出し３つ非常上告-最高検察庁御中_ツイッター（@s_hirono）に投稿しました。前記のものです。具体的には2014年6月のものです。

　この時点で深澤諭史弁護士に注目していたことが確認できましたが、深澤諭史弁護士のツイートのスクリーンショットというのはありませんでした。次の時期のものもTwitterに記録しておきます。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 21:21／2018-10-16 21:20 URL： https://twitter.com/kk_hirono/status/1052172626712354819 https://twitter.com/s_hirono/status/1052172541295452160
&twitter(1052172626712354819){theme:light}
> 2014-07-26-101617_深澤諭史　（fukazawas）さんはTwitterを使っています.jpg https://t.co/eQzsvSIEOd
◁◁◁

　上記のスクリーンショットをみると、ツイート数が17001件、フォロワー数が974件となっています。当時はまだプロフィールにTwitterの開始時期が表示されていなかったようですが、2014年7月26日の時点でツイート数が1万7千に達していたというのはバランス的に意外な発見です。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-10-16 21:27／2018-10-16 21:26 URL： https://twitter.com/kk_hirono/status/1052174108681678848 https://twitter.com/s_hirono/status/1052174046287212544
&twitter(1052174108681678848){theme:light}
> 2014-12-12-101434_ブロックされているため、@fukazawasさんをフォローしたり、@fukazawasさんのツイートを見ることができません.jpg https://t.co/ly395W8lBP
◁◁◁

　上記のスクリーンショットが、深澤諭史弁護士にブロックされたのを最初に記録したものだと思われます。モトケンこと矢部善朗弁護士（京都弁護士会）にはブロックを解除された時期もあったのですが、深澤諭史弁護士の場合、そういうのは一度も確認していません。

▶（012／207） TW fukazawas（深澤諭史） 日時： 2014-03-15 10:54:00 +0900 URL： https://twitter.com/fukazawas/status/444652764316983296
{% tweet 444652764316983296 %}
> 何人も自分に都合のよいことしかいわない弁護士をさがし続けて，ハシゴするひとがいますが。 \n \n そういう人は，大吉が出るまでおみくじを引き続けるのですかね。 \n \n まあ，セカンドオピニオンを求めるのは否定しませんが。

　おみくじといえば神社ですが、このツイートのことはすっかり忘れていたか、自動処理でデータベースに登録されたという可能性もあるかもしれません。スクリーンショットがあれば、少なくともその時点で目にしていたということが確認できるのですが、今はそれも心掛けて記録しています。

▶（013／207） TW fukazawas（深澤諭史） 日時： 2014-03-20 13:46:00 +0900 URL： https://twitter.com/fukazawas/status/446508140230475777
{% tweet 446508140230475777 %}
> 法テラス相手にストライキをやって，民事法律扶助はなくなり，国選も「国選を競うように取っているような老人たち」だけが担当するというのもありかも。 \n \n 不都合があるけれど，これこそが法の光。平成の司法改革が目指した世界かも。

　上記も「弁護士鉄道」の歴史、資料を感じさせる深澤諭史弁護士のツイートの記録です。基本がプログラムを使った自動処理ですが、これほどの成果があったとは、少々驚いています。

▶（014／207） TW fukazawas（深澤諭史） 日時： 2014-08-04 12:50:00 +0900 URL： https://twitter.com/fukazawas/status/496141197983764482
{% tweet 496141197983764482 %}
> 平成の司法改革の大誤算は，制度設計者が「自分たち以外の当事者が，自分たちの都合の良い通りに動いてくれる」と何の根拠もなく妄想したことと， \n \n そんな人々を設計に関与させてしまったこと，だろう。

▶（015／207） TW fukazawas（深澤諭史） 日時： 2014-08-05 12:13:00 +0900 URL： https://twitter.com/fukazawas/status/496494264235216896
{% tweet 496494264235216896 %}
> ある一定の割合で \n 「都合の悪いこと」「意に沿わないこと」が起きても， \n 「ほっておけば何とかなる」と \n 根拠無く思い込んでいる人々というのはいる。 \n こういう人には，なかなか教えても，その通りに動いてくれない。 \n \n ＲＴ

　そのまま弁護士にあてはまる深澤諭史弁護士の上記のツイートですが、そういった自覚がまったくないところも弁護士らしく、また、社会的な有害性、危険性も看過できないものとして広く、普く周知されたいと思います。警察、検察、裁判所、弁護士、一般の情報共有として。

▶（018／207） TW fukazawas（深澤諭史） 日時： 2014-09-23 13:36:00 +0900 URL： https://twitter.com/fukazawas/status/514271999057596416
{% tweet 514271999057596416 %}
> 「難しい決断しないといけないとき」と「不都合な事実が明らかになったとき」には，連絡先のパソコンや携帯は故障したり，風邪を引いて寝込んだりする。 \n \n #弁護士あるある

　#弁護士あるある というハッシュタグがあります。2014年9月23日の時点で日本語のハッシュタグがTwitterで使えるようになっていたのだと確認できました。これも深澤諭史弁護士らしいツイートですが、確率が逆転している弁護士らしい現象のように思えます。

　具体的には日曜ドラマ劇場などにもなっていた日曜劇場『99.9－刑事専門弁護士－』の数値ですが、逆というのは00.1％の確率だと思います。実際の体験談に裏打ちされた可能性は否定し難いですが、100回に1回あるいは1000回に1回のことを、あるあるとしている点です。

▶（019／207） TW fukazawas（深澤諭史） 日時： 2014-09-25 12:18:00 +0900 URL： https://twitter.com/fukazawas/status/514977276522266624
{% tweet 514977276522266624 %}
> ＞ＲＴ \n スライム先生のいうとおり，なんで，重罪に限定して裁判員を導入するかわからん。 \n \n 重罪なら興味を持って参加してもらえるから？ \n 重罪の被告人なら，裁判員の都合で長期拘束されても文句を言いづらいだろうから？

　今のところ、深澤諭史弁護士が裁判員裁判を担当したというツイート、話は見ておりませんが、裁判員制度に対しても否定的な独自の考えをお持ちのことは、これまでツイートで散見してきました。「裁判員の都合」というのも独自的な特異性を感じるものです。愚弄気味です。

▶（020／207） TW fukazawas（深澤諭史） 日時： 2014-09-27 12:34:00 +0900 URL： https://twitter.com/fukazawas/status/515705908144259072
{% tweet 515705908144259072 %}
> ＞ＲＴ \n これは，弁護士としても実感している。 \n 相談に来る人の中には，ネットの都合良い情報を切り貼りしたり，法律相談をハシゴして，これまた自分に都合のいいことだけを話して，都合のいいところだけを聞いて \n 「●●と書いてあった！いわれた！●●すれば間違いない！」 \n と主張される方もいる。

　上記のツイートは、一時的に改行を入れて２つのツイートととして告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)に投稿しました。最近見かけたのとほとんど同じなのですが、2014年9月の時点から少しも変わっていないようです。

　2014年といえば、弁護士業界を取り巻く環境もずいぶんと変わったと思いますし、深刻に考えさせられる重大事件もいくつかありました。この先も似たような内容の深澤諭史弁護士のツイートが登場すると思いますが、その辺りも踏まえて、弁護士業界の資質、問題性を考えて頂きたいです。

▶（021／207） TW fukazawas（深澤諭史） 日時： 2014-11-03 12:32:00 +0900 URL： https://twitter.com/fukazawas/status/529113938726645760
{% tweet 529113938726645760 %}
> 都合の悪い主張をされたら、とりあえず、数百万円単位の賠償請求をすれば、黙らせられるとおもっている。 \n \n #労働事件で労働者によく訴えられる使用者あるある

　「都合」という単純なキーワードで、ここまで濃密な問題性を孕むツイートが連発されるとは想定外でした。まだ（021／207）という段階なので、先が思いやられますが、それだけ大きな収穫とも指摘したいです。

▶（024／207） TW fukazawas（深澤諭史） 日時： 2015-04-10 10:35:00 +0900 URL： https://twitter.com/fukazawas/status/586341600348909568
{% tweet 586341600348909568 %}
> 需用者にとってだけ，一方的に都合の良い自由競争を夢想したのがそもそもの間違い。

　上記の深澤諭史弁護士のツイートは、司法制度改革への不満、皮肉なのだと思います。需用者という言葉は見かけないと思ったのですが、LinuxのMOZCの日本語変換では「需要者」という候補しか出ませんでした。逆の立場が提供者で、それが弁護士のことなのだと思われます。

▶（027／207） TW fukazawas（深澤諭史） 日時： 2015-06-17 13:28:00 +0900 URL： https://twitter.com/fukazawas/status/611027657224925184
{% tweet 611027657224925184 %}
> 都合のいいときだけ医師をもちだす方々、お元気ですか？ \n (･∀･) \n https://t.co/0dV9HH3MIc

　医療や医師、裁判や弁護士を社会的に等価値という前提条件としてきたのも深澤諭史弁護士や小倉秀夫弁護士のツイートに見られてきた弁護士脳の特徴です。より深刻と匂わせたり、ストーカー犯罪などを安直に医学的治療の必要性と結びつけるのも深澤諭史弁護士の特徴です。頗る表層的で単純な思考です。

　最近では見かけていませんが、小倉秀夫弁護士などは刑事裁判の国選弁護と医療保険制度を等価なものとして、同じような運用をすべきという意見表明をしていました。数々の重大刑事事件の報道が真っ盛りの時期でも、全く無関係なツイートに没頭し、精査検討しているとは到底思えませんでした。

▶（028／207） TW fukazawas（深澤諭史） 日時： 2015-06-22 11:00:00 +0900 URL： https://twitter.com/fukazawas/status/612802225925033985
{% tweet 612802225925033985 %}
> 事実認定や予測に，都合の良い仮定を差し込んではいけないんですよ・・・。 \n これは，司法研修所で事実認定の基礎として徹底的に学んだ！ \n (･∀･)ﾄﾞﾔｧ \n https://t.co/cxh7UTfnfS

　司法修習はずいぶん前から2年あったものが1年となっているはずです。深澤諭史弁護士が法科大学院（ロースクール）の出身ということははっきりしており、新司法試験の合格者だとも思われます。

　私自身、新司法試験と旧司法試験が混在した時期が数年間あったと、半年ほど前でしようか最近になって知ったのですが、深澤諭史弁護士の修習時期には旧司法試験がなくなっていたか、ごく少数の割合となっていたかと思われますし、本人も旧司法試験の合格とは表明していません。

　司法修習の期間がいつ頃、2年から1年になったのかはっきりした時期はわからず、それ以上に短縮の理由というのが、不思議と見かけないものです。予算の関係だと思われますが、それは貸与制の問題では大きな問題とされていました。

　1,2年前、時期ははっきり思い出せず、いちいち調べることもしませんが、その司法修習生の貸与制が見直されました。弁護士らの間では大きな話題としてツイートに見ていましたが、テレビで一切報道を見なかったのも、不思議な現象として印象的なものでした。

　時刻は10月17日11時07分になります。目が覚めたのは5時半ぐらいでしょうか、まだ外は真っ暗でした。二度寝をこころみたのですが寝付けず、しかたなく起きたときは6時を過ぎて外も明るくなっていました。

　特に関心のあるニュースや話題もなかったので、7時少し前から録画していたリーガルＶを視聴していました。その前に2回目の放送だった月9ドラマ『SUITS/スーツ』を再生していたのですが、終わりの方だけしか録画されていませんでした。テーブル越しに録音を突きつけた場面でした。

　また、いずれ取り上げたいと思いますが、どちらのドラマも佐藤大和弁護士が監修などをしているというツイートを見かけていました。どちらかは知っていたように思いますが、話題の弁護士ドラマの２つというのは、知らなかったようにも思います。次のツイートです。

▶ ツイート％yamato_lawyer（レイ法律事務所代表弁護士佐藤大和）％2018/10/15 11:37％ https://twitter.com/yamato_lawyer/status/1051663234644684800
&twitter(1051663234644684800){theme:light}
> 今期、テレ朝「リーガルＶ」（１５・０％）、フジ「ＳＵＩＴＳ」（１４・２％）と民放視聴率１位、２位。２つとも自分と弊所の弁護士たちで監修し、両作品とも現場監修もしているため、この結果は法律監修をしている弁護士としてすごく嬉しい。今夜は夜９時からフジテレビ「ＳＵＩＴＳ」をぜひご覧に！  
▶

　佐藤大和弁護士のTwitterのタイムラインで上記のツイートを捜したのですが、思ったよりずいぶんと遡ったので、少し不安になりました。削除するような内容のツイートではないと思っていましたが、見つからないとそういう考えも頭をもたげます。

　深澤諭史弁護士ほどではないですが、佐藤大和弁護士のツイートもリツイートやいいねの数が少なめなので前から気になっていました。上記のツイートも75件というリツイート数です。逆に見るたびにリツイートの数が多く千件以上が普通にあると思うのが山口貴士弁護士です。

　山口貴士弁護士は、大注目された証人喚問で森友学園の籠池氏の保佐人としてテレビに出ていましたが、名前などは出ていなかったように思いますし、顔は見ていても知らない人がほとんどかと思われます。

　テレビに出ている弁護士前半にもいえることですが、Twitterの検索をしても、余り反応というものを見かけることがありません。私も以前はそうだったように思いますが、なんとなくテレビを見ながら聞き流すだけという感じであったように思います。

　さて、深澤諭史弁護士の「都合」をキーワードにしたツイートのご紹介を再開したいところですが、内容を読むと耐え難く掲載し、あるいは言及したくなるものばかりなので、思い切って今年つまり2018年のツイートまで飛ばしたいと思います。2015年6月22日から飛ばすことになります。

▶（166／207） RT fukazawas（深澤諭史）｜jikapan（自家製パンチェッタ） 日時：2018-01-10 18:28:00 +0900／2018-01-10 13:26:00 +0900 URL： https://twitter.com/fukazawas/status/951022899338526720 https://twitter.com/jikapan/status/950946895874088960
{% tweet 951022899338526720 %}
> 裁判官について「職業上旧姓を使うなんて許さん」と吹き上がる方は，社会で旧姓使用が広まるなら事実上の不都合ないでしょ？という，平成２７年の夫婦同姓合憲判決を攻撃してることに気付いてるんだろうか…。その攻撃が「やはり不都合だから戸籍上で別姓を許すべき」という援護射撃になってる…。

　2018年の1件目はリツイートでした。内容はともかく「jikapan（自家製パンチェッタ）」というアカウントは、ダイオウグソクムシを使っていて、私が珠洲の木ノ浦海岸の近くから釣ってきた小鯛にいたタイノエを初めて知った時期とアカウントのツイートに注目した時期が重なっていました。

▶（168／207） TW fukazawas（深澤諭史） 日時： 2018-02-12 10:31:00 +0900 URL： https://twitter.com/fukazawas/status/962861738742837250
{% tweet 962861738742837250 %}
> 「自分と反対の意見の人が圧倒的に多数だけれども，自分の意見に賛同する人が実は沢山いて，その人達は，ただ黙っているだけなんだ。その黙っている人が声を上げさえすれば，自分と同じ意見が多数派になるに違いない」 \n って都合良く想像できる現象に，そろそろ名前を付けたい \n （・∀・）

▶（171／207） RT fukazawas（深澤諭史）｜poorpartner（三毛猫B【行政法クラ】） 日時：2018-02-24 13:11:00 +0900／2018-02-24 13:09:00 +0900 URL： https://twitter.com/fukazawas/status/967250670817501184 https://twitter.com/poorpartner/status/967250029663547392
{% tweet 967250670817501184 %}
> 安くやる弁護士はいい弁護士か？ \n \n 消費者からすれば都合のいい弁護士かもしれないが、 \n \n ホントに、いいかどうか？ \n \n やることやるには時間がかかる。 \n \n 手を抜くか \n 手弁当でやってるか、 \n \n どっちだろうか？ \n \n 消費者は考えるしかないかと。 \n \n 安かろう悪かろうでいいなら、それはあり。

　ここ数日、深澤諭史弁護士のツイートの頻度というか数がかなり増えていると感じています。モトケンこと矢部善朗弁護士（京都弁護士会）や小倉秀夫弁護士の方は減少傾向とも思いますが、小倉秀夫弁護士はたびたびツイートの数が多すぎるので、まともに仕事をしているのかと指摘を受けていました。

　深澤諭史弁護士のツイートはリツイートも多いので、スマホでリツイートをするのはパソコンより手間いらずかとも思いますが、仕事に対する集中力が持続できるものなのかという疑問もあります。割に合わないので手を抜くかも、というような弁護士のツイートは多く見かけてきました。

　さきほど書くのを忘れていましたが、ネットでみつけた先日の日野町事件を取り上げた坂上忍さんの番組の動画を視聴していました。死後の再審が認められたということでも司法では歴史的な出来事だったのだと思いますが、当日のニュース以外に報道を見ることはなく、関心も高そうには思えずにいました。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/10/17 09:57％ https://twitter.com/hirono_hideki/status/1052362841892642816
&twitter(1052362841892642816){theme:light}
> 1番だけが知っている 10月15日 | バラエティ動画視聴 Tvkko https://t.co/gX27rItwi0  
▶

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/10/17 10:40％ https://twitter.com/hirono_hideki/status/1052373795648860160
&twitter(1052373795648860160){theme:light}
> 1番だけが知っている 10月15日 | バラエティ動画視聴 Tvkko https://t.co/gX27rItwi0
> 芸人・明石家さんまが初めて語った新事実!たけし独立騒動と引退勧告▽鈴木亮平が死ぬまでに行きたい奇跡の世界遺産ベスト3!▽北村弁護士が震えた大逆転裁判…吉田羊が涙  
▶

　上記の9時57分のツイートは視聴開始後少ししてから、2つ目の10時40分のツイートは視聴終了直後のツイートでした。当初は余り意識していなかったものの放送時間の計測に近いものとなっているかと思います。途中にCMが入り、その数が多かったり、不自然に終わるCMもありました。

　録画の開始も日野町事件を取り上げた最初からではなかったようです。番組の概要はネットで捜した情報などを見ていましたが、4、５つぐらいの話題があって、2時間番組のようだったので、日野町事件に割り当てられる時間はもっと短いものと思っていました。他にも色々と発見の多い番組でした。

　一方的に警察を悪者にしすぎているのではないかという疑問も感じながら見ていましたが、録画で見ていると10年から20年ほど前に制作された番組を当時の時代背景や価値観とともに見ているような錯覚に陥りました。それがSHOWというものなのかもしれません。

　日野町事件についても前から取り上げておきたかったのですが、再審開始の後も世間の反応が小さすぎたので、話題性としても情報を共有するのに向いているのかという疑問もありました。同じ滋賀県では、別の再審開始の事件もありましたが、あれもニュースで見るだけの報道でした。

　情報番組ごとの扱いにはかねてより疑問が強かったのですが、昨日は特にそれを強く感じました。それはネットで見ていた犯人隠避教唆の弁護士逮捕のニュースで、テレビで取り上げているのを見たのは朝の情報番組とくダネ、だけだったと思います。ニュースでも見なかったと思います。

▶（173／207） RT fukazawas（深澤諭史）｜k_sawmen（泥濘大魔王ジャイホー！バーフバリ！） 日時：2018-03-08 17:39:00 +0900／2018-03-08 17:29:00 +0900 URL： https://twitter.com/fukazawas/status/971666702432837632 https://twitter.com/k_sawmen/status/971664224052183040
{% tweet 971666702432837632 %}
> よくもまぁこんなに都合良く歴史を創作できますねぇ……しかも表現の自由まで特攻で守られたことにしちゃうし笑　明治憲法と日本国憲法の違いも、一ミリも知らないんでしょうかね https://t.co/hSbxWi9L6h

　上記はリツイートですが、深澤諭史弁護士のツイートには、歴史についても特異な断定性を感じています。それこそ自己都合の解釈で単細胞的なものを感じるのですが、それが単純明確に筋道を立てるという弁護士としての資質、必要な要素なのかもしれません。

　深澤諭史弁護士の歴史認識として代表的なキーワードが「インパール作戦」と「はだしのゲンの町内会長」です。まとめ記事も作成しているかと思いますが、ここでは取り扱わないこととしておきます。

▶（181／207） TW fukazawas（深澤諭史） 日時： 2018-04-08 11:03:00 +0900 URL： https://twitter.com/fukazawas/status/982801047524540416
{% tweet 982801047524540416 %}
> もういい加減，不都合な真実に気が付いた方がいいと思う。 \n 今の政府は，残業代ゼロは年収１０００万円超えだけではなくて，最低賃金労働者にも適用したくて適用したくたまらず， \n 時間ではなくて成果で評価というのは，真っ赤な大嘘，デマ，フェイクニュースの類だってことを・・・。 \n （・∀・；）

　長時間労働とか残業代についても強いこだわりを見せてきた深澤諭史弁護士なのですが、不思議なことに愛媛ご当地アイドル自殺の問題に関しては、テレビで運営会社の低賃金と多額の罰金性などブラック性が問題視されているのに、言及したツイートが見られていません。

　契約内容の異様性などテレビで繰り返し指摘されていますが、そういう会社側に一方的な都合の契約書というのも、以前は弁護士が関わっているという情報を見かけたように思います。もう何年も前のことなのではっきりとした情報は持ち合わせがないですが、そういうのも近年見かけないと思っていました。

▶（183／207） RT fukazawas（深澤諭史）｜haya_rt（鳩屋） 日時：2018-04-18 14:04:00 +0900／2018-04-18 08:25:00 +0900 URL： https://twitter.com/fukazawas/status/986470511570857984 https://twitter.com/haya_rt/status/986385251428519938
{% tweet 986470511570857984 %}
> ネトウヨの人たちって、権力者＝俺たちになってるんだよね。 \n 権力者から見たらネトウヨの君たちは都合よく動いてくれて、権力も簡単に制限できて、こんなに権力者から嬉しい層はいないと思うよ。

　この鳩屋というアカウントも匿名の弁護士かと思われます。これまでに何度かかなり気になる内容のツイートを見かけてきました。

```
[10017]  % dp -l |grep 鳩屋|sed 's/$/\n/'
2017年09月26日00時58分の登録： ＼鳩屋@ゴミ起案量産終了　@haya_rt＼教官は、弁護士倫理のギリギリを行くような者は誰からも信頼されないし、私のクラスからはそのような人は出て欲しくないとおっしゃっていましたね。 http://hirono2014sk.blogspot.com/2017/09/hayart.html

2017年10月15日09時20分の登録： ＼鳩屋@ゴミ起案量産終了　@haya_rt＼アディーレの就職説明会で消費者庁からの措置命令について、なんだかんだ我々は着手金無料でやってたから依頼者のためになってる的なトンデモ回答 http://hirono2014sk.blogspot.com/2017/10/hayart.html

2017年10月26日19時33分の登録： ＼鳩屋@ゴミ起案量産終了　@haya_rt＼なので71期になる人もこれまでと変わらずじ自由にツイッターやればええよね。\n導入でツイッターはやらない方がいいですみたいな http://hirono2014sk.blogspot.com/2017/10/hayart71.html

2017年10月26日19時37分の登録： ＼鳩屋@ゴミ起案量産終了　@haya_rt＼なお、当局が修習生のツイッターを監視していることは、70期の法クラが導入時に呼び出しを受けている事案があったので明らかです。 http://hirono2014sk.blogspot.com/2017/10/hayart70.html

2017年11月07日13時38分の登録： ＼鳩屋@ゴミ起案量産終了　@haya_rt＼組合員に法律相談を勧めるべきです。組合の不十分な支援で獲得できる権利が損なわれては元も子もないでしょ。 http://hirono2014sk.blogspot.com/2017/11/hayart.html

2017年11月07日15時34分の登録： ＼鳩屋@ゴミ起案量産終了　@haya_rt＼一般人がこれは風邪の症状だなと思ってても、重大な病気の症状だったりするわけで、それはやっぱり医者に診てもらわないとわからないの http://hirono2014sk.blogspot.com/2017/11/hayart_7.html

2017年11月07日15時53分の登録： TWEET：”2014-05-08 20:06〜2017-11-07 12:17”／鳩屋@ゴミ起案量産終了（@haya_rt）の検索（2017年11月07日15時53分の記録40件） http://hirono2014sk.blogspot.com/2017/11/tweet2014-05-08-20062017-11-07.html

2017年11月15日21時18分の登録： ＼鳩屋　@haya_rt＼研修所でそれやると懲戒になるから絶対やっちゃダメだよと神山先生からきつく言われてましたが...笑\n本当にやる人いるんですね(｀・ω・´) http://hirono2014sk.blogspot.com/2017/11/hayart_15.html

2017年11月24日20時57分の登録： ＼鳩屋　@haya_rt＼思わせぶり冒陳とはどんなものですか？ http://hirono2014sk.blogspot.com/2017/11/hayart_24.html

2017年12月04日09時16分の登録： ＼鳩屋@　@haya_rt＼法曹になろうとする者が守秘義務に過剰に萎縮して表現の自由を謳歌しないなんて。 http://hirono2014sk.blogspot.com/2017/12/hayart.html

2017年12月10日07時38分の登録： ＼鳩屋@　@haya_rt＼レジェンド弁護士の話を聞いてると徹底的にやることの大切さを痛感します。 徹底的にやった先に何か見えてくるのかもしれないですね。 http://hirono2014sk.blogspot.com/2017/12/hayart_10.html

2017年12月15日14時53分の登録： ＼鳩屋@１月まで無職　@haya_rt＼僕も刑事事件も被害者支援活動も両立して取り組もうと考えています。 http://hirono2014sk.blogspot.com/2017/12/hayart_15.html

2017年12月19日11時44分の登録： ＼鳩屋@１月まで無職　@haya_rt＼65から70までは無給で1年間過ごしたわけですよ。 71からは以前の給費制の半分くらいしか出ないわけですよ。結局足りない分は貸与で http://hirono2014sk.blogspot.com/2017/12/hayart65701-71.html

2018年01月19日15時49分の登録： ＼鳩屋　@haya_rt＼日弁連のページに「新規登録弁護士のための民事弁護実務ハンドブック」というのが載っているが、一文に驚愕した。\n「依頼者に宿題を出すという意味でも書 http://hirono2014sk.blogspot.com/2018/01/hayart.html

2018年02月18日20時47分の登録： ＼99.9-鳩屋-　@haya_rt＼全ての受け皿、それが書記官...。 書記官って窓口にくるクレームの受付もやらないとあかんし、本当に大変やな...。 http://hirono2014sk.blogspot.com/2018/02/999-hayart.html

2018年02月26日14時28分の登録： ＼99.9-鳩屋-　@haya_rt＼午前と午後カウントもなくなりますし、基準回数を超えると4000円しかもらえないのが3000円になるというのを刑弁委員会の報告で聞きま http://hirono2014sk.blogspot.com/2018/02/999-hayart40003000.html

2018年03月15日12時03分の登録： ＼99.9-鳩屋-　@haya_rt＼「これほど悪質クレームが増えているのは、憲法が個人主義を採用してるからで、道徳を憲法に明記するためにも憲法改正は必要！」というトンデ http://hirono2014sk.blogspot.com/2018/03/999-hayart.html

2018年03月29日21時24分の登録： ＼鳩屋　@haya_rt＼法テラスの新理事長が誰かはもういいから報酬振込はよ http://hirono2014sk.blogspot.com/2018/03/hayart.html

2018年03月29日21時27分の登録： ＼鳩屋　@haya_rt＼ロースクールって法律しか教えないけど、経営についても教えるべきなのでは？ http://hirono2014sk.blogspot.com/2018/03/hayart_29.html

2018年04月02日08時35分の登録： ＼鳩屋　@haya_rt＼医学部で司法試験も受かって、それで医療弁護士ってもっと他に選択肢あるんじゃ...って思う。 http://hirono2014sk.blogspot.com/2018/04/hayart.html

2018年04月13日22時56分の登録： ＼鳩屋　@haya_rt＼アクリル板の向こうの依頼者と世間話してたら、昨日と一昨日の新聞がガッツリ黒塗りされてたけどなんかあった？と聞かれた。 警察も自分らの不祥事は隠す http://hirono2014sk.blogspot.com/2018/04/hayart_13.html

2018年04月21日20時20分の登録： ＼鳩屋　@haya_rt＼離婚相談で本人と一緒に親もついてくるやつ、本人以上に親が自分の子供の配偶者がいかに酷い配偶者であるか言ってくるので大変。 気持ちは分かるけど今後 http://hirono2014sk.blogspot.com/2018/04/hayart_21.html

2018年04月24日08時18分の登録： ＃鳩屋　@haya_rt＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月24日08時17分 http://hirono2014sk.blogspot.com/2018/04/hayart201804240817.html

2018年04月25日04時57分の登録： ＼鳩屋　@haya_rt＼刑事弁護魂あるやつだけ国選やればええんやって、なんで刑事ではこうなるんでしょうねぇ。 活動に見合った対価が欲しいというだけなのに、なぜ国選ではそ http://hirono2014sk.blogspot.com/2018/04/hayart_25.html

2018年04月25日05時00分の登録： ＼鳩屋　@haya_rt＼だいたい刑事弁護人ってすごいことしてるのに，あれだけの評価しかされないってむかつかないのだろうか。 自分の仕事はそれだけの価値しかないと言われて http://hirono2014sk.blogspot.com/2018/04/hayart_46.html

2018年04月25日05時03分の登録： ＼鳩屋　@haya_rt＼被疑者国選でいえば，多数回接見になれば一回の接見が３０００円程度でしょ。 基準回数の接見と多数回接見とで接見内容が何が変わるというのだろうか。  http://hirono2014sk.blogspot.com/2018/04/hayart_14.html

2018年04月25日05時05分の登録： ＼鳩屋　@haya_rt＼診療報酬をめちゃくちゃ下げるけど，医師や病院は診療義務あるし，通常のレベルの治療を提供しなければならないとなったらそれはおかしいだろって思うでし http://hirono2014sk.blogspot.com/2018/04/hayart_75.html

2018年04月25日08時44分の登録： ＃鳩屋　@haya_rt＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月25日08時44分 http://hirono2014sk.blogspot.com/2018/04/hayart201804250844.html

2018年04月30日23時45分の登録： ＃鳩屋　@haya_rt＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月30日23時45分 http://hirono2014sk.blogspot.com/2018/04/hayart201804302345.html

2018年05月05日22時16分の登録： ＃鳩屋　@haya_rt＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月05日22時16分 http://hirono2014sk.blogspot.com/2018/05/hayart201805052216.html

2018年05月07日23時06分の登録： ＃鳩屋　@haya_rt＃のツイート／2018-05-01_1128〜2018-05-07_2231／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月07日23時06分 http://hirono2014sk.blogspot.com/2018/05/hayart2018-05-0111282018-05.html

2018年05月31日11時21分の登録： ＃鳩屋　@haya_rt＃のツイート／2018-05-26_1712〜2018-05-31_0922／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月31日11時21分 http://hirono2014sk.blogspot.com/2018/05/hayart2018-05-2617122018-05.html

2018年06月07日22時44分の登録： ＃鳩屋　@haya_rt＃のツイート／2018-06-01_0002〜2018-06-07_1837／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月07日22時44分 http://hirono2014sk.blogspot.com/2018/06/hayart2018-06-0100022018-06.html

2018年06月11日10時46分の登録： ＼鳩屋　@haya_rt＼神奈川弁護士会はどうやって被害者やその遺族と接触しているのか。 警察と情報共有する仕組みでも作ってるのかな http://hirono2014sk.blogspot.com/2018/06/hayart.html

2018年06月11日10時46分の登録： ＃鳩屋　@haya_rt＃のツイート／2018-06-04_1038〜2018-06-11_1041／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月11日10時46分 http://hirono2014sk.blogspot.com/2018/06/hayart2018-06-0410382018-06.html

2018年07月11日22時34分の登録： ＼鳩屋　@haya_rt＼本当に再審開始決定出てすごい。 これ撮ってて本当に感動したわ。 撮りながら泣いた。 http://hirono2014sk.blogspot.com/2018/07/hayart.html

2018年07月11日22時34分の登録： ＃鳩屋　@haya_rt＃のツイート／2018-07-07_1426〜2018-07-11_2234／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月11日22時34分 http://hirono2014sk.blogspot.com/2018/07/hayart2018-07-0714262018-07.html

2018年10月01日01時06分の登録： ＼鳩屋　@haya_rt＼アホなのかな。 そうやって冤罪生み出してきて真犯人も分からくなってしまって被害者遺族に更に被害を与えてきた歴史を何も知らんのか。 あなたが言って http://hirono2014sk.blogspot.com/2018/10/hayart.html

2018年10月01日01時06分の登録： ＃鳩屋　@haya_rt＃のツイート／2018-09-29_0145〜2018-10-01_0005／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月01日01時06分 http://hirono2014sk.blogspot.com/2018/10/hayart2018-09-2901452018-10.html

2018年10月14日09時38分の登録： ＼鳩屋　@haya_rt＼当局がわざわざしうしうせいのツイート監視してるみたいやけど、私が当局ですって人RTして http://hirono2014sk.blogspot.com/2018/10/hayartrt.html

2018年10月14日09時38分の登録： ＃鳩屋　@haya_rt＃のツイート／2018-10-07_1020〜2018-10-14_0824／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月14日09時38分 http://hirono2014sk.blogspot.com/2018/10/hayart2018-10-0710202018-10.html

```

　忘れた頃にみかける鳩屋という変わったプロフィールの名前のアカウントですが、記録の方は思った以上の数がありました。アイコンの写真の方も変わっていて特徴的でしたが、他のアカウントと記憶が混同したり、取り違えそうになることもあったかと思います。

　この鳩屋というアカウントについても最初に見たのは、宮崎の強姦ビデオ示談交渉の件に関連したツイートだったような印象となっているのですが、上記の記録をみても宮崎というのはないので、他のアカウントと取り違えている可能性はあるかと思います。

　1つ記憶にあるのは、福岡市の小説で大きな大賞をとったという作家の弁護士がいました。その後、脳梗塞で倒れ後遺症でリハビリしているとか、依頼者ともめて懲戒処分を受けたという情報も見かけていたのですが、すっかり見かけなくなっていて、今日ひさしぶりに思い出しました。

　間違った印象を与えてしまってもいけないので、正確な情報に近づくため少し調べてみます。

[link:] » "宮崎" from:haya_rt - Twitter検索 https://t.co/NSN7mU9DEE

[link:] » "示談" from:haya_rt - Twitter検索 https://t.co/SWbdBJHxCm

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜haya_rt（鳩屋） 日時：2018-10-17 12:40／2018-09-02 10:45 URL： https://twitter.com/kk_hirono/status/1052404074400768000 https://twitter.com/haya_rt/status/1036067515871322112
&twitter(1052404074400768000){theme:light}
> 示談交渉にあたっては、被害者側がどんな迷惑を被ったのかに耳を傾け共感することが大事やなぁ。 \n  ただ、謝って金払うだけじゃない。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜haya_rt（鳩屋） 日時：2018-10-17 12:41／2018-03-02 08:56 URL： https://twitter.com/kk_hirono/status/1052404248456192007 https://twitter.com/haya_rt/status/969360707228655618
&twitter(1052404248456192007){theme:light}
> 示談成立させて加算報酬3万って安くね？
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜haya_rt（鳩屋） 日時：2018-10-17 12:41／2014-10-07 00:27 URL： https://twitter.com/kk_hirono/status/1052404329213304833 https://twitter.com/haya_rt/status/519146902911066112
&twitter(1052404329213304833){theme:light}
> 死亡事故で示談が成立、交渉の末、不起訴に \n   \n  不起訴に！？
◁◁◁

[link:] » "交渉" from:haya_rt - Twitter検索 https://t.co/PzMpjkCX0I

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜haya_rt（鳩屋） 日時：2018-10-17 12:42／2018-04-15 12:24 URL： https://twitter.com/kk_hirono/status/1052404528425984001 https://twitter.com/haya_rt/status/985358080777961472
&twitter(1052404528425984001){theme:light}
> 刑事って短期間の間に労力めっちゃ必要やのに、某テラスの基準って安すぎやろほんま。 \n  しかも昔よりも弁護人の弁護内容も増えてるやろ。 \n  そういうとこ日弁連が交渉して予算ぶんどらせてこいよ。
◁◁◁

　やはり鳩屋というアカウントのもので、宮崎の強姦ビデオ示談交渉について関連している内容のツイートはありませんでした。

[link:] » 弁護士 作家 福岡 - Google 検索 https://t.co/8Ddt2lZuO7

```
法坂 一広
（ほうさか いっこう）
誕生	保坂晃一
1973年
福岡県福岡市
職業	作家
国籍	
ジャンル	推理小説
主な受賞歴	『このミステリーがすごい!』大賞大賞（2011年）
デビュー作	『弁護士探偵物語・天使の分け前』
 ウィキポータル 文学
テンプレートを表示
法坂 一広（ほうさか いっこう、1973年 - ）は日本の推理作家、弁護士。福岡県福岡市出身、在住。京都大学法学部卒業。福岡県弁護士会所属、登録番号は27232。


目次
1	略歴
2	作品
2.1	単行本
2.1.1	弁護士探偵物語シリーズ
2.1.2	その他
2.2	アンソロジー
3	不祥事
4	外部リンク
5	脚注
略歴［編集］
2011年、『弁護士探偵物語・天使の分け前』（応募時タイトル『エンジェルズ・シェア』）で第10回『このミステリーがすごい!』大賞の大賞を受賞。

［source：］法坂一広 - Wikipedia https://ja.wikipedia.org/wiki/%E6%B3%95%E5%9D%82%E4%B8%80%E5%BA%83
```

```
福岡県弁護士会は１２日、依頼者との間で契約書を作成せず、預かり金も返還しなかったとして、同会の保坂晃一弁護士（４４）を業務停止１カ月の懲戒処分とした。保坂弁護士は「法坂一広」のペンネームで作家としても活動。小説「懲戒弁護士」（刊行時「弁護士探偵物語　天使の分け前」）で、平成２３年に宝島社主催の「このミステリーがすごい！」大賞を受賞したこともある。

［source：］作家弁護士を懲戒処分　福岡、法坂一広氏 - 産経WEST https://www.sankei.com/west/news/171212/wst1712120090-n1.html
```

[link:] » 法坂一広（筆名）(@housaka1)さん | Twitter https://t.co/wIi0VOI37l

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 12:55／2018-10-16 00:32 URL： https://twitter.com/kk_hirono/status/1052407788977250305 https://twitter.com/housaka1/status/1051858267784146944
&twitter(1052407788977250305){theme:light}
> なかなか点の入らない時期に身に付けたスタイルなのかもしれないけれど、ここにきて、シュート決まるようになって頼もしい限り https://t.co/uNawTOCCVa
◁◁◁

[link:] » "交渉" from:housaka1 - Twitter検索 https://t.co/SBHDcAy1PD

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 12:56／2012-11-06 12:19 URL： https://twitter.com/kk_hirono/status/1052408054866685952 https://twitter.com/housaka1/status/265654658306035712
&twitter(1052408054866685952){theme:light}
> 国選事件で示談交渉なんて、久しぶりだなぁ。
◁◁◁

[link:] » "示談" from:housaka1 - Twitter検索 https://t.co/Xi050Vm2UB

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 12:57／2018-04-27 14:16 URL： https://twitter.com/kk_hirono/status/1052408235532197890 https://twitter.com/housaka1/status/989734892299694080
&twitter(1052408235532197890){theme:light}
> 示談するにあたって、弁護士が付いてないということはないだろうから、第三者に開示しないという条項は入れているはずなんだけど、誰が漏らしたかと言うことが問題。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 12:57／2015-01-20 08:59 URL： https://twitter.com/kk_hirono/status/1052408260781907969 https://twitter.com/housaka1/status/557326585393471489
&twitter(1052408260781907969){theme:light}
> 弁護人が、早期に示談で終わらせようとすれば金のためと言われ、否認のまま裁判に持ち込んでも金のためと言われる。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 12:57／2015-01-17 23:31 URL： https://twitter.com/kk_hirono/status/1052408302439665664 https://twitter.com/housaka1/status/556458761255018496
&twitter(1052408302439665664){theme:light}
> 示談強要の件の法曹関係者の反応で驚いたのは、被害者のコメント（代理人経由の伝聞）が真実で、問題の弁護士が嘘言ってるという事実認定になってしまっていること。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 13:04／2015-01-17 23:19 URL： https://twitter.com/kk_hirono/status/1052409958103490565 https://twitter.com/housaka1/status/556455747400105985
&twitter(1052409958103490565){theme:light}
> 犯行態様に争いがあって、被害者の供述に合致しない映像がある場合に「後で問題になっても困りますから先に言っておきますが、裁判になれば法廷に出すことになります。示談金出す余裕なく申し訳ありませんが、お互いのためにここは告訴取り下げてもらえませんか」というのも問題なのだろうか。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 13:05／2012-02-01 20:31 URL： https://twitter.com/kk_hirono/status/1052410165885116416 https://twitter.com/housaka1/status/164672155387301889
&twitter(1052410165885116416){theme:light}
> ブログを更新しました。『検察官のデンキキによる「示談書潰し」　その１』http://t.co/ZaJhtmIZ
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 13:05／2012-02-01 12:32 URL： https://twitter.com/kk_hirono/status/1052410242250825729 https://twitter.com/housaka1/status/164551675435163648
&twitter(1052410242250825729){theme:light}
> 書証の同意圧力（？）について、腹が立つのは、こっちが示談書を取調請求した際に、検察官が示談についての被害者の電話聴取書を請求して、電話聴取に同意しないんだったら示談書に同意しないなどと言い出す場合。示談書に「宥恕」文言を入れているわけでもないのに「示談はしましたが許せません」って
◁◁◁

[link:] » "宮崎" from:housaka1 - Twitter検索 https://t.co/zM8UqqLX5O

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜housaka1（法坂一広（筆名）） 日時：2018-10-17 13:11／2012-02-13 12:53 URL： https://twitter.com/kk_hirono/status/1052411774958481408 https://twitter.com/housaka1/status/168905564779323392
&twitter(1052411774958481408){theme:light}
> @numaguchiy ご購入ありがとうございます。今度、宮崎に売り込み（？）に行く予定です！！！法坂でした。
◁◁◁

　やはり宮崎の強姦ビデオ示談交渉に関連して深く考えさせられたツイートは、法坂一広（筆名）弁護士のものでした。しかし、「宮崎」と検索するとそれらしいものは見当たらず、これが検索がうまく行かず、他のアカウントと取り違える要因の1つとなっていたのかもしれません。

```
「示談書」を取り交わした場合は、それを証拠（書証）として裁判所に提出することになります。



刑事事件の場合、書証については、相手方の「同意」がなければ、原則として裁判所に提出することはできません。



弁護人が「示談書」を提出しようとする場合、検察官の「同意」を得る必要があります。


ところが……



検察官に示談書を開示すると、検察官は被害者に本当に示談したのかどうかを確認するわけです。



（個人的には、こういう確認をすること自体が気に入らない。弁護人も同じ法曹資格者なのですから。それに、検察官の提出しようとする書証の全てについて、弁護人が裏を取るなんて言ったら、検察官も嫌がることでしょう……とりあえず、この点は置いておいて）




更に、いつの間にやら、示談について確認した検察官（ときとして検察事務官）が、行きがけの駄賃だとばかりに、電話聴取書（通称デンキキ）を作成するという扱いが一般化しています。


デンキキの内容は、大抵「示談はしましたが、被告人を許せない気持ちには変わりありません」というものです。



まあ、これくらいならまだしも、「本当は受け取りたくはなかったのです」「よく分からないままに印鑑を押しただけです」とか、ひどい場合になると



「弁護人に騙されて印鑑を押しました」



とまで書かれたケースもあったのだそうです。




そして、検察官はこのデンキキを証拠請求して、



「弁護人がデンキキに同意しないんだったら、示談書にも同意してやんないけんね！」



とのたまうわけです。


（「少し」と言いつつ、長くなりましたので、続きはまた明日にでも……） 



［source：］検察官のデンキキによる「示談書潰し」　その１ | 2.五体不満足 https://ameblo.jp/bengoshi-kh/entry-11152417377.html
```

　次が法坂一広（筆名）弁護士のTwitterアカウントのプロフィールです。

```
法坂一広（筆名）
@housaka1
福岡のジャズ、アビスパ福岡好き弁護士作家。スポーツライター。脳出血後の左片麻痺のため、リハビリ中。闘病手記のオファーお待ちしております。 「弁護士探偵物語 天使の分け前」「同 完全黙秘の女」「最終陳述」(以上宝島社）「ダーティ・ワーク」（幻冬舎）。執筆

レベルファイブスタジアムに行こう！
ameblo.jp/bengoshi-kh/
2011年3月に登録

［source：］法坂一広（筆名）(@housaka1)さん | Twitter https://twitter.com/housaka1
```

　ずいぶん久しぶりにみたアカウントでしたが、ツイートのほとんどはリツイートが０か１で、０の方が多いようです。これだとリツイートとして他のタイムラインでみることがなかったことが自然なことだと思いました。

▶（192／207） TW fukazawas（深澤諭史） 日時： 2018-04-30 21:26:00 +0900 URL： https://twitter.com/fukazawas/status/990930438569971712
{% tweet 990930438569971712 %}
> とりあえず，一般論として述べるけれども， \n 「自分の抱えている法律問題について，ネットで，自分に都合の良い情報をつまみ食いするのは自殺行為」 \n ということは，何度も強調しておく。 \n まさに「自殺後」の相談になってしまうことも，珍しくない。 \n （・∀・；）

　法律相談の相場というのは３０分か１時間で、消費税別の５千円と１万円が一般的かと思います。なかにはそれ以上の時間を掛けることもあるようですが、タイムチャージとなると１時間あたり２，３万から上が相場のようです。

　法律相談というのは実際に経験もしておりますが、相談する側の説明と、それに対する弁護士の回答というやりとりがあって、それをひっくるめた時間になりますが、それで常に的確な対応が出来るものなのかかねがね疑問に思っています。

　無料の法律相談には七尾市まで行ったことがありましたが、往復の電車代を含め、朝から夕方までの時間を潰し、なんの成果も得られず、大損をさせられただけだというのが率直な感想でした。中には相談にぴったり当て嵌まるケースというのもあるのかもしれないですが、違うことも多そうです。

　弁護士に相談しなければ取り返しのつかない不利益を招くというような発言も深澤諭史弁護士のツイートでは散見してきましたが、逆に過大な成果と大きな不利益を招くと誤認させる誇大広告のような不当表示にならないものかとも、前々から考えていました。

▶（193／207） TW fukazawas（深澤諭史） 日時： 2018-04-30 21:27:00 +0900 URL： https://twitter.com/fukazawas/status/990930663720144896
{% tweet 990930663720144896 %}
> 今日日，無料法律相談も充実しているし，場合によっては，無料で電話相談という方法もあるのだから，本当に，都合のよい嘘と心中する前に，弁護士に相談を。 \n （・∀・；） https://t.co/whpZqE665C

　都合のよい嘘というのも抽象的な表現ですが、それと心中というのもかなり強めの表現です。一般的に心中というのは一家心中や無理心中など最悪の結果を連想させるものかと思います。「弁護士に相談を。」というのも特別な救済法があるようですが、これも消費者を誤認させる不当性がないのか疑問です。

▶（194／207） TW fukazawas（深澤諭史） 日時： 2018-05-03 11:41:00 +0900 URL： https://twitter.com/fukazawas/status/991870414002540544
{% tweet 991870414002540544 %}
> 「議論が白熱すると現れる『都合の良い法律情報』」って，本当に，的確にまとめた言葉だなぁ・・・。 \n （・∀・；）

　この手合も深澤諭史弁護士のツイートでは散見されるものですが、具体的な指摘がなく、あってもかなり強引なこじつけではないかと疑いたくなるものばかりです。

▶（195／207） TW fukazawas（深澤諭史） 日時： 2018-05-03 11:50:00 +0900 URL： https://twitter.com/fukazawas/status/991872511074684936
{% tweet 991872511074684936 %}
> 一時期流行った偽医療情報と，「都合のいい法律情報」「ぼくのかんがえたさいきょうのほうりつかいしゃく」問題って，同根だと思う。 \n 社会的な損失が大きいから，どうにかしないと。 \n （・∀・；）

　今年の５月３日のツイートとなっています。はっきりした日にちは思い出せないですが、憲法記念日というのがその辺りにあったかと思います。

```
「国民の祝日に関する法律」 (昭和 23年) で定められた祝日の一つ。5月3日。日本国憲法の施行 (1947年5月3日) を記念する日。

［source：］憲法記念日(けんぽうきねんび)とは - コトバンク https://kotobank.jp/word/%E6%86%B2%E6%B3%95%E8%A8%98%E5%BF%B5%E6%97%A5-61078
```

　あまり自信はなかったのですが、憲法記念日が５月３日だということが確認できました。そもそも法律の解釈には学説判例等があって、下級審の判例など参考にしかならないはずです。最高裁での憲法違反も判例違反もそのほとんどが不適切として棄却されるのが現状のはずです。

　いわゆる民間療法と素人の法律判断を同列において、弁護士としての法解釈や判断を優勢で価値の高いものとして印象づけているようですが、前提となる事実認定を含め、結果を先取りしすぎた不確かさ、さらに暴走的な危うさしか感じ取ることが出来ず、それこそ蔓延性のある社会的脅威かと思います。

▶（196／207） TW fukazawas（深澤諭史） 日時： 2018-05-06 09:42:00 +0900 URL： https://twitter.com/fukazawas/status/992927607346810880
{% tweet 992927607346810880 %}
> 「なぜ，ネットで都合のよい嘘の法律情報を集めてばかりいるのか？」 \n って，かなり驚きをもって迎えられている現実ですが，ネットトラブルの当事者を，加害者含めて多数弁護してきた経験からいうと，実は珍しくともなんともない現象。 \n （・∀・；）

　法律家の弁護士でもテレビ番組のコメンテーターとして、誤った情報を発言し、批判されたり、謝罪することがあります。どちらも無期懲役の仮釈放の相場だったかと思いますが、大渕愛子弁護士と横粂勝仁弁護士が、そのようなことをやっていました。

　ニュースにまでならなかったと思うので、番組を見ていなかった知らない人の方が多いかと思いますが、嘘とまではいえない誤情報も深澤諭史弁護士は、「ネットで都合のよい嘘の法律情報」に含めているのかと考えてしまいます。

　中には確かに間違った情報もありました。親告罪ではなくなった強姦罪を刑事手続で告訴を必要とする親告罪であるように解説したものだったと思います。確かにこの間違いは大きいかと思いますが、意図的に流す嘘というのは、熊本地震で檻からライオンが逃げ出したという話の類ではと思われます。

　たしかにネットには「都合のよい嘘の法律情報」というのが出回っているのかもしれませんが、深澤諭史弁護士がいうほど多いとは思えず、具体例も乏しく、そこまで断定的に決めつけるのは無理があるうように思えてなりません。

▶（198／207） TW fukazawas（深澤諭史） 日時： 2018-05-06 10:11:00 +0900 URL： https://twitter.com/fukazawas/status/992934922674323456
{% tweet 992934922674323456 %}
> 例の件に限らず，議論白熱で都合のいい嘘法律情報が発生する，紛争当事者が都合のよいデマだけピックアップして判断を誤る，という現象を繰り返し見ていると，これだけネットに情報が溢れ，手軽に手に入る時代でも，いやだからこそ法学部や法科大学院で法律を学ぶ意義は大きいと痛感する。 \n （・∀・）

　例の件が何を指すのかわからないですが、今年の５月６日であれば、それらしい情報は見つけることができそうにも思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年05月06日 - Twilog https://t.co/n60BraBF96

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜obpmb3fN93mQI9i（大阪名物パチパチ弁護士） 日時：2018-10-17 16:54／2018-05-04 10:24 URL： https://twitter.com/kk_hirono/status/1052467790836260864 https://twitter.com/obpmb3fN93mQI9i/status/992213336279339008
&twitter(1052467790836260864){theme:light}
> 弁護士に相談した方がいいときはどんな時かというと、とにかく困ったか困ったと感じた時や。すぐや。 \n  弁護士は法律知識だけじゃなくて事案分析のプロやしな。すっきりするで(ピンキリやけどな)。 \n   \n  「5,000円の相談料は高いわ」と思う奴は他の方法考え。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Redips00（赤ネコ@弁護士兼マンガ家） 日時：2018-10-17 16:54／2018-05-05 17:27 URL： https://twitter.com/kk_hirono/status/1052467813842006016 https://twitter.com/Redips00/status/992682249282666496
&twitter(1052467813842006016){theme:light}
> なぜ人は占い師に5000円払うくせに、弁護士に払う5000円を高いと言うのか。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Redips00（赤ネコ@弁護士兼マンガ家） 日時：2018-10-17 16:54／2018-05-05 17:29 URL： https://twitter.com/kk_hirono/status/1052467841587245056 https://twitter.com/Redips00/status/992682609426677760
&twitter(1052467841587245056){theme:light}
> 高いと思わない人が相談に来るんだろうけどな。
◁◁◁

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年05月05日 - Twilog https://t.co/mrAuuI2y96

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜take___five（中村剛（take-five）） 日時：2018-10-17 16:56／2018-04-27 07:43 URL： https://twitter.com/kk_hirono/status/1052468374024806401 https://twitter.com/take___five/status/989636003961880576
&twitter(1052468374024806401){theme:light}
> せめて、懲戒請求する前に、「懲戒請求しても大丈夫か」くらいは誰か弁護士に相談した方がいいと思いますよ。誰かの煽りにのって懲戒請求して数十万〜数百万払わされることになっても、その煽った人は責任を取ってくれるかわからないので。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜take___five（中村剛（take-five）） 日時：2018-10-17 16:56／2018-04-25 22:44 URL： https://twitter.com/kk_hirono/status/1052468458502291459 https://twitter.com/take___five/status/989138085219680256
&twitter(1052468458502291459){theme:light}
> いい機会なんで一般の人達への情報提供。 \n  ・弁護士に対する懲戒請求は誰でもできるが、濫用的懲戒請求の場合、損害賠償義務を負う \n  ・その額は1件あたり数十万〜百万円ほど \n  ・訴訟に必要な住所氏名は、あなたが記載した懲戒請求書から相手の弁護士に伝わる \n  ・相手は裁判をお気軽にやってくる弁護士
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ssk_ryo（ささきりょう） 日時：2018-10-17 16:57／2018-04-29 16:01 URL： https://twitter.com/kk_hirono/status/1052468636818919424 https://twitter.com/ssk_ryo/status/990486094310293504
&twitter(1052468636818919424){theme:light}
> あ、そうか。ハッシュタグが #不当懲戒 だからいろいろ言う人が出てるのか。 #不当懲戒請求 にすればよかったか。今後はそうしよう。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ssk_ryo（ささきりょう） 日時：2018-10-17 16:57／2018-05-03 13:56 URL： https://twitter.com/kk_hirono/status/1052468710668025856 https://twitter.com/ssk_ryo/status/991904428599922689
&twitter(1052468710668025856){theme:light}
> #不当懲戒請求　の件で、５月１６日、司法記者クラブで記者会見をします。ノースライム先生と私が会見します。興味のある記者さんは是非お越し下さい。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 16:58／2018-05-05 09:26 URL： https://twitter.com/kk_hirono/status/1052468837231222784 https://twitter.com/hirono_hideki/status/992561020999630850
&twitter(1052468837231222784){theme:light}
> 刑事事件の弁護活動で被害者側に何度も示談を迫ったとして、２０１３年に県弁護士会から退会命令の懲戒処分を受けた高森浩弁護士について、日本弁護士連合会は先月２６日付で、処分をより軽い業務停止２年間の懲戒処分に変更した。 https://t.co/5kLXfWEY2K
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 16:58／2018-05-05 09:25 URL： https://twitter.com/kk_hirono/status/1052468861662949376 https://twitter.com/hirono_hideki/status/992560900094619648
&twitter(1052468861662949376){theme:light}
> 高森浩弁護士（富山）、退会命令から業務停止２年に変更　／富山 ( 事件 ) - 弁護士自治を考える会 - Yahoo!ブログ https://t.co/5kLXfWEY2K
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 16:58／2018-05-05 09:24 URL： https://twitter.com/kk_hirono/status/1052468891253858304 https://twitter.com/hirono_hideki/status/992560673107329024
&twitter(1052468891253858304){theme:light}
> 深澤諭史さんのツイート: "なんか勘違い・混同があるようですが，①弁護士に対する懲戒請求が不法行為になる場合と，②民事訴訟の訴え提起が不法行為になる場合，以上①と②の範囲は大きく異なります。 ①の方が相当（あるいは極めて，といって… https://t.co/tLnUZE50pM
◁◁◁

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年05月04日 - Twilog https://t.co/DvcVc3Kwvu

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ssk_ryo（ささきりょう） 日時：2018-10-17 17:00／2018-05-04 16:08 URL： https://twitter.com/kk_hirono/status/1052469435296927744 https://twitter.com/ssk_ryo/status/992299922195021825
&twitter(1052469435296927744){theme:light}
> 不法行為地が東京弁護士会になるので、管轄は東京地裁ですね。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2018-10-17 17:01／2018-05-04 16:57 URL： https://twitter.com/kk_hirono/status/1052469538472656896 https://twitter.com/yamato_lawyer/status/992312350790184961
&twitter(1052469538472656896){theme:light}
> 実名報道の弊害の一つ。弁護士ドットコムからの取材でも回答したが、（ https://t.co/SsxRKRX4jG ）実名報道によって被害者にも大きな迷惑がかかる。実名報道はもっと慎重に考えるべき。取材自粛要請 被害者の保護者から… https://t.co/bl7uapDvJx
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Hideo_Ogura（小倉秀夫） 日時：2018-10-17 17:02／2018-05-03 05:57 URL： https://twitter.com/kk_hirono/status/1052469900730482688 https://twitter.com/Hideo_Ogura/status/991783794138144769
&twitter(1052469900730482688){theme:light}
> 女性専用車両を設けても、示談金欲しさに男女共用車両に乗り込んで痴漢冤罪を生み出す女性を排除できません。なので、冤罪防止にはなりません。RT @die1248: @katepanda2 男の一個人として言うなら、痴漢防止なり冤罪防止の為に女性専用車両ある方がいいですね、
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Hideo_Ogura（小倉秀夫） 日時：2018-10-17 17:02／2018-05-03 06:02 URL： https://twitter.com/kk_hirono/status/1052469957257097216 https://twitter.com/Hideo_Ogura/status/991784894631219200
&twitter(1052469957257097216){theme:light}
> 男性にもフルスペックの人権が保障されるべきだというと、色々なメールとかきます。RT @katepanda2:性差別性暴力について意見してメディアに名前出たりすると来る。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Hideo_Ogura（小倉秀夫） 日時：2018-10-17 17:03／2018-05-04 19:11 URL： https://twitter.com/kk_hirono/status/1052470035237621765 https://twitter.com/Hideo_Ogura/status/992345902839926784
&twitter(1052470035237621765){theme:light}
> 日本人男性にも基本的人権が保障されると主張しただけでこの言われよう。RT @ef2818: 「法律に詳しいということは弁護士で奴らの味方」ねえ。無駄に感じ悪い人とかヤメケンとか小倉とか、人権感覚が狂った弁護士が人気があるのも理解できるね。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 17:03／2018-05-04 20:24 URL： https://twitter.com/kk_hirono/status/1052470116690980864 https://twitter.com/hirono_hideki/status/992364281759854592
&twitter(1052470116690980864){theme:light}
> @Hideo_Ogura @ef2818 感覚というよりは、それが弁護士としての本拠地、「ご本尊」ではないでしょうか？　弁護士妖怪大泥棒神社たる所以です。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 17:03／2018-05-04 20:15 URL： https://twitter.com/kk_hirono/status/1052470145325514753 https://twitter.com/hirono_hideki/status/992362007096520704
&twitter(1052470145325514753){theme:light}
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”小林事件”／ささきりょう（@ssk_ryo）の検索（2010-10-27〜2016-12-05／2018年05月04日20時14分の記録102件） https://t.co/9Dt0gpzWo4
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 17:03／2018-05-04 15:50 URL： https://twitter.com/kk_hirono/status/1052470216259563521 https://twitter.com/hirono_hideki/status/992295340970684416
&twitter(1052470216259563521){theme:light}
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”弁護士に手を出したら奴ら群れで襲いかかってくる”／データベース登録済みツイート：2018年05月04日15時37分の記録：ユーザ・投稿：7／9件 https://t.co/As2i1LXkA9
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 17:04／2018-05-04 13:30 URL： https://twitter.com/kk_hirono/status/1052470284945481730 https://twitter.com/hirono_hideki/status/992260121861345280
&twitter(1052470284945481730){theme:light}
> 「YouTubeとかみれないので」というバイキングの司会者坂上忍。
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-10-17 17:04／2018-05-04 11:51 URL： https://twitter.com/kk_hirono/status/1052470335696560128 https://twitter.com/hirono_hideki/status/992235134664376322
&twitter(1052470335696560128){theme:light}
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”法曹って，子どもの頃に「先生に『帰れ！』”／データベース登録済みツイート：2018年05月04日11時49分の記録：ユーザ・投稿：12／28件 https://t.co/LcJEffiO5h
◁◁◁

　それらしいと思われるのは佐々木亮弁護士や北周士弁護士の不当懲戒請求の件ですが、あの件を深澤諭史弁護士がデマと言っているのかもしれません。たしかに驚くような内容と件数の大量懲戒請求ではありましたが、弁護士らの対応や解釈にも強引さを感じていました。

▶（200／207） TW fukazawas（深澤諭史） 日時： 2018-05-10 20:27:00 +0900 URL： https://twitter.com/fukazawas/status/994539295049330688
{% tweet 994539295049330688 %}
> これ、本当に深刻だから、都合の良いデマと心中する前に、早く対処した方がいいと思う。 \n （・∀・；） https://t.co/yZKUeI15Db

　やはりこの深澤諭史弁護士のいうデマというのは、大量懲戒請求を扇動したという人物のことかと思いますが、それらの問題というのも根を辿ると、従軍慰安婦問題や歴史問題に行き着くようです。

　先日、ノーベル平和賞のニュースがありました。前々から北朝鮮問題で候補者が話題とされていましたが、結果は戦争の性犯罪に取り組み医師と被害者の女性でした。この件についてもキーワードでまとめ記事を作成したと思いますが、ほとんど見向きもしない弁護士が多かったと思います。

　性犯罪そのものを弁護士としての商売道具に悪用しているというのが、私の分析ですし、見向きもしない方向性というのもまさに都合次第としか考えられない弁護士脳の資質と習性です。

▶（202／207） TW fukazawas（深澤諭史） 日時： 2018-05-17 09:19:00 +0900 URL： https://twitter.com/fukazawas/status/996907912357330945
{% tweet 996907912357330945 %}
> 不当懲戒請求の件について，なお，これ，民事の話ですね。刑事は又別です。 \n 「とりあえず，都合のいい法律情報だけあつめて，放置しておけば，そのうち何とかなる」 \n は，最悪の選択であるといえます。 https://t.co/yZKUeI15Db

　そういえば、弁護士の大量懲戒請求の件では、弁護士から訴えられる側の代理人を受け付けるなどと高島章弁護士（新潟県弁護士会）が表明をしていたかと思います。深澤諭史弁護士もその側に向けて、善処できる妙案があるようなことをもったいをつけてちらつかせていたかと思います。

▶（203／207） TW fukazawas（深澤諭史） 日時： 2018-06-22 09:00:00 +0900 URL： https://twitter.com/fukazawas/status/1009949172139622405
{% tweet 1009949172139622405 %}
> 「社会に求められている弁護士像」って，要するに，弁護士だけ増員すると，真っ先に絶滅する種類の弁護士なんですよね。 \n 身も蓋もないけれども，不都合な真実として，ちゃんと直視の必要がある。

　これはちょっと記憶にあったのかはっきりしないツイートですが、意味もかなり不明です。社会が弁護士に不当な要求をしているということを言いたいのでしょう。自業自得という言葉もみたような気もしましたが、それは深澤諭史弁護士ではないかもしれません。

　ようやく（203／207）まで来ました。もう少しです。

▶（205／207） TW fukazawas（深澤諭史） 日時： 2018-07-30 22:43:00 +0900 URL： https://twitter.com/fukazawas/status/1023927074371690496
{% tweet 1023927074371690496 %}
> どこに適正手続の保障、推定無罪の原則があるのだというのだ…。 \n 裁判所だけは、刑事裁判の鉄則を守ってくれると思っていたのに…。 \n 検察に都合の悪そうな証拠は却下、検察側証人は「具体的かつ迫真性がある」の一言で信用性が認められる、そんな… https://t.co/SDRHbwssEr

　今日はほかにも見たようなことを思い出しましたが、 #司法発見伝 というハッシュタグがあります。前に南総里見八犬伝のNHK人形劇のことを思い出したと取り上げたことがあったかと思います。他に「アマゾンの奥地に探検」というようなフレーズもありましたが、最近は見かけなくなっています。

▶（206／207） TW fukazawas（深澤諭史） 日時： 2018-10-07 09:55:00 +0900 URL： https://twitter.com/fukazawas/status/1048738485262213120
{% tweet 1048738485262213120 %}
> それと、裁判が公開であることと、裁判資料を公開してもよいかは、別の問題なので要注意。 \n この辺りは、多少体系的に勉強をすれば、理解できることなのであるが、本人訴訟のための「勉強」って、「自分に都合の良い情報のつまみ食い」に終始するの… https://t.co/k9quSfLnxo

　躊躇なく本人訴訟を全否定するのもどうかと思います。法律上は本人訴訟が原則であり、そのため民事訴訟での弁護士の立場は代理人となっているのかとも考えますが、弁護士に任せられる問題なのかという判断も個人にはありそうですし、事情はさまざまかと思います。

▶（207／207） TW fukazawas（深澤諭史） 日時： 2018-10-10 15:12:00 +0900 URL： https://twitter.com/fukazawas/status/1049905457006092289
{% tweet 1049905457006092289 %}
> Air Pods これで，ＡｐｔＸ ＬＬに対応してくれれば，最強なんだけれども，そう都合よくいかないか。 \n （・∀・）

　最後に法律とは無関係のツイートのようですが、ようやく２０７件目に到達しました。


