#+STARTUP: content
 #+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "被告発人小島裕史裁判長（平成5年当時の名古屋高裁金沢支部裁判長）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-09-12 11:52:01 +0900

#contents

* TODO 岡口基一裁判官の分限裁判後の報道会見から考えたこと
  :LOGBOOK:
  CLOCK: [2018-09-12 水 11:59]--[2018-09-12 水 12:02] =>  0:03
  :END:

** TODO 伊藤和子弁護士
   :LOGBOOK:
   CLOCK: [2018-09-12 水 12:02]--[2018-09-12 水 12:07] =>  0:05
   :END:

*** TODO 伊藤和子弁護士と小倉秀夫弁護士が参加した岡口基一裁判官の分限裁判後の記者会見のYouTube動画

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:09／2018-09-12 01:23 URL： https://twitter.com/kk_hirono/status/1039712571073355776 https://twitter.com/hirono_hideki/status/1039550123485749248
&twitter(1039712571073355776){theme:light}
> 半裸SNS投稿の異色の裁判官に最高裁が判断へ… どこまで許される裁判官のSNS？ - 弁護士落合洋司（東京弁護士会）の日々是好日 https://t.co/SenKi1q2VJ
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:09／2018-09-12 01:29 URL： https://twitter.com/kk_hirono/status/1039712618577973248 https://twitter.com/hirono_hideki/status/1039551584026259456
&twitter(1039712618577973248){theme:light}
> 半裸SNS投稿の異色の裁判官に最高裁が判断へ… どこまで許される裁判官のSNS？（FNN PRIME） - Yahoo!ニュース https://t.co/V5uMil24Im
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:09／2018-09-12 01:41 URL： https://twitter.com/kk_hirono/status/1039712647980044289 https://twitter.com/hirono_hideki/status/1039554516096434176
&twitter(1039712647980044289){theme:light}
> 「長官はものすごい剣幕で…びびっちゃう」岡口判事会見：朝日新聞デジタル https://t.co/lkZ2JlvnwZ
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:09／2018-09-12 01:53 URL： https://twitter.com/kk_hirono/status/1039712690405396480 https://twitter.com/hirono_hideki/status/1039557615246692353
&twitter(1039712690405396480){theme:light}
> 「長官はものすごい剣幕で…びびっちゃう」岡口判事会見：朝日新聞デジタル https://t.co/lkZ2JlvnwZ \n  「最高裁長官に『まず１０分間しゃべって下さい』と言われ、予想をしていなかったのでパニクってしまったが、（東京高… https://t.co/DwxwtpiYgS
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:10／2018-09-12 02:57 URL： https://twitter.com/kk_hirono/status/1039712930365767680 https://twitter.com/hirono_hideki/status/1039573715028066304
&twitter(1039712930365767680){theme:light}
> 岡口裁判官が会見「ありえないことが起きている」「戒告なら法治国家とは言えない」 - 弁護士ドットコム https://t.co/hB5R5rHAhw
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:11／2018-09-12 03:00 URL： https://twitter.com/kk_hirono/status/1039712960795402241 https://twitter.com/hirono_hideki/status/1039574348330237952
&twitter(1039712960795402241){theme:light}
> 【ノーカット】岡口基一裁判官、司法記者クラブ会見（2018.9.11） - YouTube https://t.co/DpT5SAlFq0
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:11／2018-09-12 10:04 URL： https://twitter.com/kk_hirono/status/1039712998036660227 https://twitter.com/hirono_hideki/status/1039681069266554881
&twitter(1039712998036660227){theme:light}
> どうして女性差別と戦うの? : 人権は国境を越えて-弁護士伊藤和子のダイアリー https://t.co/CaGw5xNLr7
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜saeki_sr（佐伯博正＠働き方改革関連法ノート） 日時：2018-09-12 12:11／2018-09-02 06:34 URL： https://twitter.com/kk_hirono/status/1039713023303151616 https://twitter.com/saeki_sr/status/1036004412747993088
&twitter(1039713023303151616){theme:light}
> どうして女性差別と戦うの?   \n  「私は、何かあると、あの理不尽な思いを思い出し、試練に立たされている女性、社会から理不尽に叩かれている女性がいれば、そばにいて助けたい（略）」ヒューマンライツ・ナウ事務局長・伊藤和子氏… https://t.co/LbAg1tKcEh
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:11／2018-09-12 10:10 URL： https://twitter.com/kk_hirono/status/1039713047906934786 https://twitter.com/hirono_hideki/status/1039682696866197504
&twitter(1039713047906934786){theme:light}
> #伊藤和子　弁護士 - Twitter検索 https://t.co/f6gXPLGpki
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KazukoIto_Law（Kazuko Ito 伊藤和子） 日時：2018-09-12 12:11／2018-09-11 23:13 URL： https://twitter.com/kk_hirono/status/1039713075081826304 https://twitter.com/KazukoIto_Law/status/1039517337114763264
&twitter(1039713075081826304){theme:light}
> 岡口裁判官、白ブリーフ姿のアイコンについて語る「裁判所から批判されたことない」|弁護士ドットコムニュース https://t.co/efBbJQDBsy @bengo4topicsさんから
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KazukoIto_Law（Kazuko Ito 伊藤和子） 日時：2018-09-12 12:11／2018-09-11 23:12 URL： https://twitter.com/kk_hirono/status/1039713096812490752 https://twitter.com/KazukoIto_Law/status/1039517089218748422
&twitter(1039713096812490752){theme:light}
> 「長官はものすごい剣幕で…びびっちゃう」岡口判事会見：朝日新聞デジタル https://t.co/odCPStlAQs
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KazukoIto_Law（Kazuko Ito 伊藤和子） 日時：2018-09-12 12:11／2018-09-11 23:10 URL： https://twitter.com/kk_hirono/status/1039713124406837250 https://twitter.com/KazukoIto_Law/status/1039516510920704003
&twitter(1039713124406837250){theme:light}
> 弁護団10名全員が46期、 \n  うち私と主任の野間さん、小倉さん、宮崎さんの4人が4組です。 \n  岡口さんの１組や水戸修習からも応援が！ \n  最高裁判所に提出した主張書面（２）です - 分限裁判の記録　岡口基一 https://t.co/NV1PYfSMUf
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KazukoIto_Law（Kazuko Ito 伊藤和子） 日時：2018-09-12 12:11／2018-09-11 14:40 URL： https://twitter.com/kk_hirono/status/1039713156287746048 https://twitter.com/KazukoIto_Law/status/1039388134511788032
&twitter(1039713156287746048){theme:light}
> #岡口判事  \n  の期日が終わりました。 \n  このあと、 \n  5時から会見です。 \n  同期だけで結成した弁護団。 \n  同期の一大事に、 \n  被災したばかりの北海道、名古屋の弁護士も参加してがんばってくれました。 \n  小倉先生も駆けつけてくれました。 https://t.co/hvptFshz40
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KazukoIto_Law（Kazuko Ito 伊藤和子） 日時：2018-09-12 12:12／2018-09-11 10:13 URL： https://twitter.com/kk_hirono/status/1039713230153768960 https://twitter.com/KazukoIto_Law/status/1039320893380386817
&twitter(1039713230153768960){theme:light}
> 最高裁判所が、ＮＨＫその他マスコミの傍聴要請を拒否　　今日の審問期日 - 分限裁判の記録　岡口基一 https://t.co/PdGElqMQBu
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KazukoIto_Law（Kazuko Ito 伊藤和子） 日時：2018-09-12 12:12／2018-09-11 10:12 URL： https://twitter.com/kk_hirono/status/1039713248885407744 https://twitter.com/KazukoIto_Law/status/1039320677663178755
&twitter(1039713248885407744){theme:light}
> 本日の #岡口判事 \n    最高裁期日にあたり、 \n  #木村草太 先生 が \n  意見書を作成してくださいました。弁護団意見書とともに提供します❗
▷▷▷

　流れをおさらいする意味もあり、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のツイートを列挙しました。夜中の1時半か1時過ぎに目が覚めたように思います。テレビをつけたまま寝ていましたが、報道ステーションの途中だったかもしれません。

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:18／2018-09-11 22:13 URL： https://twitter.com/kk_hirono/status/1039714778959077377 https://twitter.com/hirono_hideki/status/1039502189520011264
&twitter(1039714778959077377){theme:light}
> ふるさと納税、ルール違反の自治体は制度“除外”も｜ニフティニュース https://t.co/v2U4rPrdFL
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:18／2018-09-11 22:11 URL： https://twitter.com/kk_hirono/status/1039714816934309888 https://twitter.com/hirono_hideki/status/1039501811344859136
&twitter(1039714816934309888){theme:light}
> 奈良弁護士会（西村香苗会長）は１１日、奈良県天理市内の自治会で、構成員の資格を地元神社の氏子に限定する「村八分」があり、人権侵害に当たるとして自治会に是正を勧告したと発表した。 https://t.co/GUvhHQvggI
▷▷▷

▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-12 12:18／2018-09-11 22:11 URL： https://twitter.com/kk_hirono/status/1039714857283534848 https://twitter.com/hirono_hideki/status/1039501686782418944
&twitter(1039714857283534848){theme:light}
> 奈良弁護士会：「村八分」で天理市内の自治会に是正勧告 - 毎日新聞 https://t.co/GUvhHQvggI
▷▷▷

　確認したところ、上記の３つが寝落ちする前のツイートだったようです。奈良の弁護士会の村八分の問題は、ニュースサイトのサイドバーで見かけたものでした。そこでも思い出したのが、似たような大分弁護士会の問題でした。大分県といえば、岡口基一裁判官の出身地になります。

　時刻は19時43分です。夕方にテレビで気になる石川県内ニュースがありました。調べたところ、全国ニュースはおろかネットのニュースとしてもまだあがってはいないようです。その後だったと思いますが、小雨の中、久しぶりにシメノドラッグ宇出津店に買い物に行ってきました。

　買い物から戻ってからはテレビをつけていません。気になる石川県内ニュースはMRO北陸放送のNスタというニュース番組で見ていました。金沢テレビのとなりのテレ金ちゃんとeveryの全国ニュースの関係と同じように、石川県内向けは「レオスタ」というコーナーになっているようです。

　その「Nスタ」ですが、昨日辺り、全国版の報道ニュース番組らしいと初めて気が付きました。それというのもTwitterのツイートの動画に、岡口基一裁判官の分限裁判のニュースの再生があり、その画面に「Nスタ」という番組名が見えたからです。

　時刻は19時51分です。録画機器の確認をしたのですが、以前の毎回予約で予約できていたのは「3分クッキング」だけでした。昨日、録画予約の一覧で前回同様の「かがのとイブニング」と「NEWS７」があることを確認していたのですが、録画は出来ていませんでした。

　昨日の未明だったように思いますが、取り外していた録画機器を接続させ、再生の動作まで確認をしていました。録画機器を取り外したのは9月4日の夕方のことで、18時20分ころに台風21号の強風で、表のガラス戸が外れ、大雨の予報も出ていたので、表に近いテレビなどをしまっていたのです。

　テレビは、強風による雨が吹き込み心配がなくなった時点で設置し直していたのですが、録画機器の方は、面倒もあったので数日間、とりつけないままにしていました。録画の必要性で取り付け直したのも、岡口基一裁判官の分限裁判のニュースを録画し、内容を確認するのが目的でした。

　よくみると、録画一覧の画面に「HDD　残量が少なくなっています。」という表示が出ていることにきがつきました。昨日の時点で、かなりの数の録画済み番組を消去したと思うのですが、容量に余裕が出たと思い、未明から朝に3つの番組を録画予約し、そちらは録画が出来ているようです。

　「日テレNEWS２４」、「あさチャン！」、「羽鳥慎一モーニングショー」という３つの番組です。まだ再生はしていないのですが、これも岡口基一裁判官の分限裁判のニュースが出ないか確認するための録画指定でした。

　昨夜のNEWS９ですが、番組開始から21時35分ぐらいまで視聴し、そのあとで「健康で文化的な最低限の生活　＃９」にチャンネル変更しました。その前の録画予約の一覧で確認していたのですが、その「健康で文化的な最低限の生活」の方が録画予約となっていました。

　「健康で文化的な最低限の生活」というドラマ番組は関心があったのですが、まともに見たのは紹介の放送とあと1回ぐらいだったように思います。初回の放送だけは単独で録画予約を入れていて、今も録画済みとなっています。

　録画の一覧を確認すると「健康で文化的な最低限の生活　＃１」は、7月17日の放送となっていて、同じ放送時間のNEWS９は8月24日の録画放送が残っていました。これは一括消去の作業で漏れたものだと思います。

　これまで毎回録画の予約を入れていたのは「NHK連続テレビ小説」、「3分クッキング」、「かがのとイブニング」、「NEWS７」、「NEWS９」の５つだけです。

　以前は、他の民放のドラマも毎回予約にしていたのですが、それは消しました。ただこの毎回予約の取り消しがややこしく、未だによく理解していません。

　録画危機は、数年前に3万円ちょっとでAmazonで買ったものです。値段をおさえたこともあり、同じ時間に録画できる番組は１つだけです。

　時刻は20時23分です。録画済みの「日テレNEWS２４」を早送りで再生していたところ、「ツイッターに”上半身裸の男性”も　「現役」裁判官が会見で・・・」という見出しで、岡口基一裁判官の分限裁判ののニュースが見つかりました。

　Twitterの検索で「岡口　テレビ」などと幅を持たせた検索をしていたのですが、確認できたのは関テレという関西方面のみの放送と思われる番組名ぐらいで、他に放送はなかったものとなかばあきらめていました。今日のテレビでも、岡口基一裁判官に関するニュースは1つも確認していません。

　時刻は20時34分です。リモコンの操作ミスで手間取りもあったのですが、録画していた「日テレNEWS２４」における岡口基一裁判官の記者会見等のニュースを一通り視聴しました。思いの外、踏み込んだ内容で、笹子トンネル崩落事故の陪席裁判官もしていたという初めて知る情報もありました。

　時刻は20時57分です。もう一つ毎回予約をしていた番組を忘れていました。今視聴しているNHKの「ニュースいしかわ８４５」という番組です。２０時４５分から２１時前までの放送ですが、東海北陸のニュースと説明が出ることもあり、静岡県のニュースが出ることもありました。

　金沢西高校の告訴のニュースは、ないのかと思った２０時５５分からでした。その前は、能登地方での大雨被害のニュースが中心で、七尾市の七尾城址へつながる道路が崩落して迂回路や登山道のことが紹介されていました。


