#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: 石川県警察
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-09-06 20:24:31 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  深澤諭史弁護士 弁護士ドットコム

[:contents]

* 2018年09月06日分

** 深澤諭史弁護士

*** 深澤諭史弁護士のリツイートとして発見した登録弁護士以外閲覧不可らしい、「【弁護士ドットコム】法律・法曹関連ニュース【弁護士限定】」

▷ リツイート→fukazawas（深澤諭史）＞newsforbengo4（【弁護士ドットコム】法律・法曹関連ニュース【弁護士限定】）｜2018/09/06 18:32／2018/09/06 18:30｜https://twitter.com/fukazawas/status/1037634556621336577  ／https://twitter.com/newsforbengo4/status/1037634145554325504
<blockquote class="twitter-tweet" lang="ja"><p>9/6のPickup

絶望的に進む司法統制　少数者守る役目果たせぬ　東京高裁判事　岡口基一　特別寄稿「ツイッター分限裁判」
https://t.co/atTGcmnEh7

６日の全裁判取りやめ　札幌高裁と地裁・簡裁… https://t.co/agwEwAn8FO</p>&mdash; newsforbengo4（【弁護士ドットコム】法律・法曹関連ニュース【弁護士限定】）<a href="https://twitter.com/newsforbengo4/status/1037634145554325504">2018/09/06 18:30</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
RT @newsforbengo4: 9/6のPickup

絶望的に進む司法統制　少数者守る役目果たせぬ　東京高裁判事　岡口基一　特別寄稿「ツイッター分限裁判」
https://t.co/atTGcmnEh7

６日の全裁判取りやめ　札幌高裁と地裁・簡裁
https://t.…
▷

<blockquote>
【弁護士ドットコム】法律・法曹関連ニュース【弁護士限定】
@newsforbengo4
弁護士会員限定で、法律・法曹関連ニュースを毎営業日更新しています。弁護士の方の場合、登録・購読は無料です。

東京・六本木
bengo4.com/lawyer/mypage/…
2018年5月に登録
<span style="color: #01DFA5; font-size: 12px;">［source：］ 【弁護士ドットコム】法律・法曹関連ニュース【弁護士限定】(@newsforbengo4)さん | Twitter <a href="https://twitter.com/newsforbengo4">https://twitter.com/newsforbengo4</a></span>
</blockquote>

　今夜初めて見るアカウントと思いましたが、Twitterへの登録が2018年5月となっています。今年ですが、今日は9月6日なので3ヶ月ぐらいは経過していることになり、今夜このタイミングで初めて見たというのも奇遇な出会いです。

　ページの再読込をしましたが、2018年9月6日20時39分という時点で、ツイート数は98件、フォロー1,548、フォロワー242件となっています。以外に少ないフォロワー数です。



** 三浦義隆弁護士

*** 「以前仲良く（隠語）していた人が旅行に行ってお守り買ってきてくれたけど即日捨てたことある。」という三浦義隆弁護士のツイート

▶ ツイート％lawkus（ystk）％2018/09/05 07:51％ https://twitter.com/lawkus/status/1037110839155687424
<blockquote class="twitter-tweet" lang="ja"><p>以前仲良く（隠語）していた人が旅行に行ってお守り買ってきてくれたけど即日捨てたことある。 https://t.co/gHHJHcBYmh</p>&mdash; lawkus（ystk}）<a href="https://twitter.com/lawkus/status/1037110839155687424">2018/09/05 07:51</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
以前仲良く（隠語）していた人が旅行に行ってお守り買ってきてくれたけど即日捨てたことある。 https://t.co/gHHJHcBYmh
▶

　昨日の昼にみたツイートだったと思います。そのあと三浦義隆弁護士のタイムラインを遡ったところツイートが見当たらなかったので、削除したのかとも思ったのですが、そのあと発見しました。

　三浦義隆弁護士の弁護士としての、宗教や信仰、一般常識を超えた独自の立ち位置を感じたツイートでした。弁護士の宗教的な社会的影響力についても考えさせられる資料です。スクリーンショットの方は、昨日の夜になって記録していたかと思います。

▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2018/09/05 21:53％ https://twitter.com/s_hirono/status/1037322742863785984
<blockquote class="twitter-tweet" lang="ja"><p>2018-09-05-215131_ystk（@lawkus）：以前仲良く（隠語）していた人が旅行に行ってお守り買ってきてくれたけど即日捨てたことある。.jpg https://t.co/Y3QSmBBB3T</p>&mdash; s_hirono（非常上告-最高検察庁御中_ツイッター}）<a href="https://twitter.com/s_hirono/status/1037322742863785984">2018/09/05 21:53</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
2018-09-05-215131_ystk（@lawkus）：以前仲良く（隠語）していた人が旅行に行ってお守り買ってきてくれたけど即日捨てたことある。.jpg https://t.co/Y3QSmBBB3T
▶

　三浦義隆弁護士については、なにより印象的な検察に関するツイートがあります。すでにご紹介済みかと思いますが、あらためてご紹介をしておきたいと思います。宗教や信仰の上を行く弁護士、警察や安心安全の上を行く弁護士の実像としても、参考になるものがあると思います。

<blockquote>
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
基準となる注目のツイートを含む最新199件のツイート
2017-12-07 22：16から199件：最新2017-12-13 21：08という範囲（5日22時間52分）の取得
基準となる注目ツイートの位置と内容タイムラインの該当箇所に移動
<span style="color: #01DFA5; font-size: 12px;">［source：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＼ystk　@lawkus＼「警察官は法律の素人です」 「認めれば不起訴にしてやる 認めれば執行猶予がある 黙秘すれば認めたのと同じになる 詳しくは言えないが動かぬ証拠を <a href="http://hirono2014sk.blogspot.com/2017/12/ystklawkus_22.html">http://hirono2014sk.blogspot.com/2017/12/ystklawkus_22.html</a></span>
</blockquote>

　法曹といわれる裁判官、検事、弁護士が法律のプロもしくは専門家で、その意味で警察官が法律の素人というのはあながち間違いではなさそうですが、ここまで強調されると、いろいろと考え込んでしまいます。弁護士による弁護士の絶対性もしくは神格化というのは、他にもみられる現象かと思います。

<blockquote>
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
基準となる注目のツイートを含む最新199件のツイート
2018-08-23 06：25から199件：最新2018-09-06 21：26という範囲（14日15時間1分）の取得
<span style="color: #01DFA5; font-size: 12px;">［source：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＼ystk　@lawkus＼以前仲良く（隠語）していた人が旅行に行ってお守り買ってきてくれたけど即日捨てたことある。 <a href="http://hirono2014sk.blogspot.com/2018/09/ystklawkus.html">http://hirono2014sk.blogspot.com/2018/09/ystklawkus.html</a></span>
</blockquote>



** 渡辺輝人弁護士

*** 「同窓生なのでシェア。」という渡辺輝人弁護士のツイートの「上智大生殺害：発生２２年、警視庁が現場再現の動画を公開 - 毎日新聞」という記事

2018年09月06日16時21分の登録： ＼渡辺輝人　@nabeteru1Q78＼同窓生なのでシェア。 / “363000c” http://hirono2014sk.blogspot.com/2018/09/nabeteru1q78-363000c.html

▶ ツイート％nabeteru1Q78（渡辺輝人）％2018/09/06 14:18％ https://twitter.com/nabeteru1Q78/status/1037570662498414592
<blockquote class="twitter-tweet" lang="ja"><p>同窓生なのでシェア。 / “363000c” https://t.co/2tNEqx8UYI</p>&mdash; nabeteru1Q78（渡辺輝人}）<a href="https://twitter.com/nabeteru1Q78/status/1037570662498414592">2018/09/06 14:18</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
同窓生なのでシェア。 / “363000c” https://t.co/2tNEqx8UYI
▶

<span style="color: #01DFA5; font-size: 12px;">» 上智大生殺害：発生２２年、警視庁が現場再現の動画を公開 - 毎日新聞 https://t.co/kHDTdHSjKa</span>

　どうもJavaScriptで処理ができないのかもしれません。JavaScriptでの引用ができませんでした。

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2018/09/06 22:01％ https://twitter.com/kk_hirono/status/1037687154850193408
<blockquote class="twitter-tweet" lang="ja"><p>» 上智大生殺害：発生２２年、警視庁が現場再現の動画を公開 - 毎日新聞 https://t.co/kHDTdHSjKa</p>&mdash; kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中}）<a href="https://twitter.com/kk_hirono/status/1037687154850193408">2018/09/06 22:01</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
» 上智大生殺害：発生２２年、警視庁が現場再現の動画を公開 - 毎日新聞 https://t.co/kHDTdHSjKa
▶

　記事には「不審な男は事件への関与が疑われており、身長１６０センチくらいで中肉体形。」という記載があります。今年に入ってから見つけた情報だったと思いますが、この事件の犯人は、他の千葉県だったと思いますが強姦殺人事件で無期懲役となった人物の犯行の疑いという話がありました。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「順子地蔵」の検索結果 - Twilog https://twilog.org/hirono_hideki/search?word=%E9%A0%86%E5%AD%90%E5%9C%B0%E8%94%B5&ao=a

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年01月06日 - Twilog https://twilog.org/hirono_hideki/date-180106

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年08月06日 - Twilog https://twilog.org/hirono_hideki/date-180806

　「順子地蔵」をキーワードに含むツイートのTwilogが2日だけだったというのは意外でした。同一犯が疑われる死刑求刑の無期懲役判決が確定した事件に関する情報も、私の見落としがあったのかもしれないですが、見当たりませんでした。

　その死刑求刑の無期懲役も、放火があったように思います。何度かみたほぼ全身の顔写真が印象的でしたが、160センチぐらいという小柄な体格には思えませんでした。事件の名称も思い出せないですし、被疑者の名前も記憶にはありません。

　３Dの公開動画にもでていた160センチぐらいという怪しい人物は、怪しい人物の目撃情報として知っていましたが、160センチだったという情報は今回初めて見たように思います。

　さきほど、検索している時に目にしたコメントに、外国留学の前日の殺害だったのでストーカーの可能性が高い、というものがありました。留学の前日の事件だったということはこれまでに繰り返し見てきた情報ですが、身近な関係から発展した事件という見立ても、これまで見なかったものです。

<blockquote>
事件概要
平成8年9月9日（月曜日）（被害者の母親が外出した）午後3時50分ころから（119番通報があった）午後4時39分までの間、葛飾区柴又3丁目被害者宅2階において、被害者が刃物で殺害された上、自宅を放火されるという事件が発生しました。
この日の天候は朝から雨が降り続き、肌寒い一日でした。

発生日時
平成8年9月9日（月曜）午後3時50分ころから同日午後4時39分までの間

発生場所
東京都葛飾区柴又3丁目　被害者宅

被害者
女子大生（英語学科4年）　当時21歳

当時の出来事（平成8年事件当時）
出来事
7月11日　公安調査庁が公安審査委員会にオウム真理教の解散請求
7月19日　アトランタ・オリンピック開催（8月4日まで）
8月4日　映画「男はつらいよ」の主演俳優・渥美清さん死去（68歳）
9月3日　渥美清さんに国民栄誉賞
9月17日　野茂英雄さん（当時ロサンゼルス・ドジャーズ所属）が日本人初大リーグでのノーヒット・ノーラン達成

テレビ番組
NHK連続テレビドラマ小説「ひまわり」「ふたりっ子」
NHK大河ドラマ「秀吉」
民放ドラマ「ロングバケーション」

流行語等
「自分で自分をほめたい」
「ルーズソックス」
「チョベリバ・チョベリグ」
「ストーカー」

当日の番組表
<span style="color: #01DFA5; font-size: 12px;">［source：］ 柴又三丁目女子大生殺人 放火事件　警視庁 <a href="http://www.keishicho.metro.tokyo.jp/jiken_jiko/ichiran/ichiran_10/kameari.html">http://www.keishicho.metro.tokyo.jp/jiken_jiko/ichiran/ichiran_10/kameari.html</a></span>
</blockquote>

　「午後3時50分ころから同日午後4時39分までの間」とここまで時間が絞られているというのも初めて知った気がします。50分の間で殺人と放火が起こったようです。顔見知りの犯行としてはずいぶん短い時間で、流しの手慣れた犯行のようにも思えます。

　ストーカー事件だったとすれば、顔見知りということになりそうですが、殺して放火することを目的としていれば、家の前で立ち尽くしていたという不審人物とは違うような気もします。いずれにせよ、ミステリー性の高い事件です。

　順子地蔵のことは、長い間、録画したままになっていた番組の再生視聴がきっかけで知りました。



*** 東京都葛飾区の女子大生放火殺人事件の「順子地蔵」を知ったテレビの録画番組の記録

▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2018/09/06 22:57％ https://twitter.com/s_hirono/status/1037701276539076609
<blockquote class="twitter-tweet" lang="ja"><p>2018-01-06_144727＿録画再生・未解決事件追跡プロジェクト　島根女子大学生殺害事件　動画公開踏み切る警察.jpg https://t.co/H0vjpykWiT</p>&mdash; s_hirono（非常上告-最高検察庁御中_ツイッター}）<a href="https://twitter.com/s_hirono/status/1037701276539076609">2018/09/06 22:57</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
2018-01-06_144727＿録画再生・未解決事件追跡プロジェクト　島根女子大学生殺害事件　動画公開踏み切る警察.jpg https://t.co/H0vjpykWiT
▶

▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2018/09/06 22:57％ https://twitter.com/s_hirono/status/1037701308990423040
<blockquote class="twitter-tweet" lang="ja"><p>2018-01-06_151304＿録画一覧・１２／１３（日）NHKスペシャル　未解決事件　追跡プロジェクト「埋もれた情報　動き出した事件」.jpg https://t.co/O5uBCumUqr</p>&mdash; s_hirono（非常上告-最高検察庁御中_ツイッター}）<a href="https://twitter.com/s_hirono/status/1037701308990423040">2018/09/06 22:57</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
2018-01-06_151304＿録画一覧・１２／１３（日）NHKスペシャル　未解決事件　追跡プロジェクト「埋もれた情報　動き出した事件」.jpg https://t.co/O5uBCumUqr
▶

　Twilogでは情報が見当たらなかったので、２０１８年１月６日という日付の情報を頼りに、パソコン内のファイルを検索して見つけました。ファイルをコピーし、ファイル名を変更してTwitterにアップロードしたものです。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「未解決事件 追跡プロジェクト」の検索結果 - Twilog https://twilog.org/hirono_hideki/search?word=%E6%9C%AA%E8%A7%A3%E6%B1%BA%E4%BA%8B%E4%BB%B6%E3%80%80%E8%BF%BD%E8%B7%A1%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88&ao=a

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2015/12/13 21:06％ https://twitter.com/hirono_hideki/status/676010393093980161
<blockquote class="twitter-tweet" lang="ja"><p>NHKスペシャル　未解決事件　追跡プロジェクト「埋もれた情報　動き出した事件」
2015年12月13日（日）  21時00分～22時15分  の放送内容 https://t.co/CKWGtXviZ1</p>&mdash; hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語}）<a href="https://twitter.com/hirono_hideki/status/676010393093980161">2015/12/13 21:06</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
NHKスペシャル　未解決事件　追跡プロジェクト「埋もれた情報　動き出した事件」
2015年12月13日（日）  21時00分～22時15分  の放送内容 https://t.co/CKWGtXviZ1
▶

　ちょっと目を疑ったのですが、２０１５年１２月１３日に録画していた番組を、２０１８年１月６日になって気が付き再生をしていたようです。１月６日というのは０時で日付が変わるタイミングで１月７日に、宇出津の八坂神社で「七日詣り」があるのですが、記憶にはありませんでした。

　宇出津の八坂神社の七日詣りのことは、２０１７年のこととして特別な思いがあり、それが小倉秀夫弁護士のツイートとも関連していました。私がお地蔵さまにこだわるようになったのも、八坂神社に向かう時の観音寺橋のたもとの地蔵の祠がきっかけというか、始まりだったようにも思います。

　順子地蔵のことを知ったのも、小倉秀夫弁護士の「葛飾　倶楽部」というツイートを始めてみた時期と近接していたように思います。



*** Twilogで調べると２０１７年１２月９日に発見したらしい小倉秀夫弁護士の「葛飾弁護士倶楽部」というツイート、過去に記憶にない例外１件

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「葛飾 倶楽部」の検索結果 - Twilog https://twilog.org/hirono_hideki/search?word=%E8%91%9B%E9%A3%BE%E3%80%80%E5%80%B6%E6%A5%BD%E9%83%A8&ao=a

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞Hideo_Ogura（小倉秀夫）｜2017/12/09 16:31／2014/08/27 01:52｜https://twitter.com/hirono_hideki/status/939397173279473664  ／https://twitter.com/Hideo_Ogura/status/504310462402424833
<blockquote class="twitter-tweet" lang="ja"><p>葛飾弁護士倶楽部では、東京が大震災に見舞われたときはなるべく早期に区民法律相談に応じられるように体制を組んでいるのだけど、それをやると要らぬ批判を受けるようだなあ。</p>&mdash; Hideo_Ogura（小倉秀夫）<a href="https://twitter.com/Hideo_Ogura/status/504310462402424833">2014/08/27 01:52</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
RT @Hideo_Ogura: 葛飾弁護士倶楽部では、東京が大震災に見舞われたときはなるべく早期に区民法律相談に応じられるように体制を組んでいるのだけど、それをやると要らぬ批判を受けるようだなあ。
▷

　次が記憶になかった小倉秀夫弁護士のツイートになります。その記憶になかった小倉秀夫弁護士のツイートは、今回のTwilogの検索で初めて発見したものではありません。

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞Hideo_Ogura（小倉秀夫）｜2014/08/27 09:29／2014/08/27 01:52｜https://twitter.com/hirono_hideki/status/504425392195645440  ／https://twitter.com/Hideo_Ogura/status/504310462402424833
<blockquote class="twitter-tweet" lang="ja"><p>葛飾弁護士倶楽部では、東京が大震災に見舞われたときはなるべく早期に区民法律相談に応じられるように体制を組んでいるのだけど、それをやると要らぬ批判を受けるようだなあ。</p>&mdash; Hideo_Ogura（小倉秀夫）<a href="https://twitter.com/Hideo_Ogura/status/504310462402424833">2014/08/27 01:52</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
RT @Hideo_Ogura: 葛飾弁護士倶楽部では、東京が大震災に見舞われたときはなるべく早期に区民法律相談に応じられるように体制を組んでいるのだけど、それをやると要らぬ批判を受けるようだなあ。
▷

　「葛飾弁護士倶楽部」というのは地域に密着した消防団のイメージとも重なるものがありました。２０１６年１２月３１日だったと思いますが、宇出津の新村浜町に火事があって、消火後の消防団の活動をみながら、初詣のつもりで八坂神社に行き、誰もおらず閉まっていたということもありました。

　その宇出津の新村浜の火事は、ボヤに近い程度の火事だったと思いますが、北陸中日新聞では福島県の高野病院の医院長の火事での死亡記事と並んだ記載となっていました。偶然にしてはどうなのかという考えも、その辺りから始まったようにも思います。

　高野病院については、次のまとめ記事も作成しております。福島の放射能や原発事故にはツイートの多かった弁護士も、意外なほど反応が乏しかったようですが、高野病院医院長へのはなむけともなるような歴史的記録だと思っています。

2018年08月08日16時10分の登録： REGEXP：”高野病院”／データベース登録済みツイート：2018年08月08日16時10分の記録：ユーザ・投稿：7／18件 http://hirono2014sk.blogspot.com/2018/08/regexp201808081610718.html






