#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "本件告発事件の労働問題としての側面"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-10-21 10:44:36 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  小菅信子山梨学院大学法学部政治行政学科教授 谷口真由美大阪国際大准教授 河西邦剛弁護士 佐藤大和弁護士 神原元弁護士 愛媛ご当地アイドル自殺訴訟 パワハラ

#contents

* 参考資料

** 谷口真由美大阪国際大准教授

*** TBSサンデーモーニング（平成３０年１０月２１日放送）のパネリストとして「人権」を語ったことから調べたこと
    :LOGBOOK:
    CLOCK: [2018-10-21 日 11:01]--[2018-10-21 日 18:04] =>  7:03
    :END:

　起きたのは７時４０分頃でしたが、ずいぶん久しぶりに最初から終わりまでサンデーモーニングを視聴しました。初めの方がサウジアラビアのジャーナリスト殺害疑惑が中心でした。サンデーモーニングがいつから始まった番組なのか調べてもいないのですが、たぶん司会者はずっと同じかと思います。

　その日曜日朝８時からの番組、サンデーモーニングの司会者が関口宏です。昭和の時代、たぶん昭和４０年代からテレビで見ていたと思うのですが、その昭和４，５０年代の頃は、見た目で坂本九と混同するようなところがありました。

```
坂本 九（さかもと きゅう、本名：大島 九（おおしま ひさし）、1941年12月10日 - 1985年8月12日［1］）は、日本の俳優・タレント・歌手・司会者。神奈川県川崎市川崎区出身。愛称は九ちゃん（きゅうちゃん）。

妻は女優の柏木由紀子。柏木との間に娘が2人おり、長女は大島花子、次女は舞坂ゆき子。実祖父は茨城県田伏村（現：かすみがうら市）出身の漁師坂本金吉［注 1］。またサックス奏者の阿部薫は甥（姉の息子）。

『上を向いて歩こう』や『見上げてごらん夜の星を』、『明日があるさ』など数多くのヒット曲を出し、全世界におけるレコードの売上は1500万枚以上に達した［2］。また、映画や舞台の俳優、テレビ番組の司会など活動は多岐に渡り活動していたが、1985年（昭和60年）8月12日に起きた日本航空123便墜落事故で帰らぬ人となった。

［source：］坂本九 - Wikiwand https://www.wikiwand.com/ja/%E5%9D%82%E6%9C%AC%E4%B9%9D
```

　以前よりテレビで関口宏をみると中東やアラビアンナイトがイメージとして頭に浮かぶことがありました。３ヶ月ほど前になるでしょうか、ネットでその答えを見るけたのですが、それが「スター千一夜」という番組でした。その司会者だったのだと思います。

```
関口宏（1971 - 1979年、ただし初めて司会を担当したのは1970年4月［注 2］）

［source：］スター千一夜 - Wikipedia https://ja.wikipedia.org/wiki/%E3%82%B9%E3%82%BF%E3%83%BC%E5%8D%83%E4%B8%80%E5%A4%9C
```

```
『スター千一夜』（スターせんいちや）は、フジテレビ系列で、1959年3月1日（フジテレビ開局当日） - 1981年9月25日に放送されたトーク番組。放送回数は6417回。通称は「スタ千」。

［source：］スター千一夜 - Wikipedia https://ja.wikipedia.org/wiki/%E3%82%B9%E3%82%BF%E3%83%BC%E5%8D%83%E4%B8%80%E5%A4%9C
```

　たぶん初めて調べたのだと思います。スター千一夜という番組は司会者として関口宏しか記憶というかイメージがなかったのですが、ページにはざっと３２人ほどの司会者の名前があって「ほか多数」ともされています。

　それより意外だったのは放送時間です。昭和４４年１０月１日以降が「19:45 - 20:00」とされています。放送曜日も昭和４９年１０月以降は、土日を除く月曜日から金曜日まで放送されていたようです。

　これまでの私の記憶では２２時かあるいは２２時３０分からの放送で、それも日曜日だけとなっていました。この時間帯というのは必殺仕事人などの必殺シリーズの時代劇と同じものでした。

　最近は「月曜日から夜ふかし」というような番組があって、ニュースzeroが終わってからの放送なので、０時以降かと思います。「スター千一夜」もそれに近いような夜遅くの番組というイメージが番組名とマッチしていました。

　芸能情報にはまるで関心がなかったので、「スター千一夜」という番組もほとんど見た記憶がないのですが、番組名が中東のアラビアンナイトつまり「千夜一夜物語」を連想させたことと、関口宏と混同した坂本九のイメージだけがしっかり残っていました。

　実際に坂本九もスター千一夜を司会者をした時期があったようです。坂本九は歌手というイメージしかなかったので、これも意外です。それに夜の空をイメージさせるヒット曲も歌っていたかと思います。曲名は思い出せないですが、これも少し調べてみます。

```
「見上げてごらん夜の星を」（みあげてごらんよるのほしを）は、日本の歌手坂本九の1963年のヒット曲。作詞永六輔、作曲いずみたく。原曲は1960年に初演された同名ミュージカルの劇中主題歌。日本レコード大賞作曲賞受賞。

坂本の代表曲であり、後に数多くのアーティストにカバーされた。

［source：］見上げてごらん夜の星を (曲) - Wikipedia https://ja.wikipedia.org/wiki/%E8%A6%8B%E4%B8%8A%E3%81%92%E3%81%A6%E3%81%94%E3%82%89%E3%82%93%E5%A4%9C%E3%81%AE%E6%98%9F%E3%82%92_(%E6%9B%B2)
```

　私は１９６４年の生まれなので、生まれる１年ほど前のヒット曲だったようです。昭和４０年代によく耳にした曲の１つです。なんか暗い感じであまり好きではなかったのですが、自然によく耳に入ってきた曲でした。

　「千夜一夜物語」ですが、これも確認のため調べるまで「千夜物語」と思っていました。能都中学校の図書館でタイトルを見たことを印象的に憶えているのですが、読んだことはなく、手にとって開くようなこともなかったかもしれません。

　能都中学校の図書館はコの字型の校舎の玄関の上にありましたが、利用したことは少なく記憶に残っている本というのもその千夜一夜物語だけです。２階にあったように思いますが、２階には職員室もあったはずです。３階に何があったのかは思い出せません。

　能都中学校の音楽室は３階にありましたが、玄関と同じ面ではなく、給食室と同じ面の付け根だったと思います。なお、私は３年生の時も３年１組だけは教室が２階にありました。それもあったので３階の記憶というのは薄くなっているのかもしれません。

　能都中学校の放課後というのは、コの字の校舎と体育館の間の通路を周回するかたちで部活動の生徒が走り回っていました。今考えるととても危ないものだったと思うのですが、当時はまったく問題にならず、注意も受けることがなかったように思います。

　書いていて久しぶりに思い出したのですが、能都中学校の１年生のとき、教室から外に出てふざけているとき、頭に強い衝撃を受け、そのまま倒れました。ふざけていた相手からいきなり殴られたのだと思ったのですが、しばらくして駆け寄った声が３年生でした。

　声に聞き覚えのある３年生から笑いながら声を掛けられていたのですが、状況がのみこめず、あとで３階から落とした氷柱の氷の塊が、私の頭上に落ちたのだとわかりました。どれほどの大きさの塊だったのかわからないですが、とても心配した様子ではなかったことが何より印象的でした。

　当時の能都中学校は先輩後輩の上下関係がとても厳しく、登下校は先輩の顔を見るたびに挨拶をするのがきまりとなっていました。たぶん戦前の風潮をそのまま引き継いでいたのだと思います。高校のときも同じではありましたが、関係性はもっと複雑にはなっていました。

　私は３年生になる頃まで相撲部にいましたが、当時の能都中学校の相撲部の練習というのは、ほとんどが石川県立水産高校の相撲部への通いで、例外というのは１回しか記憶にありません。校舎から離れたところに相撲場があり、現在でも残っているようですが、そこで練習したのが１度だけです。

　１度だけだったので余計によく憶えているのですが、その相撲場の横には町営のプールがありました。プールの方はずいぶん前から跡形もなく草木に覆われています。辺田の浜や崎山、宇出津の上田町の方から坂を上ると、坂を上りきった右手にそのプールがありました。

　辺田の浜に住んでいたころ、夏になるとそのプールに行くことがありました。辺田の浜の家の近くには水産高校のグランドがあって、そこで野球の練習をすることもあったのですが、特に印象に残っていたのが、水産高校のラクビー部の練習風景でした。

　石川県立水産高校の相撲部は金沢市の卯辰山の全国相撲大会で優勝するほどの強豪校であったのですが、ラクビー部の方は問題外の弱小チームで、石川県内最強の羽咋工業高校には決まって１００対０で負けているという話を聞いていました。

　前にも書いていると思いますが、辺田の浜に住んでいる頃は、毎年夏になると京都の親戚が遊びに来ていていました。従兄弟に高校ラクビー花園大会の話を聞いていたように思っていたのですが、改めて考えると聞いていたのは「花園高校」だったのかもしれません。

```
花園中学校・高等学校（はなぞのちゅうがっこう・こうとうがっこう）は、京都府京都市右京区花園木辻北町にある、花園学園内の中学校・高等学校。

［source：］花園中学校・高等学校 - Wikipedia https://ja.wikipedia.org/wiki/%E8%8A%B1%E5%9C%92%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1
```

```
禅宗（臨済宗）妙心寺によって創設され、仏教（禅宗）の心を教育方針に掲げている。 花園学園内には他に、4年制総合大学の花園大学、洛西花園幼稚園がある。 「ラグビー部」「男子バレーボール部」「硬式野球部」「陸上競技部」「自転車競技部」「吹奏楽部」などの部活動も全国で活躍している。

［source：］花園中学校・高等学校 - Wikipedia https://ja.wikipedia.org/wiki/%E8%8A%B1%E5%9C%92%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1
```

　もしやと思って調べたのですが、京都市内に花園高校が実在するようです。私の京都の親戚は京都市の北区の方だと思うので、どうなのかと思ったのですが、Googleマップで見ると、そう離れてはいないようです。

　母親の５人兄弟の長男の長男のことで、花園高校の話を聞いたように思うのですが、記憶はあやふやです。もう一人弟がいて、そちらが京都大学に入学したという話を聞いたように思うのですが、同じ頃に兄が高校生で弟が大学生だったというのはあり得ない話です。

　そういえば、今日のサンジャボで久しぶりに籠池夫妻を見たのですが、夫人の個性がかなり強烈です。その母親の５人兄弟の長男という私のおじさんの妻が、いくらかそれに似たような個性がありました。声が大きく勢い良く喋る人でした。

　その京都のおばさんですが、数年前におじさんの遺影をもって私の家に来たことも前に書いていると思います。８月の９日頃だったと思いますが、愛知県に住む三女のおばさんから電話があったとき、大病を患ったという次女のおばさんのことを聞いたのですが、自宅で生活しているということでした。

　その時に幼い頃のはっきりしなかった記憶の確認ができたのですが、次女のおばさんの夫婦は前に北野天満宮の近くに住んでいて、今も倉庫のようにして残しているという話を聞きました。


