#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "弁護士らの不遇、不満の象徴としての成仏理論と地蔵菩薩の衆生済度"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-09-16 10:26:23 +0900

tags:  深澤諭史弁護士 成仏理論 地蔵菩薩 法クラ 落合洋司弁護士（東京弁護士会）

[:contents]

* 成仏理論

** 深澤諭史弁護士

*** 2018年9月15日のTwitterタイムライン

（以下のページに移転させました。）

成仏理論について再び考えさせられた深澤諭史弁護士のTwitterタイムライン：成仏理論／深澤諭史弁護士／2018年9月15日のTwitterタイムライン http://hirono2018.memo.wiki/d/%c0%ae%ca%a9%cd%fd%cf%c0%a4%cb%a4%c4%a4%a4%a4%c6%ba%c6%a4%d3%b9%cd%a4%a8%a4%b5%a4%bb%a4%e9%a4%ec%a4%bf%bf%bc%df%b7%cd%a1%bb%cb%ca%db%b8%ee%bb%ce%a4%ceTwitter%a5%bf%a5%a4%a5%e0%a5%e9%a5%a4%a5%f3#content_1_1_1

*** 2018年9月14日のTwitterタイムライン

（以下のページに移転させました。）

成仏理論について再び考えさせられた深澤諭史弁護士のTwitterタイムライン：成仏理論／深澤諭史弁護士／2018年9月14日のTwitterタイムライン http://hirono2018.memo.wiki/d/%c0%ae%ca%a9%cd%fd%cf%c0%a4%cb%a4%c4%a4%a4%a4%c6%ba%c6%a4%d3%b9%cd%a4%a8%a4%b5%a4%bb%a4%e9%a4%ec%a4%bf%bf%bc%df%b7%cd%a1%bb%cb%ca%db%b8%ee%bb%ce%a4%ceTwitter%a5%bf%a5%a4%a5%e0%a5%e9%a5%a4%a5%f3#content_1_1_2

** 九大キャンパス火災　元院生の男性 放火し自殺か

*** 落合洋司弁護士のブログの引用からの経緯で見つけたアクセスランキング1位のニュース記事
    :LOGBOOK:
    CLOCK: [2018-09-16 日 18:14]--[2018-09-16 日 19:09] =>  0:55
    :END:

▶ ツイート％yjochi（落合洋司 Yoji Ochiai 🇯🇵）％2018/09/16 16:37％ https://twitter.com/yjochi/status/1041229585046618112  
<blockquote class="twitter-tweet" lang="ja"><p>はてなブログに投稿しました #はてなブログ
高速で自損事故 そこに追突...　1歳と2歳のきょうだい死亡 - 弁護士落合洋司（東京弁護士会）の日々是好日
https://t.co/SXcRk2FC2U</p>&mdash; yjochi（落合洋司 Yoji Ochiai 🇯🇵}）<a href="https://twitter.com/yjochi/status/1041229585046618112">2018/09/16 16:37</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
はてなブログに投稿しました #はてなブログ
高速で自損事故 そこに追突...　1歳と2歳のきょうだい死亡 - 弁護士落合洋司（東京弁護士会）の日々是好日
https://t.co/SXcRk2FC2U  
▶

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-16 18:16／2018-09-16 17:50 URL： https://twitter.com/kk_hirono/status/1041254406895759365 https://twitter.com/hirono_hideki/status/1041248045965307905</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041254406895759365){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/hirono_hideki/status/1041248045965307905<a href="https://twitter.com/hirono_hideki/status/1041248045965307905"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 高速で自損事故 そこに追突...　1歳と2歳のきょうだい死亡（ホウドウキョク） - Yahoo!ニュース https://t.co/xTynJlVeNX
▷▷▷

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-09-16 18:16／2018-09-16 17:53 URL： https://twitter.com/kk_hirono/status/1041254431784722432 https://twitter.com/hirono_hideki/status/1041248573965328385</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041254431784722432){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/hirono_hideki/status/1041248573965328385<a href="https://twitter.com/hirono_hideki/status/1041248573965328385"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 九大キャンパス火災　元院生の男性 放火し自殺か　身元判明、福岡東署（西日本新聞） - Yahoo!ニュース https://t.co/nifnQVWPEj
▷▷▷

<blockquote>
15日未明、岡山・美作市の中国自動車道で、自損事故で止まっていたワゴン車に乗用車が追突し、1歳と2歳のきょうだいが死亡したほか、4人が軽いけがをした。
<span style="color: #01DFA5; font-size: 12px;">［source：］ 高速で自損事故 そこに追突...　1歳と2歳のきょうだい死亡（ホウドウキョク） - Yahoo!ニュース <a href="https://headlines.yahoo.co.jp/hl?a=20180915-00036334-houdouk-soci">https://headlines.yahoo.co.jp/hl?a=20180915-00036334-houdouk-soci</a></span>
</blockquote>

　記事に「きょうだい」とひらがなになっていたのも気になったのですが、2歳の長男と1歳の長女とのことです。「9/15(土) 19:36配信」という昨日のニュースだったようですが、テレビでも見ておらず、初めて知るニュースでした。

　岡山県の美作市とありますが、市というのは初めて見たような気がしました。中国自動車道沿いに「美作」という地名があったことは記憶にありますが、津山市の近くであったように思います。津山インターの近くには勝央というサービスエリアもありました。

　17時頃のテレビだったと思いますが、京都市の地名が長いということを特集にしていて、その放送で中京区のことを「なかぎょうく」と読むとしりました。上京区も同じですが、「なかきょうく」や「かみきょうく」と読むものと認識していたように思います。

　この京都市内と岡山県の津山市付近との関係については、昭和60年のこととして書いておきたいことがあります。現在は宝達志水町となっている押水町ともつながりがあります。「ファミー」などと呼ばれた中西運輸商の古い4トントラックのことです。

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2014/03/07 01:15％ https://twitter.com/kk_hirono/status/441608104040349697  
<blockquote class="twitter-tweet" lang="ja"><p>中西運輸商ではファミーとかスーパーの名前が箱に書いてあるオンボロの4トン車に乗っていて、岡山県の津山市あたりだったか中国自動車道ですが、トラックを横転させたような話があったかと思います。ちょっと記憶があいまいですが。</p>&mdash; kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中}）<a href="https://twitter.com/kk_hirono/status/441608104040349697">2014/03/07 01:15</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
中西運輸商ではファミーとかスーパーの名前が箱に書いてあるオンボロの4トン車に乗っていて、岡山県の津山市あたりだったか中国自動車道ですが、トラックを横転させたような話があったかと思います。ちょっと記憶があいまいですが。  
▶

　美作という地名は、宮本武蔵の出身地であったようにも思います。漫画のタイトル名がはっきり思い出せないですが、たぶん「宮本武蔵」というタイトルで本宮ひろ志の漫画がありました。能都中学校の1,2年生の頃であったという記憶です。

<blockquote>
時は関ヶ原の戦いの直前。英田郡の若者たちは最後の侍になるチャンスを狙っていた。その２００人の大将を誰にするか？出世に駆られた乱暴者・宮本村の弁蔵は、皆の前で侍を倒してみせる。しかし仲間たちの反応は・・。やがて天下分け目の戦いが始まった！青春の苦悩と成長を描いた本宮版・宮本武蔵！
<span style="color: #01DFA5; font-size: 12px;">［source：］  武蔵 第1巻 | 本宮 ひろ志 | マンガ | Kindleストア | Amazon <a href="https://www.amazon.co.jp/%E6%AD%A6%E8%94%B5-%E7%AC%AC1%E5%B7%BB-%E6%9C%AC%E5%AE%AE-%E3%81%B2%E3%82%8D%E5%BF%97-ebook/dp/B009SJQNY6">https://www.amazon.co.jp/%E6%AD%A6%E8%94%B5-%E7%AC%AC1%E5%B7%BB-%E6%9C%AC%E5%AE%AE-%E3%81%B2%E3%82%8D%E5%BF%97-ebook/dp/B009SJQNY6</a></span>
</blockquote>

　調べたところ本のタイトル名は「武蔵」だったようです。単行本が3巻まであったことはわかりましたが、発売の時期を特定しうる情報は見つかりませんでした。雑誌の連載として見た記憶はなく、単行本でのみ読んだという記憶です。

<blockquote>
福岡市東区箱崎6丁目の九州大箱崎キャンパスで7日朝に研究室を焼いた火災で、福岡東署は15日、焼け跡から見つかった遺体は研究室に出入りしていた同区の職業不詳の男性（46）と発表した。署によると、死因はやけどによる火傷死。男性が放火、自殺したとみて調べている。

【写真】九大箱崎キャンパスの火災現場で消火活動に当たる消防隊

　署は、現住建造物放火か、非現住建造物放火の疑いで、男性を容疑者死亡のまま書類送検することも視野に入れている。
<span style="color: #01DFA5; font-size: 12px;">［source：］ 九大キャンパス火災　元院生の男性 放火し自殺か　身元判明、福岡東署（西日本新聞） - Yahoo!ニュース <a href="https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci">https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci</a></span>
</blockquote>

　この九州大学の火災は、テレビニュースで見ていましたが、たしか法学部でありながら、関連した弁護士のツイートというのは１つも見かけないまま忘れていました。

　記事には放火し自殺したと疑われる元院生の困窮した生活ぶりが具体的に書いてありますが、大学内部の情報というのも余り見かけることがなかったので、参考になりました。

<blockquote>

■困窮、研究の場も無く　「経済破綻に直面」知人に訴え　非常勤職失い複数のバイト
　福岡市東区の九州大学箱崎キャンパスの火災で亡くなった卒業生の男性（46）は、2010年の退学後も常勤の研究職を目指していたが、非常勤職を“雇い止め”に遭うなどして困窮を深めた。家賃の支払いも滞り、肉体労働を掛け持ちして研究室で寝泊まりするようになった。そこに学舎の移転が重なる。「耐乏生活を強いられる」「経済破綻に直面」－。男性は親交のあった大学関係者に宛てたメールで、苦しい胸の内を訴えていた。

　複数の関係者によると、男性は15歳で自衛官になったが退官し、九大法学部に入学。憲法を専攻し、1998年に大学院に進学した。修士課程を修了して博士課程に進んだが、博士論文を提出しないまま2010年に退学となった。

　ドイツ語を勉強し、文献の校正ができるほどの力を付けた。生前は少なくとも県内の二つの大学で非常勤講師を務める傍ら、教授の研究補助もしていた。元教授は「授業の発表も丁寧で、論文を書く能力もあったのに」と振り返る。

　大学側によると、男性は15年以降、研究室を1人で使用。ただ、顔を出すのは夜間で、ほかの院生と接触しない“孤立”状態だった。
<span style="color: #01DFA5; font-size: 12px;">［source：］ 九大キャンパス火災　元院生の男性 放火し自殺か　身元判明、福岡東署（西日本新聞） - Yahoo!ニュース <a href="https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci">https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci</a></span>
</blockquote>

<blockquote>
心の内をメールで明かしていた
　そんな男性が、信頼した九大関係者に心の内をメールで明かしていた。

　月末払いの家賃を振り込もうとしましたが、金額が足りませんでした。経済破綻に直面しています（昨年6月1日）

　3、4月はほぼ無給だったことや、専門学校の非常勤職が“雇い止め”となり、5、6月の月収は14万5千円とつづった。

　10万円借りることができました。なんとか過ごせそうです（同月4日）

　男性は同月から昼間に週4回、宅配便の仕分けのアルバイトを始めた。

　昼のバイトを始める時73キロあった体重が、現在61キロ（今年3月12日）

　昨年12月からは夜も週4回、肉体労働の別のバイトも掛け持ちしていた。
<span style="color: #01DFA5; font-size: 12px;">［source：］ 九大キャンパス火災　元院生の男性 放火し自殺か　身元判明、福岡東署（西日本新聞） - Yahoo!ニュース <a href="https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci&p=2">https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci&p=2</a></span>
</blockquote>

<blockquote>
「院生はみな厳しい現実を共有していた。私が彼だったかもしれない」。男性をよく知る研究者は声を落とす。

　大学院生が研究を続けて「教授」や「准教授」といった常勤職を得るのは容易なことではない。文部科学省によると、博士号取得者または博士課程の単位取得者で、大学などに任期付きで籍を置きながら研究を続ける人を「ポストドクター」と定義し、1万5910人（15年度）に上る。男性は「ポスドク」に当たらないが、大学側も今年5月までは「ポスドク」と誤解して研究室の利用を黙認していた。

<span style="color: #01DFA5; font-size: 12px;">［source：］ 九大キャンパス火災　元院生の男性 放火し自殺か　身元判明、福岡東署（西日本新聞） - Yahoo!ニュース <a href="https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci&p=2">https://headlines.yahoo.co.jp/hl?a=20180916-00010003-nishinpc-soci&p=2</a></span>
</blockquote>

　これは、「高速で自損事故 そこに追突...　1歳と2歳のきょうだい死亡（ホウドウキョク） - Yahoo!ニュース」の記事のページで、アクセスランキング（国内）1位となっていたものです。そういえば、昨夜、テレビの小さなニュースとして見かけていたような気もしないではありません。

▷▷▷
<span style="background-color: #FBEFF5;>">RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-16 19:04／2018-09-16 19:02 URL： https://twitter.com/kk_hirono/status/1041266497513906176 https://twitter.com/s_hirono/status/1041266023956021250</span>
<div style="color: #848484; font-size: 11px;">&twitter(1041266497513906176){theme:light}</div><blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">https://twitter.com/s_hirono/status/1041266023956021250<a href="https://twitter.com/s_hirono/status/1041266023956021250"></a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br />> 2018-09-16-180019_九大キャンパス火災　元院生の男性　放火し自殺か　身元判明、福岡東署9／16（日）　13：10配信　.jpg https://t.co/uj5yacYncJ
▷▷▷

　弁護士のツイートで、収入が少ないとか困窮しているというのは、日常茶飯のこととして見かけていますが、司法試験の塾のアルバイトのようなものは以前見かけたように思いますが、本業に無関係のアルバイトをしているとか、アルバイトをしたという話は見かけていないように思います。



