#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "元最高裁判事桜井龍子氏のネット記事"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-09-26 09:41:06 +0900
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  元最高裁判事桜井龍 最高裁調査官 落合洋司弁護士（東京弁護士会）

#contents

* 経緯

** ジャーナリストの江川紹子氏

*** Twitterタイムラインでの発見
    :LOGBOOK:
    CLOCK: [2018-09-26 水 09:47]--[2018-09-26 水 10:57] =>  1:10
    :END:

▶ ツイート％amneris84（Shoko Egawa）％2018/09/18 11:01％ https://twitter.com/amneris84/status/1041869779940724736
&twitter(1041869779940724736){theme:light}
> 興味深いインタビュー。続きが早くよみたい　→【話の肖像画】元最高裁判事・桜井龍子（１）裁判官になったら「桜井」に（1/3ページ） - 産経ニュース https://t.co/n2hODcPmwN @Sankei_newsさんから  
▶

　ジャーナリストの江川紹子氏のTwitterタイムラインを遡ってツイートを捜したのですが、思っていたよりずいぶん前のものでした。9月18日11時1分の投稿日時になっていますが、今日は9月26日です。8日前になりますが、3,4日前という感覚でいました。

　最近、刑事事件や刑事裁判に関する目立ったツイートを見かけないと思いながらジャーナリストの江川紹子氏のタイムラインを見ていたのですが、この1つあとになるツイートで紹介されたジャーナリストの江川紹子氏本人のネット記事の内容も気になるものがありました。

▷ リツイート→amneris84（Shoko Egawa）＞seijipremier（毎日新聞 政治プレミア）｜2018/09/18 11:03／2018/09/18 09:18｜https://twitter.com/amneris84/status/1041870196439306240 ／ https://twitter.com/seijipremier/status/1041843877513113600
&twitter(1041870196439306240){theme:light}
> RT @seijipremier: 日本にいる外国人労働者は約128万人。「すでに日本は、外国人労働者なしでは回らない社会になっているのです」と指摘する江川紹子さん @amneris84 。「便利なモノでなく人として」受け入れるためどうすればいいか。皆さんの意見をお聞かせくださ…  

　ジャーナリストの江川紹子氏本人のツイートではなくリツイートとなっていましたが、ジャーナリストの江川紹子氏のネット記事の紹介ツイートです。正確になんと呼ぶのか忘れましたが、公式のツイートの方では記事のサムネイル表示があり、そちらに「細野豪志さん」という名前が出ています。

　サムネイルというのはリンク画像などの縮小版のことですが、誤解を与える可能性もあるので、正式と思われる呼び名を、あらためて調べて確認しておきたいと思います。

```
ツイッターカードとは、ツイートに貼り付けられた記事へのリンクを魅力的に見せる機能のことです。具体的にはツイートの中に「アイキャッチ画像」や「記事のタイトル」などが表示されるようになります。

［source：］【2018年版】Twitterカードとは？使い方と設定方法まとめ https://saruwakakun.com/html-css/reference/twitter-card
```

　Twitterカードという用語は初めてみかけました。同じような表示はブログでもでき、そちらは別の名称になっていました。URLを指定すると自動でhtmlコードを生成してくれるサイトもありましたが、コマンドで生成する方法が見つからなかったので、それ以上調べるのを断念しました。

［link：］ 関連記事(内部リンク)のブログカードをプラグイン無しで実装する方法［コピペ］｜こまろくNOTE https://www.komaroku.com/related-articles-blog-card

　久しぶりに、それも前回と同じく自ら調べた上で見つけたものですが、ブログカードであったように思います。普通にネットを利用していても見かけない名称ですが、普段ごく普通に見かけるものとなっています。アイキャッチ画像ともいううようです。人目を引きつける意味とか。

　どうもTwilogでは、そのTwitterカードやブログカードが表示されない仕様となっているようです。このカードは視覚的により多くの情報を得ることができますが、それをそのまま伝えにくいという難もあるように思います。リンクの記事を開けばそれまでかもしれないですが。

　以前、gooのブログで、アクセスランキングが一時的に上位になったことがあったのですが、細野豪志の不倫問題を記事にしていたためということがあり、割りと印象的な記憶として残っています。

```
今年もいろいろと国会議員が週刊誌を騒がしたが、議員の恋愛スキャンダルが噴出するたびに必ずといっていいほど出てくるのが細野豪志氏と山本モナの名前。

　細野と言えば、今回の衆議院解散にあたって、いち早く民進党を離党し、政治団体『日本ファーストの会』を設立した若狭勝氏と合流。その後、小池百合子東京都知事が代表となった新党『希望の党』の結党メンバーに名前を連ねた。

　遡ること'06年の10月。当時、細野は35歳。民主党若手のホープと呼ばれ、党の政策調査会長代理を務めていた。

「将来、党を背負って立つと言われていました」（一般紙社会部記者）

［source：］細野豪志氏と山本モナの不倫騒動が消えぬ理由 路チュー写真にインパクト？ - ライブドアニュース http://news.livedoor.com/article/detail/13697167/
```

　時期を確認したかったのですが、2006年10月とあります。細野豪志氏は、次の問題がテレビニュースになり、ネットでも話題をみかけないまま、名前も姿も見かけなくなっていたので、少し気になっていました。

```
〈細野氏　選挙中に5000万円受領　証券会社から　当初報告せず〉

　朝日新聞が細野豪志元環境相（46・無所属）の“裏金疑惑”を報じたのは、6月27日のこと。記事によると、細野氏は昨年10月の衆院選期間中に、証券会社から5000万円を借り入れたという。この借入金が選挙費用であれば報告義務があるが、「選挙運動費用収支報告書」には未記載。さらに当初、個人資産を公開する「資産報告書」にも記載がなかった。


夢も希望もない……　©共同通信社
　細野氏は、「当時、希望の党を設立し、どう運営していくか考える立場だった」ため借り入れたが、結局、必要がなくなり、返済したと釈明している。

［source：］細野豪志氏、5000万円“裏金”報道　スポンサーとのタイ旅行も | 文春オンライン http://bunshun.jp/articles/-/8046
```

　自民党の議員とは違い大きな盛り上がりがなかったのが不思議な現象でした。細野豪志氏は、静岡県内が選挙区で、何かのテレビ番組で密着取材のようなものを受けていたのも印象に残っています。

```
区域［編集］
三島市
富士市（旧・富士川町域を除く）
御殿場市
裾野市
伊豆の国市（旧・伊豆長岡町域）
田方郡
駿東郡

［source：］静岡県第5区 - Wikipedia https://ja.wikipedia.org/wiki/%E9%9D%99%E5%B2%A1%E7%9C%8C%E7%AC%AC5%E5%8C%BA
```

　少し気になったので調べた所、細野豪志氏の選挙区は静岡県5区で、御殿場市が含まれるようです。細野豪志氏の出身地というのは見た記憶がないですが、それも一応調べておきます。

```
生い立ち［編集］
京都府綾部市に生まれ、滋賀県近江八幡市で育った。近江兄弟社中学校、滋賀県立彦根東高等学校、京都大学法学部卒業［1］。京大在学中は佐藤幸治のゼミに所属。大学卒業後、三和総合研究所（現三菱UFJリサーチ&コンサルティング）で研究員を務める。1996年に結婚［2］し、1999年10月に静岡県三島市に移り住んだ。

［source：］細野豪志 - Wikipedia https://ja.wikipedia.org/wiki/%E7%B4%B0%E9%87%8E%E8%B1%AA%E5%BF%97
```

　上記に引用しましたが、「京都府綾部市に生まれ、滋賀県近江八幡市で育った。近江兄弟社中学校、滋賀県立彦根東高等学校、京都大学法学部卒業」とあります。ページには「称号	法学士（京都大学・1995年）」ともあります。

　「1999年10月に静岡県三島市に移り住んだ。」とあるので、これが選挙区となっているのだと考えられます。テレビでは選挙に勝つ目的で選挙区を選んだというような情報も過去に見たような記憶がありましたが、細野豪志の場合は実際に移住されているようです。

　京都府の出身で京大法学部出身というプロフィールは、過去に見かけたことがあったかもしれません。それほど関心の強い人物でもなかったのですが、刑事裁判、刑事事件の歴史や沿革という意味では、静岡県というのは特別な土地柄があるように感じ、かねて注目してきました。

　冤罪事件の代表格の袴田事件も静岡県清水市（現在は静岡市清水区）でしたし、同じ頃に死刑囚から同じ再審無罪となった島田事件も静岡県内の事件であったように記憶しています。

*** 静岡県内の冤罪事件と、ジャーナリストの江川紹子氏の名張事件
    :LOGBOOK:
    CLOCK: [2018-09-26 水 10:59]--[2018-09-26 水 17:02] =>  6:03
    :END:

　どういうわけか11時になったタイミングで、テレビのチャンネルが自動的にNHKに切り替わりました。それまでは北陸放送の「ひるおび」をつけていました。11時のニュースです。「母親と子ども3人が死亡　無理心中か」という見出しが最初のニュースでした。

　5項目ほどある見出しのトップで、最初に取り上げられていましたが、映像のないラジオ放送のような解説だけで、事件の場所も聞かなかったような気がします。11時台に毎回の録画予約を入れているのは11時20分ぐらいからの「3分間クッキング」だけなので、不思議な現象です。

　母親が首を吊った状態で発見されたとあるので、自殺する前に2人の子どもを手にかけていたことになりそうです。たまに見かける態様の事件ですが、精神的に追い詰められ、正気を失っていたものと想像されます。

```
1時間前
01：03
01：03
東京・文京区で母と子ども３人死亡、無理心中か
　２６日朝、東京・文京区で３６歳の母親と、生後８か月から１０歳までの子ども３人、合わせて４人が心肺停止の状態で見つかり、その後、全員の死亡が確認されました。母親は首を吊っていたということで、警視庁は現場の状況を詳しく調べています。

　午前６時すぎ、文京区本郷で、「子どもたちが息をしていない。妻が首を吊っている」と帰宅した夫から通報がありました。警察官が駆けつけたところ、３６歳の母親が首を吊っているのが見つかり、また１０歳の長女、５歳の長男、生後８か月の次女の３人も布団の上で心肺停止の状態で見つかりました。その後、全員の死亡が確認されたということです。

　警視庁は、現場の状況などから、母親が無理心中を図った可能性もあるとみて、詳しい経緯を調べています。

［source：］東京・文京区で母と子ども３人死亡、無理心中か TBS NEWS https://news.tbs.co.jp/newseye/tbs_newseye3482818.html
```

　上記のニュースのようです。「１０歳の長女、５歳の長男、生後８か月の次女の３人も布団の上で心肺停止の状態で見つかりました。」。NHKでは地名を聞かなかったように思うのですが、文京区本郷とあります。これは東京大学の住所ではなかったかと思います。

　文京区本郷の近くには「白山」という地名があって、八百屋於七地蔵尊について調べている時に出てきました。その辺りは、加賀藩の藩邸があったという歴史もあるようです。藩邸が東京大学の近くにあったことは、だいぶん前にも何かで見かけていたような記憶はありました。

　前にも書いていると思いますが、能都中学校の4泊5日の修学旅行の最後の宿泊先が、その東京大学の辺りで、大きなお寺の本堂のような部屋の宿泊地であったことが強く印象に残っています。

　11時20分に「キューピー3分クッキング」が始まりました。チャンネルは北陸放送に戻していました。ひるおび！の放送を中断して、この放送に切り替わるようです。だいぶん前から録画予約にし、料理の参考にしていたのですが、録画を再生で視聴することはほとんどなくなっています。

　時刻は12時05分です。11時30分から石川テレビでPRIMEニュースを見ていましたが、文京区本郷の無理心中のニュースはありませんでした。ポルターガイスト現象のようにチャンネルが変わらないと、知らないままのニュースとなっていたかもしれません。

　PRIMEニュースの終わりの方の石川県内ニュースでは、昨夜、羽咋市で唐戸山神事相撲が行われたという映像のニュースがありました。石川県に50年以上住んでいますが、テレビで唐戸山神事相撲を見たのは初めてかと思います。

　唐戸山神事相撲のことを知ったのも近年のことで、少し聞いたような覚えはあったのですが、羽咋市に住んでいる頃は全く知らなかったように思います。前にGoogleマップで調べたのですが、相撲の行われる神社の場所もよく把握ができませんでした。

　今朝は8時14分にテレビをつけましたが、民放の番組は全て、昨日の貴乃花親方引退表明の話題一色でした。かなり大きな事件や問題でも同じ時間に1局ぐらいは別の内容の放送ということがこれまではほとんどだったのですが、同じ時間に全て同じだったというのは珍しいかと思います。

```
《特徴》
「唐戸山神事相撲」は、相撲好きであったといわれる羽咋神社の祭神・磐衝別命(いわつくわけのみこと)の遺徳をしのんで、毎年、命日の9月25日に行われている相撲です。 

「唐戸山相撲」が行われる場所は、四方にかがり火が炊かれ、すり鉢状の地形の中央に土俵を設けた、日本最古と伝えられている野外の相撲場です。一説には、唐戸山の土を掘ってミコトの御陵を作ったからすり鉢状となったともいわれています。 

［source：］唐戸山神事相撲 （からとやましんじずもう） | 郷土芸能・民俗芸能 | 日本伝統文化振興機構(JTCO) http://www.jtco.or.jp/japanese-culture/?act=detail&id=108&p=0&c=19
```

```
「唐戸山神事相撲」の前日の９月２４日と当日２５日は、羽咋神社となりの本念寺で大法要（羽咋法事）が営まれ、羽咋駅前から国道までの約５５０ｍの商店街は、終日、歩行者天国となり、道路両脇に様々な露店が軒を並べて賑わいます。羽咋では初秋を飾る伝統的な行事になっています。 

［石川県指定無形民俗文化財］ ［羽咋市指定無形民俗文化財］ 
提供： 羽咋市商工会 様 

［source：］唐戸山神事相撲 （からとやましんじずもう） | 郷土芸能・民俗芸能 | 日本伝統文化振興機構(JTCO) http://www.jtco.or.jp/japanese-culture/?act=detail&id=108&p=0&c=19
```

　羽咋市には平成14年11月25日頃から平成21年3月15日まで住んでいましたが、歩行者天国となる大きな催しというのも全く見たことがありません。一度、市内で神輿を見かけましたが、車で動かし、同行者も少なく、珍しい光景だと思いながら見ていたことはありました。

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3191.016431269615!2d136.77665701529236!3d36.8899551799302!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5ff768be6bce5987%3A0x2beb907672690f09!2z5ZSQ5oi45bGx55u45pKy5aC0!5e0!3m2!1sja!2sjp!4v1537932393933" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

　上記にGoogleマップを埋め込みました。前に調べたときは、羽咋川の手前で市内の中心部と認識していたのですが、今回調べると、羽咋警察署より手前で、羽咋市内中心部の手前側になります。その辺りに個人病院があって、平成18年10月、指のケガをした時に治療を受けた憶えがあります。

　羽咋市の病院のことも今まですっかり忘れていましたが、機械に挟まれ指の先が潰れたようなケガでした。そのケガで休職中に、金沢地方検察庁に行き、そのあと安藤健次郎さんの自宅に会いに行ったのです。自宅に行くことは担当事務官の遠塚さんに話していました。

　Googleマップでは、初めに８番らーめん羽咋店が目につき、羽咋警察署で周辺の位置を確認したのですが、場所は、平成15年当時と変わっていないように思います。羽咋市に住み始めて最初の頃に何度か食事をしたのですが、その後は、存在自体を忘れ店に立ち寄ることもなかったと思います。

　8番ラーメン羽咋店から金沢に向かい500メートルぐらいだったように思いますが、右手にパチンコ店がありました。「センリ」という店であったように思います。今回のGoogleマップでは、そのパチンコ店の存在が跡形もなく見当たらなくなっています。

<iframe src="https://www.google.com/maps/embed?pb=!1m26!1m12!1m3!1d223.4982229273064!2d136.77863943808273!3d36.88056708263735!2m3!1f-75.6945504413153!2f45!3f0!3m2!1i1024!2i768!4f35!4m11!3e6!4m3!3m2!1d36.8813324!2d136.7754845!4m5!1s0x5ff768a5fdea6fbb%3A0x52a63f0f62576b58!2z44CSOTI1LTAwNDUg55-z5bed55yM57695ZKL5biC57Kf55Sf55S644Kt77yU77yR!3m2!1d36.8811423!2d136.7756751!5e1!3m2!1sja!2sjp!4v1537933536906" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

　国道沿いをストリートビューで見つけました。Googleマップでは駐車場に車がありますが、ストリートビューでは全く車がとまっておらず、営業しているようには見えませんでした。

　「パチンコ＆スロットパーラーセンリ」という店名です。経路を調べると「8番ラーメン羽咋店」から900メートル、徒歩で11分と出ていました。

パチンコ＆スロットパーラーセンリ、〒925-0045 石川県羽咋市粟生町キ から ８番らーめん 羽咋店 - Google マップ https://www.google.co.jp/maps/dir/36.8813324,136.7754845/%E3%80%92925-0045+%E7%9F%B3%E5%B7%9D%E7%9C%8C%E7%BE%BD%E5%92%8B%E5%B8%82%E7%B2%9F%E7%94%9F%E7%94%BA%E3%82%AD%EF%BC%94%EF%BC%91/%E7%9F%B3%E5%B7%9D%E7%9C%8C%E7%BE%BD%E5%92%8B%E5%B8%82%E5%85%B5%E5%BA%AB%E7%94%BA%E5%B7%B3%EF%BC%91%EF%BC%91+%EF%BC%98%E7%95%AA%E3%82%89%E3%83%BC%E3%82%81%E3%82%93+%E7%BE%BD%E5%92%8B%E5%BA%97/@36.8849805,136.7724082,1740m/data=!3m2!1e3!4b1!4m15!4m14!1m0!1m5!1m1!1s0x5ff768a5fdea6fbb:0x52a63f0f62576b58!2m2!1d136.7756751!2d36.8811423!1m5!1m1!1s0x5ff768bdd20e63d9:0x9bd239b367d4822b!2m2!1d136.777896!2d36.888863!3e2?hl=ja

　ここはモトケンこと矢部善朗弁護士（京都弁護士会）ともゆかりのあるパチンコ店です。ブログのコメント欄から追放された後の休日、パチンコ機の「伝説の巫女」で5万円か6万円ほど勝ちました。大当たりで「大願成就」などと出てきたのがとりわけ印象的でした。

　羽咋市と静岡県は特につながりがないので、このエントリーではかなり横に逸れてしまいました。羽咋警察署についても書いておきたいことがあるので、またその時に続きを書きたいと思います。

```
島田事件（しまだじけん）とは1954年3月10日に静岡県島田市で発生した幼女誘拐殺人、殺人死体遺棄事件である。被告人が死刑の確定判決を受けたが、1989年に再審で無罪になった冤罪事件。四大死刑冤罪事件の一つ（免田事件、財田川事件、松山事件、島田事件）。日本弁護士連合会が支援していた。

［source：］島田事件 - Wikiwand https://www.wikiwand.com/ja/%E5%B3%B6%E7%94%B0%E4%BA%8B%E4%BB%B6
```

　まず島田事件です。静岡県の島田市が静岡県のどの辺りなのか正確に思い出せないのですが、再審無罪となったのは平成元年になってからだったようです。前にも調べたことがありましたが、ずっと昭和の終わり頃のニュースとばかり思ってきました。

　当時は４つほど、死刑囚が再審無罪となりましたが、元死刑囚がメディアに顔写真で取り上げられたりしていたのは、免田事件だけだったように記憶にあります。余りテレビを見ることのない時期だったと思いますが、連日で長い間、テレビで大きく報道されていたことを憶えています。

```
財田川事件（さいたがわじけん）は、1950年（昭和25年）2月28日に起きた強盗殺人（刺殺）事件とそれに伴った冤罪事件である。四大死刑冤罪事件の一つ（免田事件、財田川事件、松山事件、島田事件）。日本弁護士連合会が支援していた。 なお、地名の「財田」ではなく川の「財田川」と呼称する由来は、1972年に再審請求を棄却した裁判所の文言で越智伝判事が「財田川よ、心あらば真実を教えて欲しい」と表現したことである［1］。

概要
1950年2月28日、香川県三豊郡財田村（現三豊市）で、闇米ブローカーの男性（当時63歳）が全身30箇所を刃物でめった刺しにされて殺害され、現金1万3000円を奪われた。

［source：］財田川事件 - Wikiwand https://www.wikiwand.com/ja/%E8%B2%A1%E7%94%B0%E5%B7%9D%E4%BA%8B%E4%BB%B6
```

　こちらでは島田事件とは異なり、「。四大死刑冤罪事件の一つ（免田事件、財田川事件、松山事件、島田事件）」と時代背景のようなものも書いてあります。松山事件というのは鉄道絡みの事件かと思ったのですが、そちらは「松川事件」だったと思い出しました。

　財田川事件は香川県の事件だったようです。免田事件が熊本県の八代市辺りの事件であったことはよく憶えていたのですが、これは初めて知ったような気もします。リンクを紹介しましたが、時間も掛かるので記事はほとんど読んでいません。

```
松山事件（まつやまじけん）は、1955年（昭和30年）10月18日に、宮城県志田郡松山町（現大崎市）にて発生した放火殺人事件と、それに伴った冤罪事件である。四大死刑冤罪事件の一つ（免田事件、財田川事件、松山事件、島田事件）。日本弁護士連合会が支援していた。

概要
1955年（昭和30年）10月18日、宮城県志田郡松山町の農家が全焼し、焼け跡からこの家に住む一家4人である家主（当時54歳）、家主の妻（当時42歳）、夫婦の四女（当時10歳）と長男（当時6歳）の焼死体が発見された。遺体解剖の結果、長男以外の頭部に刀傷らしきものが認められ、殺人および放火事件として捜査本部が設置された。

［source：］松山事件 - Wikiwand https://www.wikiwand.com/ja/%E6%9D%BE%E5%B1%B1%E4%BA%8B%E4%BB%B6
```

　松山事件というのは、愛媛県松山市の事件名なのか、それとも免田栄氏のように名前から事件名がついたのかと考えたのですが、宮城県の事件でした。現在の宮城県大崎市とありますが、長距離トラックの仕事で通過することがちょくちょくあった古川市が大崎市になったことは知っていました。

　Googleマップで大崎市志田町を調べると、東北自動車道の大和インターの近くで、そういえば東北自動車道にそのような名前のインターがあったことを思い出しました。これまで古川インターかと思っていたのですが、石巻から塩釜に立ち寄らないときは、大和インターから高速に乗っていたようです。

　宮城県大和町とありましたが、宮城県で大和といえば、石巻市出身の佐藤大和弁護士です。2,3日前に久しぶりにバイキングで姿を見ました。今日は、北周士弁護士ともお仲間でYouTube動画などを配信している田村隼人弁護士がバイキングに出演しています。

　同じ石川テレビで、このあとの情報番組グッディでは、ずいぶん前からたびたび常連として出演をみている田村隼人弁護士ですが、バイキングで出演を見たのは今日が初めてです。

　司会者の坂上忍さんからとりたてた紹介もなかったので、佐藤大和弁護士に代役を頼まれての出演という可能性もあるのかと考えました。北周士弁護士との3人は、よほど馬も合うのか親しくしているようです。

　四大死刑冤罪事件という名称は初めてみましたが、この４つの事件のうち、2件は静岡県内の事件だと思っていました。実際は、島田事件だけでした。

[link:] » 奇跡体験!アンビリバボー　冤罪事件SP　10月30日 - YouTube https://t.co/6wt2z3icUB

[link:] » 紅林 事件 - Google 検索 https://t.co/amwecuMNJs

```
現在の静岡県藤枝市出身。国家地方警察静岡県本部刑事課員として、1941年（昭和16年）8月から翌1942年（昭和17年）8月にかけて起きた浜松連続殺人事件などの数々の事件を解決した名刑事であると言われ、多くの表彰を受けた。

その一方で、自身が担当した幸浦事件（死刑判決の後、無罪）、二俣事件（死刑判決の後、無罪）、小島事件（無期懲役判決の後、無罪）、島田事件（死刑判決の後、無罪）の各事件で、無実の者から拷問で自白を引き出し、証拠を捏造して、数々の冤罪を作ったとして批判された。

取調べにおいて、拷問とそれによって得た自白を、いかにして合法とするかを考案したとして「拷問王」と評された。紅林は様々な拷問の手法を考案したが、実行には直接関与せず、部下に指示を出していた。また二俣事件における山崎兵八の書籍においては、真犯人と思われる人物からの収賄の疑惑も暴露されている。

上記4事件中、島田事件を除く3事件が一審・二審の有罪判決の後に無罪となり、島田事件も最高裁での死刑判決確定後の再審で無罪が確定した。幸浦事件・二俣事件の有罪判決破棄差し戻し時点で、当時御殿場警察署次席警部の地位にあった紅林は、非難を浴びた県警上層部によって、吉原警察署駅前派出所へ左遷された。しかも交通巡視員待遇という、実質的な二階級降任であった。

世間や警察内部から非難され、精神的に疲弊しきっていたが、1963年7月、幸浦事件の被告人に無罪判決が確定したことを機に気力がつきて警察を引退。同年9月に脳出血により急死した。


［source：］紅林麻雄 - Wikipedia https://ja.wikipedia.org/wiki/%E7%B4%85%E6%9E%97%E9%BA%BB%E9%9B%84
```

　紅林警部についてGoogle検索したところ、動画があったので視聴したところ、弘前大学教授夫人殺人事件の特集でした。この事件のことは知っていましたが、冤罪事件であったことは記憶になかったように思います。真犯人が名乗り出ての再審無罪判決だったとのことです。

　平成6年頃から読んでいた別冊ジュリストにも、この事件の事件名は記載があったかもしれません。その後、モトケンこと矢部善朗弁護士（京都弁護士会）がブログで弘前市の検察庁で検事をしていたと書いていたので、一緒に記憶するようになりました。

　青森県の弘前市も長距離トラックの仕事で行ったことがあり、国道7号線で通過するだけのこともありましたが、一度だけ、弘前市内からリンゴを積んで北九州市の市場まで運んだことがありました。ほとんどは碇ヶ関インターから青森インターまで東北道に乗っていました。

　弘前市といえば、弘前城の桜の花見が有名ですが、ＰＣ遠隔操作事件の被告人と母親を、佐藤博史弁護士が花見の旅行に招待したという話でも印象に残るところで、その佐藤博史弁護士のことを、モトケンこと矢部善朗弁護士（京都弁護士会）は真犯人であることの発覚後、尊敬すると評価していました。

　紅林というのは、人名としては他に見たことも聞いたこともない珍しいものですが、スーパーなどのリンゴでは、そのような名前の品種をたびたび見てきたように思います。リンゴはほとんど食べないし、買うことも滅多にないのですが、青果物の仕事では取り扱うことは多かったです。

　袴田事件の関連で紅林警部のことをネットで知ったのはずいぶん前のことです。まだ羽咋市に住んでいた2009年より前だったようにも思うのですが、記憶ははっきりしなくなっています。再審開始の決定が出た後だと、2009年より後になると思います。検索に言葉を1つ付け加えると出てきました。

　二俣事件のことを、さきほどの四大死刑冤罪事件の1つとして数えていたとも考えられますが、紅林警部補のことを知り、静岡県が冤罪事件や拷問捜査において特別な土地柄と思ったことは紛れのないことです。袴田事件も紅林警部の元部下が取り調べをしたという話だったと思います。

　さきほど消していたテレビをつけて、しばらくしてからチャンネルをミヤネ屋に変更したのですが、その前のグッディも貴乃花親方の引退届を取り上げています。テレビの時刻を見ると15時12分で、番組の後半になっていて、全国ニュースのコーナーを見逃したことに気が付きました。

```
1984年（昭和59年）7月11日、無罪判決。28年7ヶ月にも及ぶ獄中生活に終止符が打たれて無罪となった斎藤は7516万8000円の刑事補償金を受け取るも、裁判費用の借金返済に消えた（再審請求以降の裁判費用は借金ができず、支援団体のカンパでまかなっていた）。故郷に戻り、仙台市の弁護士事務所で一時期、働くなどした。その後、鹿島台町の自宅に戻り、母と暮らしながら清掃員などとして働いた。アムネスティ日本支部などの団体で講演活動をしていたが、長期間死刑囚として過ごした間の年金は支給されず、晩年は生活保護を受給していた。精神的苦痛を理由に1億4300万円の国賠訴訟を起こしているが、訴訟内容は裁判費用の請求でなく精神的苦痛による損害賠償であるため、2001年（平成13年）に棄却されている（一方、足利事件と布川事件の冤罪被害者は刑事補償金以外にも裁判費用を受け取っている。）。斎藤は2006年（平成18年）7月5日に多臓器不全のため75歳で死去。母も2008年（平成20年）12月24日、101歳で入所先の施設で亡くなった。

［source：］松山事件 - Wikiwand https://www.wikiwand.com/ja/%E6%9D%BE%E5%B1%B1%E4%BA%8B%E4%BB%B6
```

　時刻は15時50分です。ブラウザのページのタブを閉じようかと思ったのですが、記事に目を通すと「。28年7ヶ月にも及ぶ獄中生活に終止符が打たれて無罪となった斎藤は7516万8000円の刑事補償金を受け取るも、裁判費用の借金返済に消えた」などとありました。

　昭和59年当時だと現在より貨幣価値は高かったのではないかと思いますが、7千5百万円の刑事補償金が裁判費用の返済に消え、再審請求以降は支援団体のカンパでまかなっていたとあります。

　同じ死刑囚から再審無罪で釈放された免田事件の免田栄氏が、弁護士に多額のお金を持って行かれたと強い不満を述べていたことは、以前、何かの本で見かけたようなことがありました。裁判費用として考えられるのは、専門家の鑑定費用かと思いますが、具体的な内容は見当たりません。

　同じ死刑囚の再審無罪事件でも、これまで実際に再審請求の手続きもやりながら調べてきましたが、免田事件だけが突出して情報量が多く、他は影に隠れたような印象もあったので、元死刑囚が公になることを望まなかったのかとも考えていたのですが、触れられたくない関係者がいたのかもしれません。

　無罪判決という結果を出すことが、刑事弁護の醍醐味であり、全ての報いとその後の財産になるという相場が形成されたとも考えられます。えん罪などの専門書でも、同時期の四大死刑冤罪事件で免田事件以外を具体的に取り上げたものは、ほとんど目にしてこなかったと思います。

　その点、免田事件や袴田事件を出し抜くほどに情報が多く大きく取り上げられてきたのが、名張事件でした。近年、映画にもなっているようです。それも能登と縁のある仲代達也氏の主演でした。七尾市となった中島町に演劇堂があることは、前から知っていましたが、半年ほど前にテレビで特集を見ました。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/05/02 18:28％ https://twitter.com/hirono_hideki/status/991610300406247426
&twitter(991610300406247426){theme:light}
> 目撃！にっぽん・選「仲代達矢　亡き妻と作る舞台」
> 
> 2018年5月2日（水）  18時10分～18時45分  の放送内容 https://t.co/n3B7VhgYhk  
▶

　検索がうまく行かないとおもったら達也ではなく達矢でした。5月2日ということは4ヶ月と24日ぐらいになるかと思います。

　パソコン内にファイルが見当たらなかったので、Googleフォトで日付で探し出し、それをダウンロードし、非常上告-最高検察庁御中_ツイッター（@s_hirono）にアップロードしました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:46／2018-09-26 16:43 URL： https://twitter.com/kk_hirono/status/1044855645491613696 https://twitter.com/s_hirono/status/1044854929473581057
&twitter(1044855645491613696){theme:light}
> 2018-05-02_184358＿テレビの画面・目撃！にっぽん・選「仲代達矢　亡き妻と作る舞台」・NHK.jpg https://t.co/DGHK2zPo6G
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:46／2018-09-26 16:43 URL： https://twitter.com/kk_hirono/status/1044855667234930688 https://twitter.com/s_hirono/status/1044854897089413122
&twitter(1044855667234930688){theme:light}
> 2018-05-02_183357＿テレビの画面・目撃！にっぽん・選「仲代達矢　亡き妻と作る舞台」・NHK.jpg https://t.co/tQa2jiPKG4
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:46／2018-09-26 16:43 URL： https://twitter.com/kk_hirono/status/1044855687694753792 https://twitter.com/s_hirono/status/1044854865330130944
&twitter(1044855687694753792){theme:light}
> 2018-05-02_183346＿テレビの画面・目撃！にっぽん・選「仲代達矢　亡き妻と作る舞台」・NHK.jpg https://t.co/uCxqoEUek9
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:46／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855707621892096 https://twitter.com/s_hirono/status/1044854833356963841
&twitter(1044855707621892096){theme:light}
> 2018-05-02_182500＿テレビの画面・目撃！にっぽん・選「仲代達矢　亡き妻と作る舞台」・NHK.jpg https://t.co/8IF8hMctx4
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:46／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855730178797569 https://twitter.com/s_hirono/status/1044854801538985984
&twitter(1044855730178797569){theme:light}
> 2018-05-02_162653＿テレビの画面・NHK連続テレビ小説「カーネーション」　第5週「私を見て」第25回.jpg https://t.co/iCX30zSCFz
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:46／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855752047964160 https://twitter.com/s_hirono/status/1044854769674850304
&twitter(1044855752047964160){theme:light}
> 2018-05-02_161859＿テレビの画面・15分でにっぽん百名山「高尾山」・NHK.jpg https://t.co/pyjoQqGmtQ
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:46／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855785224900608 https://twitter.com/s_hirono/status/1044854736590114818
&twitter(1044855785224900608){theme:light}
> 2018-05-02_155325＿テレビの画面・海の安全と豊漁を祈る　勇壮！能登町小木　とも旗祭り・MRO.jpg https://t.co/usvNvx6A5D
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:47／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855844259737600 https://twitter.com/s_hirono/status/1044854703136362497
&twitter(1044855844259737600){theme:light}
> 2018-05-02_155216＿テレビの画面・海の安全と豊漁を祈る　勇壮！能登町小木　とも旗祭り・MRO.jpg https://t.co/dPQ7PRLv1j
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:47／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855878090969088 https://twitter.com/s_hirono/status/1044854671515557889
&twitter(1044855878090969088){theme:light}
> 2018-05-02_155120＿テレビの画面・行方不明の加賀市議大日山で無事保護.jpg https://t.co/6aAkRmF0XG
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:47／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855900824121345 https://twitter.com/s_hirono/status/1044854639257153536
&twitter(1044855900824121345){theme:light}
> 2018-05-02_141101＿テレビの画面・速報　山口達也「TOKIO辞めます」　TOKIO4人緊急会見・グッディ.jpg https://t.co/GORyTGTenH
◁◁◁

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-09-26 16:47／2018-09-26 16:42 URL： https://twitter.com/kk_hirono/status/1044855926484815879 https://twitter.com/s_hirono/status/1044854607464341505
&twitter(1044855926484815879){theme:light}
> 2018-05-02_080222＿小木港東一文字堤防アジ釣り・揚げたアジの甘酢あんかけ.jpg https://t.co/a4ViyNBwtn
◁◁◁

　テレビの画面を撮影したものをみて、当日の記憶喚起ができたように思います。町内の班で葬式の打ち合わせの集まりがあったのは、その翌日の5月3日のことでした。

2018年03月01日22時54分の登録： REGEXP：”（名張事件｜奥西死刑囚｜奥西勝死刑囚）”／Shoko Egawa（@amneris84）の検索（2010-02-13〜2016-12-26／2018年03月01日22時54分の記録58件） http://hirono2014sk.blogspot.com/2018/03/regexpshoko-egawaamneris842010-02.html

　3月1日となっていますが、ジャーナリストの江川紹子氏のツイートをまとめた記事です。キーワードは（名張事件｜奥西死刑囚｜奥西勝死刑囚）と３つの指定です。半角を全角に置き換えていますが、実際に検索で使った正規表現の指定です。

　MySQLの正規表現は、通常の正規表現ほど高度ではないのですが、Windowsパソコンのワイルドカードよりは、はるかに細かい指定が出来るかと思います。高度な正規表現は、先読み後読みや後方参照ができます。後方参照は文字列の置換によく使うものです。


